### ISSUE TITLE
Engine-only distribution without bundled services

### ISSUE THREAD

**Issue by itzg** [graknlabs/grakn#1182]
I have created [this Docker image, itzg/grakn](https://hub.docker.com/r/itzg/grakn/), that is 600MB :

```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
itzg/grakn          latest              f1bc25a4ec89        13 hours ago        600 MB
```

The goal of my "re-imaging" was to split out the required services into containers of their own such as [this docker-compose.yml](https://github.com/itzg/docker-grakn/blob/master/docker-compose.yml).

It would be good to get the grakn image itself even smaller, so I was wondering if there were plans to create a smaller distribution tgz that doesn't include cassandra, zookeeper, and kafka?

**Comment by burukuru** [comment]
Hi and thanks for contributing with your docker image - it looks really great!
The distribution we have on the GibHub is currently used primarily for demo purposes and therefore has everything bundled in.
We do have plans to create a grakn-engine only package for easier and faster deployments. I reckon within a month or so as we increase testing of the distributed engine.

**Comment by fppt** [comment]
Hi @itzg to further what @burukuru said, we are currently in heavy deployment mode for demo purposes. We will definitely be leaning things out as we go.

**Comment by itzg** [comment]
Sounds great @burukuru and @fppt . Feel free to close out this issue or leave it open as long as needed as a placeholder.

**Comment by marco-scoppetta** [comment]
Closing this as we don't have `zookeeper` to maintain anymore and we are rebuilding new Docker image with Grakn+Cassandra, while also considering a docker container containing Grakn only.
