### ISSUE TITLE
[GUI] relation to self is confusing; edge label hidden by other edge label

### ISSUE THREAD

**Issue by pouledodue** [graknlabs/grakn#1498]
in a relation to self some edges at not shown (because one hides another)
here `prep` edges are missing, hidden by `pobj` edges

![grakn-ui-before](https://cloud.githubusercontent.com/assets/745437/25454214/a9816f68-2a99-11e7-95b6-6cc1b9f0de22.png)

should be like this:

![grakn-ui-after](https://cloud.githubusercontent.com/assets/745437/25454228/b6809aa4-2a99-11e7-9d16-4db966e270fe.png)

**Comment by marco-scoppetta** [comment]
Hi @pouledodue ,

you are right, this is a known bug that we still need to address.

We will need to investigate how to solve this using the available options by [visjs](https://github.com/almende/vis) or make a custom patch for it.

**Comment by marco-scoppetta** [comment]
Hi @pouledodue ,

I spent some time on this today and I manage to find a fix for this, 
now your query is rendered in something like this:

<img width="1219" alt="screen shot 2017-04-27 at 15 04 24" src="https://cloud.githubusercontent.com/assets/6430514/25487055/03c307ea-2b5b-11e7-9a30-e55d307e64f7.png">

This fix will be available in the next Dashboard release to central.

Thank you again,

Marco

**Comment by marco-scoppetta** [comment]
This is fixed in [#1526](https://github.com/graknlabs/grakn/pull/1526).
