### ISSUE TITLE
[GUI] add name/value of embedded resources in the info div

### ISSUE THREAD

**Issue by pouledodue** [graknlabs/grakn#1499]
[UI] add name/value of embedded resources in the info div

Expected behavior: when I click the purple "word: 49392" widget, I expect the info div at top right 
to contain the key/value of Resources linked to to the "word: 49392" so I can identify the instance I clicked;

The info is already available as embedded resources in the HAL response, it would suffice to show it in the top right div. 

![rr](https://cloud.githubusercontent.com/assets/745437/25456031/bef8d6be-2a9f-11e7-89a5-b1b41430ca70.png)

**UPDATE:** : I just found out that sometimes, resources are written in the top right div; sometimes not; For now I can't reproduce the problem.

**Comment by pouledodue** [comment]
also i'd like it to work also when I click on a Relation.
except ti will lead to  another problem since the call to /graph/concept return 500 for relations: 

![b](https://cloud.githubusercontent.com/assets/745437/25456968/92f19a94-2aa2-11e7-9897-b7c13bdf40e5.png)

**Comment by marco-scoppetta** [comment]
Hi @pouledodue, did you manage to reproduce the first issue you have with resource not being displayed in the side panel? I have tried for a while but I failed to reproduced it, I can always see the resources there.

The second issue related to resources will be addressed and discussed in [https://github.com/graknlabs/grakn/issues/1514](#1514).

Thanks

**Comment by pouledodue** [comment]
@marco-scoppetta I will try to reproduce it and give you follow-up on this thursday

**Comment by pouledodue** [comment]
Well, i can't reproduce it; let's close it. I will keep eye open though.
