### ISSUE TITLE
[GUI]  404 Problem accessing /graph/precomputeInferences

### ISSUE THREAD

**Issue by pouledodue** [graknlabs/grakn#1530]
![screenshot](https://cloud.githubusercontent.com/assets/745437/25685965/e4a135d4-3038-11e7-95b4-0e2f8373a5e2.png)

**Comment by marco-scoppetta** [comment]
Hi,

thank you for the feedback,
the "Materialise All" was a temporary feature. We have now removed it in [#1534](https://github.com/graknlabs/grakn/pull/1534).

**Comment by pouledodue** [comment]
ok thanks
