### ISSUE TITLE
Hardcoded env varibles.

### ISSUE THREAD

**Issue by merqurio** [graknlabs/grakn#1720]
Hi there !

I'd like to let grakn use the `brew` installation of cassandra as the default cassandra. If not the DB will be erased on every `brew upgrade grakn`. Why are CASSANDRA_INCLUDE, CASSANDRA_CONF, and CASSANDRA_HOME [hardcoded](https://github.com/graknlabs/grakn/blob/master/grakn-dist/src/bin/cassandra#L32-L34)?

As far as I understand, if I set those variables during the installation, the cassandra used by grakn will be the one that it's already installed and not the embedded one. Am I wrong ? I don't have a broad experience with cassandra 🙂 .

Thanks !

**Comment by fppt** [comment]
Hi @merqurio.

At this stage they are only hardcoded in the startup script. This is just to make it easier to "get-up and go" with Grakn. No need to worry about installing Cassandra yourself etc . . . 

Now saying that it is completely feasible to run on an existing Cassandra instance (as long as the running Cassandra is `2.x`. We actually do it all the time.

What's missing is just amending this startup script to use an existing Cassandra.

> .... Am I wrong ?

Nope you are not wrong. That should work.

**Comment by fppt** [comment]
Another and simpler option is to just do:

```
./grakn-redis.sh start
./grakn-engine.sh start
```

this will bypass using the embedded Cassandra and will just use whatever you configured it to use.

**Comment by merqurio** [comment]
If I dig into the scripts and do a PR to check if the variable is already available in the environment is ok with you ? Something like:
```sh
if [ -z "$CASSANDRA_INCLUDE" ]; then
    export CASSANDRA_INCLUDE="`abs_path`/cassandra.in.sh"
fi  
```
:v:

**Comment by fppt** [comment]
I see no harm in that. Additionally I would include a version check as well. At this stage we only confidently run on Cassandra `2.1.x` so any version other than that especially `3.x` should come with a warning being printed.

**Comment by burukuru** [comment]
Hi @merqurio,

I just had a look at the [brew recipe for Cassandra](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cassandra.rb#L4) and it looks like 3.1 is being used which is not compatible with Grakn.

Your best bet would be to modify the cassandra.yaml file that ships with our package to avoid the data being deleted on upgrade. You will need to change:
```
data_file_directories
commitlog_directory
saved_caches_directory
```
Hope that helps.

**Comment by merqurio** [comment]
Thanks @fppt , I'll do that then.

@burukuru , Don't worry, brew recipe for [2.1.X](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cassandra%402.1.rb) is available too

**Comment by burukuru** [comment]
If you are planning to use Cassandra from Brew, I think the user should start Cassandra from its own scripts as opposed to grakn.sh.
Additionally Redis from Brew should probably be used.
This way only Grakn Engine will need to be started via our scripts by using:
```
grakn-engine.sh start
grakn-engine.sh stop
```
Would that work?

**Comment by merqurio** [comment]
Let me try it I'll let you know, Thanks a lot !
