### ISSUE TITLE
csv migration failed

### ISSUE THREAD

**Issue by xli4217** [graknlabs/grakn#2033]
Hi, I'm trying to follow the migration example. I used the example-csv-migration-pets and followed

`<relative-path-to-Grakn>/bin/grakn.sh clean`
`<relative-path-to-Grakn>/bin/grakn.sh start`
`<relative-path-to-Grakn>/bin/graql.sh -f ./ontology.gql`
`migration.sh csv -i owns.csv -t owns.gql -k grakn`

The commandline prompts _Migration complete_, but at query time nothing can be found. Help would be greatly appreciated. Thanks.

Xiao

**Comment by vmax** [comment]
Closing this as `grakn` no longer supports `graql migrate`; `gql` files are loaded with `grakn console -f <fn> -k <keysp>`
