### ISSUE TITLE
Feature: undo/redo

### ISSUE THREAD

**Issue by kiryaka** [graknlabs/grakn#2135]
Hi,

First of all, thank you for the great work on grakn. I hope the project will become stable and mature soon, and we will be able to use it in prod, not just in R&D playground.

In a current visualizer one inaccurate or occasional click may ruin the whole work by deleting something that is not easy to find or by saturating the picture, bringing to many new nodes that are very hard to clean up from the graph.

Simple undo/redo will fix it to the reasonable extend. So the first feature request is just N level undo/redo feature. N=5 will be awesome, but even N=1 will solve a lot of problems and I believe that one level undo should be very easy to implement.

For us, the ideal solution will probably be the fully traversable list of transformations on the graph, so that user can 1 - save the work for future. 2 - reapply the transformations if a new data inserted in a graph.

**Comment by marco-scoppetta** [comment]
Hi @kiryaka ,

the undo/redo feature is already in our roadmap for future Grakn releases.

Thanks for the useful feedback,

Marco

**Comment by kiryaka** [comment]
Thank you. Do you have a roadmap draft available somewhere? Just to see what to expect in what order. 
Few other really small things:
1. If you can not provide the actual progress, please change loader animation from loading bar to just spinner or something that not imply the percentage of completion.
2. Toast that appear after the query is done disappear too soon. If task is long user rarely will wait for it just sitting and starring to the screen, user will go to other tabs or to drink coffee and when you back at the graph it's really completely unclear - is something changed or not. May be history screen with the results will also solve it. Actually history screen with the ability to select new items that appear after query - will be absolutely amazing :)

Do you guys friendly to outside contributing or it is mostly the internal product and you will rarely put something from outside? I probably can fix most of those things by myself pretty quickly...

**Comment by marco-scoppetta** [comment]
Hi @kiryaka,

sorry for answering only now to this. 
We don't have a draft of roadmap yet as we are undergoing some restructuring in the front-end side of things, in the next release you will already see the changes.

We are indeed friendly to outside contributions and you are welcome to join our Slack Community channel to discuss changes or make new issues here in GitHub, PRs as well are welcome!

Thanks!

**Comment by marco-scoppetta** [comment]
Closing this, tracking the undo/redo possibility in workbase (Dashboard is deprecated) https://github.com/graknlabs/workbase/issues/52
