### ISSUE TITLE
"compute path" is slow

### ISSUE THREAD

**Issue by pouledodue** [graknlabs/grakn#2177]
The command `compute path from 'V32856' to 'V45272';` takes about 15 seconds on my laptop; Would be great if it took under 100ms for prod use.

I'm testing with a tiny graph of under 50 entities/relations.

What should I verify to speed the query ?

```
>>> compute count;
26
```
is as slow

**Comment by duckofyork** [comment]
Both queries should take less than a second, given it's such a small graph.

**Comment by pouledodue** [comment]
```
2017-10-05 15:14:17,128 [graql-session-0] INFO  ai.grakn.graql.ComputeQuery - ShortestPathVertexProgram is called
2017-10-05 15:14:17,384 [graql-session-0] INFO  a.g.g.i.computer.GraknSparkComputer - Creating a new Grakn Graph RDD
2017-10-05 15:14:17,450 [graql-session-0] WARN  a.g.g.i.computer.GraknSparkComputer - HADOOP_GREMLIN_LIBS is not set -- proceeding regardless
2017-10-05 15:14:41,222 [graql-session-0] INFO  ai.grakn.graql.ComputeQuery - ShortestPathVertexProgram is done in 24090 ms
```

**Comment by pouledodue** [comment]
24090 ms

**Comment by pouledodue** [comment]
```>>> compute count;
30```

```
==> grakn.log <==
2017-10-05 15:25:42,019 [graql-session-0] 
INFO  ai.grakn.graql.ComputeQuery - CountMapReduce is called
2017-10-05 15:25:42,203 [graql-session-0] 
INFO  a.g.g.i.computer.GraknSparkComputer - Creating a new Grakn Graph RDD
2017-10-05 15:25:42,206 [graql-session-0] 
WARN  a.g.g.i.computer.GraknSparkComputer - HADOOP_GREMLIN_LIBS is not set -- proceeding regardless
2017-10-05 15:25:53,201 [graql-session-0] 
INFO  ai.grakn.graql.ComputeQuery - CountMapReduce is done in 11178 ms
```

**Comment by lolski** [comment]
Can you try running it multiple times? I want to see if it is slow only on the first time as we're doing a bunch of initialisation

**Comment by WalternativE** [comment]
I experience similar things using `compute` statements on the academy knowledge base.

![compute_vs_aggregate_performance_degradation](https://user-images.githubusercontent.com/5071748/38454169-f8322886-3a61-11e8-870e-8014792359ef.PNG)

The compute query takes a lot longer than the semantically equivalent aggregate query. The same compute query was executed multiple times before in the same grakn instance - so the engine should be warmed up.

I'm testing this on the Windows Subsystem for Linux though, would have to set up a VM to make sure that this is not connected to the environment.

**Comment by marco-scoppetta** [comment]
We are closing this as we have just tested the latest versino of Grakn with sample datasets containing thousands of instances:

`compute count;` completes in about 5 seconds

please open a new issue if you have other problems with analytics features
