### ISSUE TITLE
match $x id in  ('V12345', 'V67890');

### ISSUE THREAD

**Issue by pouledodue** [graknlabs/grakn#2180]
Currently I can do `match $x id 'V12345';` to retrieve a thing.

Matching a set of ids would be useful;

`match $x id in  ('V12345', 'V67890');`

I tried with regexes too with no luck...

**Comment by aelred** [comment]
We're definitely considering a syntax to specify a collection of values.

For now, this is possible with a disjunction:
```
match $x id V12345 or $x id V67890;
```

**Comment by pouledodue** [comment]
great, thanks
