### ISSUE TITLE
Visualizer: help identify entities

### ISSUE THREAD

**Issue by pouledodue** [graknlabs/grakn#2185]
In Visualizer, sometimes is hard to identify quickly which entity is which when we don't have the identifier:
![grakn-github-suggest-orig](https://user-images.githubusercontent.com/745437/31250329-7bd3c60a-a9e8-11e7-8939-0aa5dad2de5a.png)
It would be great if by default, if an `identifier` exists for the entity, that it'd be shown  :
![grakn-github-suggest](https://user-images.githubusercontent.com/745437/31250333-7f7a5c1a-a9e8-11e7-95da-836184ef6b01.png)

or use `description` or anything as long as it is documented

**Comment by marco-scoppetta** [comment]
Hei @pouledodue ,

thanks for the feedback, this is surely a nice feature to have, we will make sure to implement something similar for the following releases and document the fields that will be shown by default.

Thanks
