### ISSUE TITLE
[Feature] insert an object of properties

### ISSUE THREAD

**Issue by idealley** [graknlabs/grakn#2186]
Following the discussion on slack I am proposing to add the following this is related to this issue on [grakn-node](https://github.com/graknlabs/grakn-node/issues/2):

a typical insert call looks like this:
```
 insert $g isa person has firstname "Titus"; has identifier "Titus Groan"; has surname "Groan"; has gender "male";
commit
```
The `has` key word has (no pun intended) to be repeated for each `resource` added, followed by the `resource` `key` and `values`

What if we could send it in the following way:

```
insert $g isa person has
    {
       firstname: 'Titus',
       surname: 'Groan',
       identifier: `${firstname} ${surname}`
       gender: 'male'
    };
commit
```

I stole this idea from cypher...

```js
CREATE (p:Person { name: 'Samuel' })
RETURN p
```

Or you can access nodes with properties directly like that:
```
    (p:Person {name: "Samuel"}) -[:LIVES_IN {date: "2015-3-20"}]-> (:City)
```
Where `p` is a variable `name` a property on the node  with the label `Person`, `date` a property on the relation

**Comment by vmax** [comment]
Closing, this relates to a nonexistent repo (`graknlabs/grakn-node`) so context is probably all lost.

**Comment by haikalpribadi** [comment]
We can now do this using https://github.com/graknlabs/grakn/tree/master/client-nodejs
