### ISSUE TITLE
Question about internal indexing

### ISSUE THREAD

**Issue by markk12** [graknlabs/grakn#2252]
i d like to try grakn . it is my first graph database. I m a curiosity about query language:
does grakn make a index call(i mean on internal indexer) for every vertex subquery and edge subquery present in the query? Pratically it makes many index calls for every query right?

**Comment by fppt** [comment]
Hi @markk12,

In future try to ask your questions on our [discussion platform](https://discuss.grakn.ai/) or [Stackoverflow](https://stackoverflow.com/questions/tagged/grakn). You will likely get your questions answered much faster.

With regards to your query:

> Practically it makes many index calls for every query right?

Yes every graql query results in internal indices being used.

**Comment by vmax** [comment]
Closing since question has been answered
