### ISSUE TITLE
graql console error when changing server.port in conf/grakn.properties

### ISSUE THREAD

**Issue by fraimondi** [graknlabs/grakn#2324]
Hi,
Changing the port to 8080 in grakn,properties causes graql console to fail:
``$ ./graql console -r localhost:8080``
``Websocket closed, code: 1011, reason: RuntimeException``

I'm using Ubuntu 16.04, and the problem happens both with https://grakn.ai/download/latest and also when compiling from source.

**Comment by fraimondi** [comment]
[continue]
DEFAULT_URI seems to be hard-coded in ai.grakn.engine.session.RemoteSession
The attached diff file fixes the issue for me for the command line shell (but if I click on Config in the web interface I get an error "Could not connect to Grakn").

[RemoteSession-diff.txt](https://github.com/graknlabs/grakn/files/1444011/RemoteSession-diff.txt)

**Comment by marco-scoppetta** [comment]
Closing this. Thank you for reporting @fraimondi , this issue is resolved in the latest version of Grakn,
changing `grpc.port` to `8080` in `grakn.properties` and then trying to start console with `grakn console --address localhost:8080` works fine now.
