### ISSUE TITLE
[Bug] Wrong data type

### ISSUE THREAD

**Issue by idealley** [graknlabs/grakn#2367]
I declared a datatype date in a `.gql` file. Then I have imported the schema into grakn `0.17.1` then I did a file with few insert queries and I thought I declared a timestamp (as a long) and used a dummy value `987654321` I got the following error:

```
$ ./graql console -f ~/Projects/grakn-gdpr/schema/queries.gql
The value [in one year] must be of datatype [java.lang.Long]
``` 

The error message should have probably been `[java.util.Date]`

**Comment by aelred** [comment]
Thanks for submitting this issue! I've made a PR to fix it.
