### ISSUE TITLE
[Feature] Kubernetes deployement script and docker container

### ISSUE THREAD

**Issue by usopan** [graknlabs/grakn#2548]
It will be nice to have a kubernetes stateful set script within the core repository only. I will see if I can get it to work then I will submit a pr or else if somebody has already done it Please share.

**Comment by kasper-piskorski** [comment]
Any luck with kubernetes deployments? I tried a simple deployment as defined here with good results:

https://github.com/kasper-piskorski/grakn-kubernetes-cluster
