### ISSUE TITLE
[Bug] Types which have a space in the label can't be chosen in the Types dropdown (in the visualiser)

### ISSUE THREAD

**Issue by jsteggink** [graknlabs/grakn#2555]
When there is a space in the label of a Type, you can't select it it in the visualiser. It should add double quotes around the label. This might also happen with other characters in the label, I'm not sure.

**Comment by marco-scoppetta** [comment]
Hi @jsteggink,

what do you mean with "you can't select it in the visualiser"?

Could you please provides an example or a screenshot?

Thank you!
