### ISSUE TITLE
[Bug] Graql: Defining a rule with the body containing "val =" fails

### ISSUE THREAD

**Issue by Tomen** [graknlabs/grakn#2625]
How to reproduce this:

Create this file named "repro1.gql"
```
define
relationship1
    sub relationship,
    relates role1,
    relates role2;
role1 sub role;
role2 sub role;
entity1
    sub entity,
    has attribute1,
    plays role1;
attribute1 sub attribute datatype string;
entity2
    sub entity,
    has attribute2,
    plays role2;
attribute2 sub attribute datatype string;
rule1 sub rule
when {
    $e1 isa entity1;
    $e1 has attribute1 $a1;
    $e2 has attribute2 $a2;
    $a1 val = $a2;
}
then {
    (role1: $e1, role2: $e2) isa relationship1;
};

```

then do
```
./grakn server stop
./grakn server clean
./grakn server start
./graql console -f repro1.gql
```

This will fail (silently) and the schema is not updated. I discussed the issue with @kasper-piskorski on Slack and he confirmed it, stating 
> from what i can see it looks like a parsing problem, `$x val = $y` gets parsed to`$x val $y` and if you parse it again which happens during validation you get syntax exception

The issue can be worked around for now by matching
```
$a1 val contains $a2;
$a2 val contains $a1;
```

**Comment by aelred** [comment]
Thanks for finding this bug! #2683 should fix the issue.
