### ISSUE TITLE
Starting Engine...........FAILED

### ISSUE THREAD

**Issue by KeruHua** [graknlabs/grakn#2778]
Hello, everyone! By running ./grakn server start I got Storage and Queue start successfully, but failed to start engine. The running environment  is  "Linux version 2.6.32.el6.x86_64, java1.8" while 1.2.0 is the version of Grakn I am trying. The error massage in grakn.log shows "java.lang.RuntimeException: Couldn't get PID of Grakn. Receive " . Just for your concern, I have gone through the discussion in https://discuss.grakn.ai/t/start-grakn-server-with-error-couldnt-get-pid-of-grakn-received/651 but nothing worked. Is there anyone who has got the some issue?

**Comment by lolski** [comment]
Thank you for reporting the bug! Several users have reported similar issues and it is now tracked here: https://github.com/graknlabs/grakn/issues/2778.

I am closing this one.
