### ISSUE TITLE
Maven install fails on Mac OSX 10.13.4

### ISSUE THREAD

**Issue by mateolan** [graknlabs/grakn#2779]
Failed to execute goal on project grakn-core: Could not resolve dependencies for project ai.grakn:grakn-core:jar:1.2.0: The following artifacts could not be resolved: org.apache.tinkerpop:gremlin-core:jar:3.2.5-grakn-SNAPSHOT, org.apache.tinkerpop:tinkergraph-gremlin:jar:3.2.5-grakn-SNAPSHOT: Could not find artifact org.apache.tinkerpop:gremlin-core:jar:3.2.5-grakn-SNAPSHOT in snapshots (https://maven.grakn.ai/content/repositories/snapshots/)

**Comment by mateolan** [comment]
OK--nvm, I'm lame and didn't have prereqs installed...there now, having fun. ~mc

**Comment by qiuwei** [comment]
I confirm this is indeed a problem 
https://maven.grakn.ai/content/repositories/snapshots/org/apache/tinkerpop/gremlin-core/3.2.5-grakn-SNAPSHOT/gremlin-core-3.2.5-grakn-SNAPSHOT.pom

This link is not valid.

Thus mvn couldn't resolve the dependencies correctly.

**Comment by qiuwei** [comment]
BTW, what's the difference between these grakn versions of tinkerpop and the offical ones?

**Comment by qiuwei** [comment]
@mateolan  could you reopen this issue?
