### ISSUE TITLE
Compare to Neo4j ,what is grakn different?

### ISSUE THREAD

**Issue by linghongtao** [graknlabs/grakn#2796]

**Comment by ShalokShalom** [comment]
Well, basically everything on the homepage is unique to Grakn at all.

**Comment by haikalpribadi** [comment]
hi @linghongtao have you seen our website? Here's a good starter (which contains everything you need) : https://grakn.ai/grakn-core
Nothing on that page could be done by Neo4j. Let me know if that helps!

**Comment by lolski** [comment]
Closing as this is not an issue.

@linghongtao, next time also consider posting questions in our [Discuss Forum](https://discuss.grakn.ai/) or [Slack channel]( http://grakn.ai/slack) ;)
