### ISSUE TITLE
Foreground mode missing in 1.2.0

### ISSUE THREAD

**Issue by bkmeneguello** [graknlabs/grakn#2816]
Previously there was a FOREGROUND env, this does not work anymore (see #926)

**Comment by lolski** [comment]
Yes, we realised that and has no plan of bringing it back for the time being. Currently Grakn consisted of 3 processes (storage, queue, engine), and only Engine was made foreground while the other two stays background.

For that reason it is not a true foreground process and therefore does not make much sense as a feature.

Can you elaborate why you need the foreground feature?

**Comment by bkmeneguello** [comment]
I'm working on a Docker of Grakn 1.2.0 (since the official is deprecated) and to keep the server up workarounds are necessary (I've used tail -f to keep de grakn.log output to stdout), but if the server fails to boot, the container doesn't die.
I think the old behavior (keep only engine on foreground) is the best solution for who need some "foreground" process)
Maybe the "foreground" option be used only when we invoke specific services (grakn server start engine -f), In the code, it's just a matter of removing the "&" from the forked process, isn't? Unless there is some conceptual reason to not have this behavior, it's a helpful one.

**Comment by bkmeneguello** [comment]
At least you could provide a reliable pidfile to all of these processes

**Comment by lolski** [comment]
There are pid files for the processes: `/tmp/grakn-storage.pid`, `/tmp/grakn-queue.pid`, `/tmp/grakn-engine.pid`.

Speaking of which, have you check this Docker by one of our community member and see if that fits your need: https://github.com/BFergerson/grakn-docker-toolbox

**Comment by bkmeneguello** [comment]
@lolski LOL, it's just this one I'm working on as colaborator

**Comment by lolski** [comment]
Sounds awesome!

As for foreground mode, we've no plans in bringing this mode back in at the moment simply because we're busy ironing out bootup issues which the users are having.

Is it possible to progress without having the foreground mode built-in?

**Comment by bkmeneguello** [comment]
Yes, with some workarounds.
