### ISSUE TITLE
Dashboard query editor doesn't completely ignore comments

### ISSUE THREAD

**Issue by BFergerson** [graknlabs/grakn#2856]
When running:
```
match $x isa entity; offset 0; limit 30; get;
#aggregate count;
```

from the dashboard visualizer I get:
![image](https://user-images.githubusercontent.com/3278877/41822913-ee1e95dc-77c4-11e8-9ed3-233977f254ae.png)

When running the same query from the console on the dashboard I get a list of entities like expected. This leads to me think that the invalid query error logic isn't ignoring comments correctly.

**Comment by Irtazaraza** [comment]
Hi, We were not able to reproduce this issue on Workbase, which has been released and will take over Dashboard functionalities. If you still find an issue, please report it. Thanks!
