### ISSUE TITLE
graql migrate export produces invalid gql

### ISSUE THREAD

**Issue by tapple** [graknlabs/grakn#2861]
Reproduction (on grakn-dist-1.2.0 on macOS 10.12.6 (16G1408)):
```bash
./graql console -f examples/basic-genealogy.gql
./graql migrate export -schema -data -k grakn | tee gen-full-test.gql
./graql console -k test2 -f gen-full-test.gql
```

Issues:
* no define keyword before the schema section (line 1, mismatched input 'label' expecting {<EOF>, 'compute', 'match', 'insert', 'define', 'undefine'})
* no insert keyword before the data section (line 86, defining property 'isa' is not supported, try `insert`)
* produces "plays @" instead of has (line 2)
* Produces label statements for attributes (line 2, Cannot create a label {@has-age-owner} starting with character {@} as it is a reserved starting character)

Currently, the export command doesn't seem useful, as I cannot use it to move data from one database to another

**Comment by vmax** [comment]
Closing this as `grakn` no longer supports `graql migrate`
