### ISSUE TITLE
Ctrl-C during a long-running query does not abandon it

### ISSUE THREAD

**Issue by tapple** [graknlabs/grakn#2872]
I have a query that takes hours (I've actually never yet seen it finish). I set log level to TRACE, and ran this query from python, and, after a while, pressed ctrl-c to give up and study the trace. I was surprised to see that the trace was still plugging away, seemingly oblivious that the client requesting the data left 5 or 10 minutes ago

I tried the same query on graql console, and  pressed ctrl-c. It continues running after the console hung up

**Comment by tapple** [comment]
I am using grakn 1.2.0 on macOS 10.12.6 (16G1408)

**Comment by marco-scoppetta** [comment]
Closing as we are going to keep track of this feature in here: https://github.com/graknlabs/grakn/issues/3595
