### ISSUE TITLE
Tinyurl in Graql cheatsheet points to page not found

### ISSUE THREAD

**Issue by BFergerson** [graknlabs/grakn#2886]
**URL**: http://tinyurl.com/graqldocs
**Points to**: http://dev.grakn.ai/docs/graql/graql-overview.html

**Comment by lolski** [comment]
@BFergerson thank you.

This is the cheatsheet in question: https://dev.grakn.ai/docs/api-references/graql-cheatsheet

**Comment by sorsaffari** [comment]
@lolski I'll be fixing some technical issue in the docs, over this weekend. This and changes in the cheatsheet itself are included.

**Comment by lolski** [comment]
Thank you, @sorsaffari !
