### ISSUE TITLE
Merge conflict remanents in Grakn Academy site

### ISSUE THREAD

**Issue by kkleidal** [graknlabs/grakn#2994]
Relatively minor, but while reading through Grakn Academy, I found a merge conflict issue:
https://github.com/graknlabs/grakn/blame/master/docs/pages/academy/3-schemas/3-schema-building.md#L64
Currently visible on the live site: http://dev.grakn.ai/academy/schema-building.html

**Comment by sorsaffari** [comment]
@kkleidal thank you for reporting this Ken :)
