### ISSUE TITLE
Software Architect for ML/AI

### ISSUE THREAD

**Issue by turgaytemel** [graknlabs/grakn#3007]
Hi,

I have just installed grakn_1.3.2with Python 3.6. When I import it within python code I get following error message. I would appreciate any help regarding this issue.

Best
Turgay Temel, PhD

>>> import grakn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/turgaytemel/anaconda3/lib/python3.6/site-packages/grakn/__init__.py", line 20, in <module>
    import grpc
  File "/Users/turgaytemel/anaconda3/lib/python3.6/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc._cython import cygrpc as _cygrpc
ImportError: dlopen(/Users/turgaytemel/anaconda3/lib/python3.6/site-packages/grpc/_cython/cygrpc.cpython-36m-darwin.so, 2): Symbol not found: _deflate
  Referenced from: /Users/turgaytemel/anaconda3/lib/python3.6/site-packages/grpc/_cython/cygrpc.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/turgaytemel/anaconda3/lib/python3.6/site-packages/grpc/_cython/cygrpc.cpython-36m-darwin.so

**Comment by flyingsilverfin** [comment]
Hi @turgaytemel 
It looks like you're using anaconda as your package manager; we've currently only tested with pip/pipenv/standard python installations. Perhaps try using these tools? Let me know if you have issues with them too!

By the way, the 'title' of the issue should be the topic of your question/problem, not your job title ;)

**Comment by turgaytemel** [comment]
Hi Joshua,

Thanks for response. I will try. I think I need to change the paths too.

Best
Turgay

**Comment by vmax** [comment]
Replaced by #4351
