### ISSUE TITLE
Graql: Make Graql cost function use graph metrics

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3028]
_This issue was originally posted by @haikalpribadi  on 2017-02-08 16:34_.

Use the data in the graph to inform estimated cost. This could include:
Number of instances per type
Number of role-players per relation
Number of resources with particular values
For scalability, these values should either be calculated continuously (e.g. incrementing a counter when adding an instance) or sampled randomly.

**Comment by marco-scoppetta** [comment]
Closing this as we have now implemented keyspace statistics and continue to improve on those.
