### ISSUE TITLE
Revisit how we interpret a role type occuring multiple times in a relation query

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3038]
_This issue was originally posted by @haikalpribadi  on 2017-02-13 17:07_.

```
define
# Relations
relation1 sub relation
has-role role1
has-role role2;
#Roles
role1 sub role;
role2 sub role;
#Entities
entity1 sub entity
plays-role role1
plays-role role2;
#Data
$a isa entity1;
$b isa entity1;
(role1:$a, role2:$b) isa relation1;
```
Query:
```
>>> match $x (role2:$y, role2:$z) isa relation1;
```
yields no results.
Note that "role2" is used twice in the query.
This should instead yield a single result, where $y and $z are both bound to $b from the insert query.

**Comment by flyingsilverfin** [comment]
The semantics of roles being played multiple times (it is allowed) has been settled
