### ISSUE TITLE
Deletion produces tumbstones

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3040]
_This issue was originally posted by @haikalpribadi  on 2017-03-13 14:03_.

Just creating this so we don't forget this bug report from Antonio Messina:
Hi guys. Just to let you know that periodically I have to increase _tombstone_failure_threshold_ in cassandra.yaml, otherwise the engine stops working and cassandra.log gets filled by

Scanned over XXXXX tombstones in biograph.system_properties; query aborted (see tombstone_failure_threshold)It usually happens after I delete a significant number of entities and resources. Please, note that "significant" means thirty thousand or more entities, and 5x resource.
Do the tombstones eventually get cleaned up?
I think they don't. So that number grows over the time. But that's just a supposition

**Comment by marco-scoppetta** [comment]
We have never experienced this issue and never managed to reproduce it. Closing this as it's pretty old and we will create a new issue if we'll ever manage to reproduce this, hopefully with more meaningful description and steps to reproduce it.
