### ISSUE TITLE
Aggregate queries needs read/write mode configuration

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3063]
_This issue was originally posted by @haikalpribadi  on 2017-05-09 12:18_.

Aggregate queries are currently not considered to be read-only, because you can register custom aggregates that could modify the graph.
We want to add a config/parameter/property to the aggregate queries that determine whether it is read-only=[TRUE|FALSE], where the default value is TRUE. This value is not configurable for system/native aggregate queries. If a user adds their own custom aggregate queries, they can define whatever they want.

**Comment by haikalpribadi** [comment]
Aggregate queries are always "read" queries now.
