### ISSUE TITLE
When session is closed outside of shell, the shell should refresh the session or die completely.

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3087]
_This issue was originally posted by @haikalpribadi  on 2017-05-15 18:34_.

**Comment by marco-scoppetta** [comment]
Just verified this behaviour and the one described in https://work.grakn.ai/entity/18517-incorrect-transaction-shutdown-in-graql-shell. The issue is resolved in Grakn 1.5 in `master`, the 2 sessions are independent and don't interfere with each other.
