### ISSUE TITLE
Analyse multithreading possibilities when reasoning

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3089]
_This issue was originally posted by @kasper-piskorski  on 2017-05-19 17:13_.

As the reasoning is a granular operation, we can leverage multithreaded processing to traverse the resolution tree faster. Possible approaches: - spawning multiple single-threaded transactions - using single multi-threaded transaction (Janus provides these)

**Comment by marco-scoppetta** [comment]
Closing this as we don't have hierarchy as we did in TP, so this is a duplicate of: https://github.com/graknlabs/grakn/issues/4216
