### ISSUE TITLE
Implement SNB Complex Queries

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3091]
_This issue was originally posted by @haikalpribadi  on 2017-06-07 13:24_.

This task has been created to track the progress of implementing the SNB complex queries. So far 4 have now been done but there are another 10 left. The optimisation needs to catch up before implementing more. The main hold ups right now are: shortest path is really slow we cannot sort twice (or even once) by resource without fetch ALL data from the graph and sorting locally.

**Comment by marco-scoppetta** [comment]
Closing this as we are implementing our own Benchmarking system, not using SNB anymore.
