### ISSUE TITLE
Engine: import Graql files via GRPC

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3101]
_This issue was originally posted by @haikalpribadi  on 2017-07-04 19:40_.

**Comment by marco-scoppetta** [comment]
Closing this as we decided to implement Parser and Query builder on each client (https://github.com/graknlabs/graql/issues/57)
That would allow us to read from file all the text and then `parseList()` would give us all the queries that we can batch in transactions and send to the server.
