### ISSUE TITLE
Grakn package in Ubuntu's apt repository

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3103]
_This issue was originally posted by @haikalpribadi  on 2017-07-06 17:51_.

1. Create deb package 2. Upload package to ppa 3. Automate/script package deployment 4. Directory structure change to just /opt/ Our own PPA: https://launchpad.net/~graknlabs/+archive/ubuntu/grakn

**Comment by vmax** [comment]
Building/deploying DEBs is on our schedule currently.
