### ISSUE TITLE
very slow query related to resources edges

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3109]
_This issue was originally posted by Sheldon Hall  on 2017-07-28 18:50_.

On SNB short query 3 we have had a massive slow down in getting the results. This is the query: 
```
 String query = "match " + "$person isa person; " + "( $person, $personId) isa key-person-id; " + "$personId val " + operation.personId() + "; " + "$rel ($person, $friend) isa knows; " + "( $rel, $date) isa has-creation-date; " + "( $friend, $friendId) isa key-person-id; " + "( $friend, $fname) isa has-first-name; " + "( $friend, $lname) isa has-last-name;"; 
```
 I can reduce it to this and still see the problem 
```
 String query = "match " + "$person isa person; " + "( $person, $personId) isa key-person-id; " + "$personId val " + operation.personId() + "; " + "$rel ($person, $friend) isa knows; " + "( $rel, $date) isa has-creation-date; "; 
```
 it seems to be related to fetching the date in this particular way. It is happening on 0.16.0-SNAPSHOT right now.

**Comment by marco-scoppetta** [comment]
closing as this is referring to snb which we dont use anymore and grakn 0.16.0-SNAPSHOT
