### ISSUE TITLE
Compressed logs are not stored in /logs directory

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3153]
_This issue was originally posted by @haikalpribadi  on 2017-10-03 15:01_.

This can be seen when running jobs on Jenkins. The main `grakn.log` file goes in `/grakn-package/logs/`, but the compressed old logs all end up in `/` as demonstrated by Thanh: 
```
 > ls -l ... -rw-rw-r-- 1 ubuntu ubuntu 6072613 Oct 3 09:53 grakn.log-2017-10.0.log.gz -rw-rw-r-- 1 ubuntu ubuntu 2842888 Oct 3 10:04 grakn.log-2017-10.1.log.gz ... 
```

**Comment by marco-scoppetta** [comment]
Closing as this was solved a while ago
