### ISSUE TITLE
Unignore New Graql Property Tests

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3161]
_This issue was originally posted by @haikalpribadi  on 2017-10-26 13:03_.

The following Property tests are currently failing randomly: 
```
GetQueryPropertyTest#matchIsAMorphism_From_PatternsWithConjunction_To_AnswersWithNaturalJoin 
GetQueryPropertyTest#conjunctionIsAssociative
GetQueryPropertyTest#conjunctionIsDistributiveOverDisjunction
GetQueryPropertyTest#disjunctionIsAssociative
GetQueryPropertyTest#anyPropertyCanBeExecutedOnAMatchQuery 
```
 These should be solved at some point

**Comment by kasper-piskorski** [comment]
Theproperty tests for graql queries/patterns do not exist anymore. We might revive them at some point, then it would be the time to look into this.
