### ISSUE TITLE
'match isa relationship; aggregate count;' query returns different answer when compared to 'compute count in relationship'

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3245]
_This issue was originally posted by @lolski  on 2018-01-02 16:33_.

reproduce by running the test `ExhaustiveReadOnlyQuery_EndToEndTest#verify_MatchRelationshipAggregateCount_Vs_ComputeCountInRelationship`

**Comment by marco-scoppetta** [comment]
The test does not exist anymore and we already have similar issue https://github.com/graknlabs/grakn/issues/3962
