### ISSUE TITLE
Engine: track and provide instance count per type

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3285]
_This issue was originally posted by @lolski  on 2018-02-08 19:07_.

Goal:
Track and provide instance count per type.
When implemented, query planner can use it for making better decisions: Let's say you have a keyspace containing 10 millions of people living in 'London', of which 10 of them happen to be working at the 'Xian restaurant'. Given a query such as "get me a person who lives in 'London' and works at the 'Xian restaurant', the query planner should intuitively start by from the predicate "working at the 'xian restaurant'", rather than "living in 'London'".

**Comment by lolski** [comment]
This issue is a duplicate to https://github.com/graknlabs/grakn/issues/4232. Closing.
