### ISSUE TITLE
Thing.plays() does not report attribute roles

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3291]
_This issue was originally posted by @haikalpribadi  on 2018-03-07 19:53_.

```
Entity bob = ...; 
Attribute bobsAge = ...; 
bob.attribute(bobAge); 
// We expect to see `@has-age-owner`, but we don't 
bob.plays().forEach(System.out::println); 
```
 This is because we only look at reified relationships.

**Comment by flyingsilverfin** [comment]
Closed since attributes no longer are owned via implicit relations
