### ISSUE TITLE
Clean keyspace from console and reload data from file -> keyspace not listed in dashboard

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3301]
_This issue was originally posted by @marco-scoppetta  on 2018-03-19 15:47_.

In graql console: - clean grakn keyspace - reload data from file - commit Check web dashboard and the grakn keyspace is not listed among the available keyspaces anymore, after restarting Grakn an reloading page it appears again

**Comment by marco-scoppetta** [comment]
Verified that this is now solved in Grakn 1.4.2
