### ISSUE TITLE
Grakn: Support daemon manager for running as a service

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3315]
How can we make running Grakn in the background easier for our users? Appending with ./grakn server with & is hacky - so we shouldn't rely on that. The proper way is to create systemctl service files, but that's not common knowledge for beginners and not simple. 

https://github.com/graknlabs/benchmark/blob/330bb8cd1ef134bf7cd634eba643212a9b0060c3/.grabl/automation.yml#L211-L233

This is what we need to automate:

```
cat > grakn-core.service <<- EOM
[Unit]
Description=Grakn Core
[Service]
Type=simple
Environment=SERVER_JAVAOPTS=-Xmx16G
ExecStart=/home/grabl/$GRABL_REPO/dist/grakn-core-all-linux/grakn server
Restart=on-failure
RestartSec=10
KillMode=process
[Install]
WantedBy=multi-user.target
EOM
sudo mv grakn-core.service /etc/systemd/system/
bazel run //test:grakn-core-extractor-linux -- dist/grakn-core-all-linux
cd ./dist/grakn-core-all-linux/
sudo systemctl daemon-reload
sudo systemctl start grakn-core
```

**Comment by vmax** [comment]
@haikalpribadi 

In the new release, for Grakn Core installed via APT it would be possible to do:
`sudo systemctl [start|stop|restart] grakn-core`

**Comment by haikalpribadi** [comment]
that's amazing @vmax ! well done! make sure to elaborate this in the release announcements, and also add it to docs, Max!
