### ISSUE TITLE
Graql: roles should only be owned by multiple relationships if there is one super-relationship that declares it

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3413]
_This issue was originally posted by @haikalpribadi  on 2018-03-27 14:49_.

For example:

parenthood sub relationship,
    relates parent,
    relates child;

fatherhood sub relationship,
  relates father as parent,
  relates child;

motherhood sub relationship,
  relates mother as parent,
  relates child;
The above should be allowed. But the following schema delaration should not be allowed to follow the above, because teachership is not subtype of parenthood or vice-versa.

teachership sub relationship
    relates teacher,
    relates child;

**Comment by flyingsilverfin** [comment]
Resolve in Grakn 2.0
