### ISSUE TITLE
(intermittent) cleaning keyspace crashes storage

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3453]
_This issue was originally posted by @jmsfltchr  on 2018-04-18 14:57_.

Grakn keyspaces can't be cleaned From within the Graql console (under a non-default keyspace) running "clean" throws an exception (below). This killed the storage, and the Grakn server couldn't be stopped, it just hanged. So we used pkill to kill Grakn, which also requires deleting the .pid files in /tmp. This isn't obvious and should be in a FAQ or some such. >>> clean Are you sure? This will clean ALL data in the current keyspace and immediately commit. Type 'confirm' to continue. >>> confirm Cleaning... Exception in thread "main" io.grpc.StatusRuntimeException: UNKNOWN at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:221) at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:202) at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:131) at ai.grakn.rpc.generated.GraknGrpc$GraknBlockingStub.delete(GraknGrpc.java:183) at ai.grakn.remote.RemoteGraknTx.delete(RemoteGraknTx.java:213) at ai.grakn.graql.shell.GraqlShell.clean(GraqlShell.java:290) at ai.grakn.graql.shell.GraqlShell.executeRepl(GraqlShell.java:195) at ai.grakn.graql.shell.GraqlShell.start(GraqlShell.java:155) at ai.grakn.graql.shell.GraqlConsole.start(GraqlConsole.java:122) at ai.grakn.bootup.Graql.run(Graql.java:82) at ai.grakn.bootup.Graql.main(Graql.java:65) Jamess-MacBook-Pro:grakn-dist-1.2.0 jamesfletcher$ ./graql console --keyspace transportation_example Jamess-MacBook-Pro:grakn-dist-1.2.0 jamesfletcher$ ./graql console --keyspace transportation_example Jamess-MacBook-Pro:grakn-dist-1.2.0 jamesfletcher$ ./grakn server status ============================================================================= ________ _____ _______ __ __ __ __ _______ ___ | __ || _  | _ || | / /|  | | | _ || | | | |__|| | | | | | | || | / / |  | | | | | || | | | ____ | |_| / | |_| || |/ / | | | | |_| || | | ||_ || _  | _ || _  | _ | | _ || | | |__| || |   | | | || |   | |  | __ | | | || | |________||__| __|__| |__||__| __|__| __||__||__| |__||___| Grakn: The Database For AI ============================================================================= Storage: NOT RUNNING Queue: RUNNING Engine: RUNNING Jamess-MacBook-Pro:grakn-dist-1.2.0 jamesfletcher$ ./grakn server stop ============================================================================= ________ _____ _______ __ __ __ __ _______ ___ | __ || _  | _ || | / /|  | | | _ || | | | |__|| | | | | | | || | / / |  | | | | | || | | | ____ | |_| / | |_| || |/ / | | | | |_| || | | ||_ || _  | _ || _  | _ | | _ || | | |__| || |   | | | || |   | |  | __ | | | || | |________||__| __|__| |__||__| __|__| __||__||__| |__||___| Grakn: The Database For AI ============================================================================= Stopping Engine.....................................................................................pq.-..kill ...^CJamess-MacBook-Pro:grakn-dist-1.2.0 jamesfletcher$ pkill -9 java Jamess-MacBook-Pro:grakn-dist-1.2.0 jamesfletcher$ ./grakn server stop ============================================================================= ________ _____ _______ __ __ __ __ _______ ___ | __ || _  | _ || | / /|  | | | _ || | | | |__|| | | | | | | || | / / |  | | | | | || | | | ____ | |_| / | |_| || |/ / | | | | |_| || | | ||_ || _  | _ || _  | _ | | _ || | | |__| || |   | | | || |   | |  | __ | | | || | |________||__| __|__| |__||__| __|__| __||__||__| |__||___| Grakn: The Database For AI ============================================================================= Stopping Engine...NOT RUNNING Stopping Queue....SUCCESS Stopping Storage...NOT RUNNING

**Comment by marco-scoppetta** [comment]
Closing as it seems to be fixed in the latest Grakn version. Reopen if it happens again in other edge cases.
