### ISSUE TITLE
Matching many independent entities takes too long or fails

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3457]
_This issue was originally posted by @jmsfltchr  on 2018-04-19 18:58_.

Without using the Grakn migrator(s), I create my own migration in Python. It is easier in some cases to write large match, insert statements rather than breaking them down. A common use for the match in this case is simply to specify variables that need to be in scope for the insert. These variables are independent so the match ought to be very fast, but it isn't.
You shouldn't need the whole db to reproduce the behaviour. On Jason's request I tried a long match of independent variables with only a schema and no data. This seems to reproduce the issue. The code and schema for this is in Dropbox/Datasets/bug #19993 Matching many independent entities takes too long or fails.zip
The offending match statement is in graql_match.txt
debug.py runs this query
This bug occurs in the stable release 1.2.0
In case you need the whole db, the current version of the transportation Grakn is in Dropbox/Datasets/grakn-transportation-example.zip, the keyspace is transportation-example

**Comment by flyingsilverfin** [comment]
Closed in Grakn 2.0, this issue is resolve as we no longer have the slow graph-sort to begin with
