### ISSUE TITLE
Subtype of attribute should have the same datatype of its super type

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3459]
_This issue was originally posted by @haikalpribadi  on 2018-04-20 12:10_.

e.g.
define
name sub attribute datatype string;
surname sub name;
Here surname should have datatype string, and the following should throw an exception:
define
name sub attribute datatype string;
surname sub name datatype long;

**Comment by alexjpwalker** [comment]
The functionality as requested is implemented. However there is a bug, that allows you to override the value type in the sub attribute: https://github.com/graknlabs/grakn/issues/5791.

Nonetheless, closing this issue now
