### ISSUE TITLE
Graql: schema disappears after loading invalid data

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3743]
_This issue was originally posted by @haikalpribadi  on 2018-05-08 16:23_.

1. `./graql console` 2. `load schema.gql` # file attached 3. `match $x sub thing; get;` # you can confirm here that the schema was loaded correctly 4. `load data.gql` # file attached, you can confirm here that the DATA IS INVALID from the error message 5. `match $x sub thing; get;` # **HERE IS THE BUG** : you will see that the schema is now gone. This should not be the case

**Comment by marco-scoppetta** [comment]
@haikalpribadi I cannot find the data you are referring to in here (lost from TP migration), I have tried loading invalid data in console after defining the schema and in all the occasions the schema remains untouched. I will close this as this seems to be solved.
