### ISSUE TITLE
Graql Migration: bug when using for loop variables not in scope

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3761]
_This issue was originally posted by @marco-scoppetta  on 2018-05-17 14:35_.

If in a migrator script we have something like: 
```
 if( != '-') do{ for (element in @split(, ',')) do { match $g isa Gene has approved_symbol ; $s isa SNP has identifier ; insert(gene: $g, snp: $s) isa SNP_GENE_ASSOCIATION; } } 
```
 Migrator will fail complaining that cannot be found in the data row: 
```
 Query not sent to server: Key [] not present in data: [{P=3, A1=T, STAT=-5, metabolite=test, organism=Can familiaris, SNP=ch78, gene=ENPP1, NMISS=432, TEST=ADD, CHR=4, BP=709978, BETA=-0.1}]
```
 This is because inside the `for` loop the scope is erroneously limited to `element`.

**Comment by marco-scoppetta** [comment]
Closing as we deleted Migrator.
