### ISSUE TITLE
Make LHS and RHS of rules explicit conjunctions

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3766]
_This issue was originally posted by @haikalpribadi  on 2017-01-18 15:17_.

Currently LHS and RHS are generic `Patterns`. However, rules do not currently support disjunctions. Instead we can explicitly define them to only accept conjunctions.

**Comment by flyingsilverfin** [comment]
Closed as of Grakn 2.0 - incidentally, here we have specialised the types for the `when` and the `then`
