### ISSUE TITLE
Drivers: fail when there is a mismatch between client driver and the running Grakn instance

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3782]
_This issue was originally posted by @haikalpribadi  on 2017-06-07 12:05_.

For every version of the python driver it will only support a certain set of grakn versions.
Whenever the user attempts to use the python driver which a version of grakn which is not supported by that specific driver version the user should be informed of the mismatch.
This will be marked as complete when the user receives an appropriate error message when using mismatched versions.

**Comment by marco-scoppetta** [comment]
We are providing a compatibility table for this, e.g: http://dev.grakn.ai/docs/client-api/nodejs

Also when client and server use different protocol is immediately clear from the errors that we get.
