### ISSUE TITLE
Migrating from a TSV file

### ISSUE THREAD

**Issue by neda-abolhassani** [graknlabs/grakn#3783]
I am migrating a TSV file to Grakn using the instructions provided in the documentation. I have created the schema and the migrator files and I have loaded the schema to the knowledge graph. The input TSV file has a very simple format:

col1  col2
data1  data2

The migrate command (containing the -s \t ) throws the error:

ERROR: Exception while loading data (disabling debug mode might skip and continue): Invalid CSV {col1	col2=da}
Migration complete.

Would you please guide me on how to resolve this issue?

**Comment by vmax** [comment]
@neda-abolhassani could you share command(s) you ran & input files so we could debug this?

**Comment by vmax** [comment]
Closing this as `grakn` no longer supports `graql migrate`
@neda-abolhassani you could utilize `client-python`, `client-nodejs` or `client-java` to load the data
