### ISSUE TITLE
Graql dumps logs to STDOUT when log file not writable

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3785]
_This issue was originally posted by @haikalpribadi  on 2017-06-13 13:04_.

If Graql can't write to the file/dir from logback.xml everything goes to the CLI and Graql exits. This happens in a prod env as described in https://work.grakn.ai/entity/15572 We should handle this better: - fall back to no logs - fall back to logs in /tmp - fall back to log file in the current directory

**Comment by marco-scoppetta** [comment]
We have disabled logging in Console, everything is printed to `stdout` and `stderr` now.
