### ISSUE TITLE
Grakn doesn't start with a partial Cassandra cluster

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3795]
_This issue was originally posted by @haikalpribadi  on 2017-09-13 16:28_.

In a cluster environment, with a Grakn node unavailable, we cannot properly start a Grakn node as Grakn crashes due to "TokenRangeOfflineException". This is important for the simplified dist where we start all 3 parts at once. Storage will start and wait for the rest of the cluster to become online but Engine will fail. Do we want to allow Engine to start with a warning?

**Comment by marco-scoppetta** [comment]
This is quite old, we now have only 2 components instead of 3. Also the cluster is now only in KGMS
