### ISSUE TITLE
Make command line flags consistent

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3798]
_This issue was originally posted by @haikalpribadi  on 2017-10-13 11:16_.

For example, `-n` in `graql console` means infer, whereas in `graql migrate` it means dry-run.
Helpful guide from Thanh: http://www.catb.org/esr/writings/taoup/html/ch10s05.html
Shell commands:
-k, --keyspace
keyspace of the graph
-e, --execute
query to execute
-f, --file
graql file path to execute
-r, --uri
uri to factory to engine
-b, --batch
graql file path to batch load
-s, --size
the size of the batches (must be used with -b)
-a, --active
the number of active tasks (must be used with -b)
-o, --output
output format for results
-u, --user
username to sign in
-p, --pass
password to sign in
-n, --infer
perform inference on results
-m, --materialise
materialise inferred results
-h, --help
print usage message
-v, --version
print version
Migration options:
-v, --verbose
Print counts of migrated data.);
-h, --help
Print usage message.);
-k, --keyspace
Grakn graph. Required.);
-u, --uri
Location of Grakn Engine.);
-n, --no
Write to standard out.);
-c, --config
Configuration file.);
-r, --retry
Number of times to retry sending tasks if engine is not available);
-d, --debug
Immediately stop and fail migration if an error occurs);

**Comment by marco-scoppetta** [comment]
No more migrator
