### ISSUE TITLE
Incorrect Transaction Shutdown In Graql Shell

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3807]
_This issue was originally posted by @haikalpribadi  on 2017-11-20 18:06_.

If you have multiple graql shell session open it looks like you could possibly shut down the wrong one depending on the order of your operations. **Steps to reproduce:** 1. Start grakn. 2. Connect to grakn using `graql console`. Do a query, for example `match $x isa entity; limit 10; get;`. It will work. Do it a couple of times and do not close the console (keep it connected to the database). 3. Connect from another terminal to grakn using `graql console`. Do the same query. Will succeed. Do not close the console. 4. Try to execute the same query in the first console. Console hangs (no response). [Problem 1]. 5. Try to execute the same query in the second console. Works normally. 6. In first console press Ctrl-C. First console terminates. 7. Try to execute the same query in the second console. You get `WebSocket closed, code: 1011, reason: NullPointerException` [Problem 2]. **So We Have Two Problems:** 1. Opening the second instance of graql shell connected to the same keyspace as the first closes the connection of the first instance. 2. Closing the first instance will close the connection of the second instance. **Notes:** This was reported by a community member most likely working on 0.17.1 This also happens when you replace one of the graql console sessions with a driver. For example the NodeJs Driver

**Comment by marco-scoppetta** [comment]
This issue is now resolved in Grakn 1.5 release candidate. The sessions are independent and do not interfere with each other creating strange behaviours.
