### ISSUE TITLE
Multithread close causes NullPointerException

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3808]
_This issue was originally posted by @haikalpribadi  on 2017-11-21 16:34_.

To replicate this try to make multiple threads that - Open the session - Write 100 times (including something like a getEntityType or getAttributeType) - Close the session You should get a stacktrace like this java.lang.NullPointerException: Null value at ai.grakn.concept.AutoValue_ConceptId.(AutoValue_ConceptId.java:15) at ai.grakn.concept.ConceptId.of(ConceptId.java:62) at ai.grakn.kb.internal.concept.ElementFactory.getOrBuildConcept(ElementFactory.java:82) at ai.grakn.kb.internal.concept.ElementFactory.buildResource(ElementFactory.java:98) at ai.grakn.kb.internal.concept.AttributeTypeImpl.lambda$putAttribute$2(AttributeTypeImpl.java:126) at ai.grakn.kb.internal.concept.TypeImpl.addInstance(TypeImpl.java:132) at ai.grakn.kb.internal.concept.TypeImpl.putInstance(TypeImpl.java:111) at ai.grakn.kb.internal.concept.AttributeTypeImpl.putAttribute(AttributeTypeImpl.java:140) at com.yahoo.ycsb.db.GraknDB.putData(GraknDB.java:217) at com.yahoo.ycsb.db.GraknDB.put(GraknDB.java:201) at com.yahoo.ycsb.db.GraknDB.insert(GraknDB.java:158) at com.yahoo.ycsb.DBWrapper.insert(DBWrapper.java:221) at com.yahoo.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:562) at com.yahoo.ycsb.ClientThread.run(Client.java:467) at java.lang.Thread.run(Thread.java:748) This is actually the expected behaviour that happens in other cases: java.lang.IllegalStateException: Graph has been closed at org.janusgraph.graphdb.tinkerpop.JanusGraphBlueprintsGraph.getAutoStartTx(JanusGraphBlueprintsGraph.java:70) at org.janusgraph.graphdb.tinkerpop.JanusGraphBlueprintsGraph.getCurrentThreadTx(JanusGraphBlueprintsGraph.java:89) at org.janusgraph.graphdb.tinkerpop.optimize.JanusGraphTraversalUtil.getTx(JanusGraphTraversalUtil.java:79) at org.janusgraph.graphdb.tinkerpop.optimize.JanusGraphStep.lambda$new$0(JanusGraphStep.java:61) at org.apache.tinkerpop.gremlin.process.traversal.step.map.GraphStep.processNextStart(GraphStep.java:139) at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:128) at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:38) at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.next(DefaultTraversal.java:200) at ai.grakn.kb.internal.concept.ConceptImpl.lambda$new$1(ConceptImpl.java:60) at ai.grakn.kb.internal.cache.Cache.get(Cache.java:107) at ai.grakn.kb.internal.concept.ConceptImpl.currentShard(ConceptImpl.java:240) at ai.grakn.kb.internal.concept.ThingImpl.type(ThingImpl.java:320) at ai.grakn.kb.internal.concept.ThingImpl.(ThingImpl.java:99) at ai.grakn.kb.internal.concept.EntityImpl.(EntityImpl.java:46) at ai.grakn.kb.internal.concept.EntityImpl.create(EntityImpl.java:54) at ai.grakn.kb.internal.concept.ElementFactory.lambda$buildEntity$7(ElementFactory.java:127) at ai.grakn.kb.internal.concept.ElementFactory.getOrBuildConcept(ElementFactory.java:75) at ai.grakn.kb.internal.concept.ElementFactory.getOrBuildConcept(ElementFactory.java:83) at ai.grakn.kb.internal.concept.ElementFactory.buildEntity(ElementFactory.java:127) at ai.grakn.kb.internal.concept.EntityTypeImpl.lambda$addEntity$0(EntityTypeImpl.java:59) at ai.grakn.kb.internal.concept.TypeImpl.addInstance(TypeImpl.java:132) at ai.grakn.kb.internal.concept.EntityTypeImpl.addEntity(EntityTypeImpl.java:59) at com.yahoo.ycsb.db.GraknDB.putData(GraknDB.java:209) at com.yahoo.ycsb.db.GraknDB.put(GraknDB.java:201) at com.yahoo.ycsb.db.GraknDB.insert(GraknDB.java:158) at com.yahoo.ycsb.DBWrapper.insert(DBWrapper.java:221) at com.yahoo.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:562) at com.yahoo.ycsb.ClientThread.run(Client.java:467) at java.lang.Thread.run(Thread.java:748)

**Comment by marco-scoppetta** [comment]
we currently have tests that check concurrency and we have never seen this issue - we have done a lot of rework on transactions and sessions, so I will close this for now and we will create new issue if this happens again
