### ISSUE TITLE
"No results" when querying without variables on dashboard

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3811]
_This issue was originally posted by @haikalpribadi  on 2017-12-13 13:20_.

e.g. 
```
 match $x sub entity; get; 
```
 will return at least one result (`entity` itself) always. But: 
```
 match sub entity; get; 
```
 is the same, with the variable removed. This should have one empty result `{ }`, indicating that "yes there is something that is `sub entity;`". However, when we run the latter query in the dashboard console we see "No results found for this query". In the Graql shell and elsewhere we see the expected `{ }`.

**Comment by marco-scoppetta** [comment]
The new Graql syntax does not allow `match sub entity; get;` anymore:

```
grakn>  match sub entity; get; 
Error: syntax error at line 1: 
 match sub entity; get; 
       ^
no viable alternative at input 'match sub'
syntax error at line 1: 
```
