### ISSUE TITLE
Improve empty Shard issues when deleting Instances - fragmentation problem

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3838]
_This issue was originally posted by @lolski  on 2018-02-08 19:22_.

Goal
Let's say the new shard creation threshold is set to 10000.
When the total entity being held by the shard 1 reaches 10000, Grakn will proceed to create a new shard, shard 2. When receiving new entities, they will be held by shard 2.
The problem arises when we delete entities on the old shard. Let's say we delete all entities held by shard 1. Even though now shard 1 is completely empty, by the current algorithm Grakn will still hold new entities in shard 2.
In practice, this will lead to a "fragmentation problem" where we have many empty shards or shards with very few nodes.

**Comment by flyingsilverfin** [comment]
Shards no longer exists in Grakn 2.0
