### ISSUE TITLE
Add possible runtime exceptions to Javadoc

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3839]
_This issue was originally posted by @haikalpribadi  on 2018-02-15 11:37_.

For public API methods, add possible runtime exceptions and their causes to the Javadoc. e.g. 
```
 /** * Commits any changes to the graph and closes the transaction. You must use the {@link GraknSession} to * get a new open transaction. * * @throws InvalidKBException when the transaction contains graph mutations which does not conform to the Grakn * knowledge model. */ @API void commit(); 
```
 Note that it is not part of the method signature, just the Javadocs. For now this is only necessary for API methods.

**Comment by marco-scoppetta** [comment]
no Javadoc no more
