### ISSUE TITLE
Graql: analytics stops working (often seen when the computer went to sleep for an extended period of time)

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3880]
_This issue was originally posted by @jmsfltchr  on 2018-04-20 19:47_.

When Grakn was affected, no compute functionality was working, including 
```
compute count
```
. We asserted that the Hadoop graph couldn't see any elements in the graph. We believe that this occurs having loaded the tube dataset via python client, let mac sleep, then waking it up and running any `compute` query, for instance `compute count;` will return 0 when there are many concepts present.

**Comment by lolski** [comment]
Marking the ticket as invalid. The issue happens a few times so we're sure that it exists, but we have been unable to find a way to reliable reproduce it.
