### ISSUE TITLE
Graql: Should not specifying variable returns nothing?

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3882]
_This issue was originally posted by @jmsfltchr  on 2018-04-23 14:09_.

```
 >>> match id "V2154552"; get; {} 
```
 This returns nothing, but the following works fine: 
```
 >>> match $x id "V2154552"; get; $x id V2154552 isa stop; 
```
 As I understand it the first should have created it's own variable and returned something. Also tried: 
```
 >>> match isa stop; get; {} 
```
 Whereas 
```
match $x isa stop; get;
```
 returned all stops

**Comment by marco-scoppetta** [comment]
New Graql syntax does not allow this type of behaviour anymore. It is mandatory to specify a variable when matching.
