### ISSUE TITLE
(intermittent) Keyspace cleaning not always working

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3893]
_This issue was originally posted by @jmsfltchr  on 2018-05-04 13:53_.

Repeatedly cleaning and re-adding the schema and re-importing data whilst developing a custom migration script eventually caused weird behaviour in the DB.

**Comment by marco-scoppetta** [comment]
This is a bit too generic and we have done quite a lot of work on this, so it's likely to be resolved. If not we should open a more specific issue with reproducible examples.
