### ISSUE TITLE
Explanation not available via gRPC, "explanation-query" is misnamed

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3897]
_This issue was originally posted by @jmsfltchr  on 2018-05-09 13:52_.

Getting back an explanation via gRPC hasn't yet been investigated, but is highly desirable.
Presently in Python responses from the server contain 
```
explanation query
```
 which is just the query used by dashboard to expand the variables.
e.g. a query such as:

```

match
$s1 id V57408; # $1525794485053660 id V57408;
$s2 id V86256; #$1525794485053662 id V86256;
$r id V176256; # $1525794485053664 id V176256;
$j(start: $s1, finish: $s2, leg-route: $r) isa journey-leg; # "start": $1525794485053660, finish: $1525794485053662, leg-route: $1525794485053664) isa journey-leg;};
get $j;

```

has an explanation query:

```

match
{
{
{
$1525794485053664 id V176256;
("start": $1525794485053660, finish: $1525794485053662, leg-route: $1525794485053664) isa journey-leg;
};
$1525794485053660 id V57408;
};
$1525794485053662 id V86256;
};
get $1525794485053664, $1525794485053660, $1525794485053662;

```

**Comment by haikalpribadi** [comment]
@jmsfltchr did you ever get to confirm that client-python returns answer explanations? cc: @flyingsilverfin

**Comment by jmsfltchr** [comment]
I haven't yet confirmed, I've asked @flyingsilverfin if he can take a look while I'm away

**Comment by marco-scoppetta** [comment]
Nodejs and Python clients now have explanation.
