### ISSUE TITLE
Grakn: Improve clean command

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3904]
_This issue was originally posted by @jmsfltchr  on 2018-05-15 14:31_.

We are suspicious that clean causes integrity issues. The method by which cleaning the whole db works also needs revisiting.

**Comment by kasper-piskorski** [comment]
@lolski @jmsfltchr What's the status on this?

**Comment by lolski** [comment]
We didn't manage to dig deeper but also, I don't think we've experienced the issue ever again @kasper-piskorski

**Comment by lolski** [comment]
https://github.com/graknlabs/grakn/issues/5316
