### ISSUE TITLE
compute query fails with out of memory when attempting to find a path of 20 steps on a graph 5K entities

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3913]
_This issue was originally posted by @lolski  on 2018-05-18 20:32_.

Steps to reproduce: 1. Install https://github.com/jmsfltchr/grakn-examples/tree/tube-visualisation 2. Run `compute path from `, which has a distance of 20 or more

**Comment by flyingsilverfin** [comment]
Closed since in Grakn 2.0.0  compute has been removed, to be brought back poperly at a later date
