### ISSUE TITLE
QueryBuilder syntax different for match... get; vs match... get $x;

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3964]
_This issue was originally posted by @jmsfltchr  on 2018-06-12 14:54_.

In Java it struck me as weird that things change drastically depending upon whether or not you supply variables to get queries: 
```
Var x = Graql.var(); 
Var y = Graql.var(); 
Stream r1 = qb.match(x).get(x); 
List r2 = qb.match(x).get(x, y).execute(); 
List r3 = qb.match(x).get().execute(); 
```

**Comment by marco-scoppetta** [comment]
Not clear enough and a lot of changes have happened in Client Java.
