### ISSUE TITLE
Refactor Concept API Cache

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#4007]
_This issue was originally posted by @haikalpribadi  on 2018-06-26 22:08_.

**Comment by lolski** [comment]
Did you remove the core API caching in 1.5 already @marco-scoppetta ?

**Comment by marco-scoppetta** [comment]
We have moved things around and removed cache for schema concepts. I am not sure what this issue is specifically referring to. I will close this for now given that we are already planning to work on caching next and this issue is not providing any addition info

**Comment by marco-scoppetta** [comment]
this is done in https://github.com/graknlabs/grakn/pull/5112 and in https://github.com/graknlabs/grakn/pull/5113
