### ISSUE TITLE
Enable multi-query transaction request on tx.query(...)

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#4030]
_This issue was originally posted by @Irtazaraza  on 2018-07-03 16:21_.

Until we build a Parser on the client side, it would nice to have the option to specify `multi` as a param in `tx.query()` so that the user can send a big string containing multiple graql queries: needed so that we can have the "import from file" functionality on the client side

**Comment by flyingsilverfin** [comment]
Decided not relevant for the forseeable future, we want to implement the required parsers
