### ISSUE TITLE
compute count; and match $x; aggregate count; give different results

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#4072]
_This issue was originally posted by @jmsfltchr  on 2018-07-13 19:41_.

Often big differences between`compute count` and `match $x; aggregate count;` For instance in my current dataset `compute count` = 316 `match $x; aggregate count;` = 828

**Comment by marco-scoppetta** [comment]
closing as duplicate of https://github.com/graknlabs/grakn/issues/3962
