### ISSUE TITLE
@has-<attribute-name> not available during schema loading

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#4086]
_This issue was originally posted by @jmsfltchr  on 2018-07-16 19:54_.

The following schema doesn't work: 
```
 define step sub attribute datatype string; index sub attribute datatype long; @has-step has index; sequence sub entity, has step; 
```
 But, splitting it up and loading it in 2 parts does work: 1: 
```
 define step sub attribute datatype string; index sub attribute datatype long; sequence sub entity, has step; 
```
 2: 
```
 define @has-step has index; 
```

**Comment by kasper-piskorski** [comment]
This is currently by design: implicit relation types are added when you specify `has`, `key`.

**Comment by alexjpwalker** [comment]
This issue is no longer valid because implicit relations are gone.
