### ISSUE TITLE
grakn KeyspaceStore could leverage JanusGraphManager - see description

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#4087]
_This issue was originally posted by @marco-scoppetta  on 2018-07-17 14:31_.

https://static.javadoc.io/org.janusgraph/janusgraph-core/0.2.0/org/janusgraph/graphdb/management/JanusGraphManager.html

**Comment by marco-scoppetta** [comment]
Duplicate of https://github.com/graknlabs/grakn/issues/4965
