### ISSUE TITLE
Basic match query takes over a minute to return

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#4100]
_This issue was originally posted by @jmsfltchr  on 2018-07-18 15:22_.

For this dataset, with 300+ rules present, some basic match queries take a long time to return, such as: 
```
 match $x isa diagnosis; offset 0; limit 60; get; 
```
 
```
 match $x isa observation; offset 0; limit 60; get; 
```
 The 300 rules are added automatically via python (along with a handful of other inserts), all data added manually is attached. The issue with the `diagnosis` query is that the 300+ rules in the deutsche telekom dataset all infer an additional roleplayer to a `diagnosis`. Presumably for this reason all of the rules are being checked to decide if any diagnoses should be inferred. Perhaps this isn't necessary?

**Comment by marco-scoppetta** [comment]
There is no dataset attached and a lot of work has been done on reasoner, specially on pruning rules, so we are closing this. Open a new issue if this is still relevant when using other datasets, but please do attach schema and data.
