### ISSUE TITLE
Add SonarCloud reporting to our CI

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#4187]
_This issue was originally posted by @haikalpribadi  on 2018-08-09 00:04_.

Add Sonar source code analysis report to our CI. You can find the maven command below. I imagine we could just add it to the very end of the build job, before parallelisation happens - just an idea. 
```
 mvn sonar:sonar  -Dsonar.organization=graknlabs  -Dsonar.host.url=https://sonarcloud.io  -Dsonar.login=0e7fa3e66933e150011ec823c840c60529d05063 
```

**Comment by vmax** [comment]
@haikalpribadi @lolski do you think we still need it?

**Comment by haikalpribadi** [comment]
yes, we still need it, @vmax. But neither @lolski or I have had the time to look into it.
