### ISSUE TITLE
Engine: rewrite

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#4207]
_This issue was originally posted by @haikalpribadi  on 2018-08-13 21:45_.

This requirement is an umbrella requirement for:
1. Simplification of codebase
2. Removal of unneeded / dead code
Specific goals:
1. Remove migration
2. Remove REST API
3. Merge with grakn-bootup
4. Merge with grakn-kb
5. Merge with grakn-factory

This issue needs #3153, needs #3824, needs #3839, needs #3841, needs #3975, needs #3994, needs #4001, needs #4002, needs #4003, needs #4008, needs #4009, needs #4011, needs #4014, needs #4034, needs #4041, needs #4046, needs #4056, needs #4057, needs #4139, needs #4140, needs #4148, needs #4208, needs #4278, needs #4283, needs #4286, needs #4310

**Comment by marco-scoppetta** [comment]
Done
