### ISSUE TITLE
Graql: multithreaded reasoning

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#4216]
_This issue was originally posted by @haikalpribadi  on 2018-08-14 20:15_.

Self explanatory, we want to either
use multithreaded transaction or
use multiple transactions
to split the work required for resolution traversal.

As the reasoning is a granular operation, we can leverage multithreaded processing to traverse the resolution tree faster. Possible approaches: - spawning multiple single-threaded transactions - using single multi-threaded transaction (Janus provides these)

**Comment by flyingsilverfin** [comment]
Reasoning in Grakn 2.0 is multi-threaded by default
