### ISSUE TITLE
Graql: Compute queries are not returning anything

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#4217]
_This issue was originally posted by @tomassabat  on 2018-08-15 13:24_.

Compute count queries returned wrong answers. The following queries returned wrong answers or 0: 
```
 >>> compute count in protein; 0 >>> compute count in PPI_ASSOCIATION; 0 
```

**Comment by marco-scoppetta** [comment]
Compute queries are working correctly in 1.5. Create new issue if we notice wrong behaviour in analytics again
