### ISSUE TITLE
Engine/Graql: improve the efficiency of produced query plans by incorporating a 'query statistic' component to order starting points

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#4232]
_This issue was originally posted by @haikalpribadi  on 2018-08-21 12:50_.

Why:
The following queries were reported to be slow:
- https://github.com/graknlabs/grakn/issues/4221
- https://github.com/graknlabs/grakn/issues/4222

How:
- Provide an instance count per type (ie, a `Map<Label, Integer>`). This instance count will be used by the query planner to start from a type which has the least amount of instance.
- Provide an implicit relationship count per type. (ie., `Map<ImplicitRelationshipType, Integer>`)
- The query planner should do greedy search with lookahead
Additionally, in the single node scenario, it will be easy. You'll just have to store a count which can be incremented when a new concept is inserted. However, in a cluster, insertion can happen across different nodes and the count needs to be propagated between one node to another.

This issue is needed-by #3937, needed-by #4324, needed-by #4221, needed-by #4222

**Comment by flyingsilverfin** [comment]
Grakn 2.0 uses statistics for query planning, closing
