### ISSUE TITLE
Document how the real time deduplication works in the dev wiki

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#4267]
_This issue was originally posted by @lolski  on 2018-08-31 12:41_.

**Comment by lolski** [comment]
Are we still planning on keeping the internal wiki? If not, I'll close this issue @haikalpribadi

**Comment by lolski** [comment]
Closing as documenting the attribute deduplicator internal architecture isn't our priorities in the next 6 months. Let me know if you think we should re-open this issue @haikalpribadi
