### ISSUE TITLE
Verify that changing grakn-engine.pid to grakn-core-server.pid is fine

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#4271]
_This issue was originally posted by @haikalpribadi  on 2018-09-01 17:03_.

**Comment by lolski** [comment]
It's been verified to work as of https://github.com/graknlabs/grakn/commit/72f664ecd4354197bf035ef74c0c277e6893bb05, proved by the fact that the test-end-to-end passed: https://circleci.com/gh/graknlabs/grakn/6355.

Closing the ticket.
