### ISSUE TITLE
Reduce bootup processes to just Grakn Server and Cassandra

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#4286]
_This issue was originally posted by @haikalpribadi  on 2018-09-01 19:17_.

Right now, we have: - `grakn-core` as a bootup script that starts: - `GraknBootup` java program (i.e. individual process) that starts up: - Cassandra through `StorageBootup` - Grakn Server through `GraknEngine` - (assume Redis is gone) The above is a bit too complicated. We can (and want to) make it such as the following: - `grakn-core` as a bootup script that starts: - `Server` java program that actually represents the Grakn "server", which during initialisation will start up: - Cassandra java program through `StorageBootup`

**Comment by lolski** [comment]
@haikalpribadi I think we no longer need to do this given that you've refactored the `bootup` script into `grakn.core.daemon`. Let's close this?
