### ISSUE TITLE
Improve fault tolerance and performance in Attribute deduplicator

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#4294]
_This issue was originally posted by @lolski  on 2018-09-03 18:13_.

Why:
The deduplicator works well on most scenarios but there are several outstanding issues:
- does not handle the following failure scenario: An attribute "John" has been stored into Cassandra, but Grakn crashes just before inserting the data to the queue. It may cause the deduplication to never be triggered.
- the producer-consumer pattern, which uses wait/notify, is considered hard to understand and needs to be made simpler
- the write-if-not-exists check is still enabled because the query planner wouldn't work when there are duplicates. the write-if-not-exists check is not a good guard, as it only works when an application is inserting sequentially, from a single thread
- if we are to remove the write-if-not-exists check though, deduplicator would always get triggered when new attributes are inserted. there must be something we can do to optimise it.
How:

This issue needs #4267, needs #4293, needs #4295

**Comment by marco-scoppetta** [comment]
Removed AttributeDeduplicator
