### ISSUE TITLE
Interpretation of an empty unifier inconsistent

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#4302]
_This issue was originally posted by @kasper-piskorski  on 2018-09-05 16:21_.

Seems sometimes we are interpreting it as a trivial unifier and sometimes as a non-existent unifier. Grakn Version:
Reproducible Steps:

**Comment by kasper-piskorski** [comment]
Fixed in https://github.com/graknlabs/grakn/commit/2febf209f14e0d69274ff494671b3f068175c0e7.
