### ISSUE TITLE
date comparison works only if the compared date exists

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#4312]
_This issue was originally posted by @sorsaffari  on 2018-09-07 19:58_.

Also with dates it is not possible to do direct comparison, i.e., this does not work: `match $x isa person has birth-date >= 1833-04-08; get;`, even though there is a person with birth-date equal to `1833-04-08` -> only with `==` the previous query works

**Comment by sorsaffari** [comment]
@haikalpribadi closing this issue as it's already fixed 🎉
