### ISSUE TITLE
Architecture: trim down dependencies

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#4321]
_This issue was originally posted by @haikalpribadi  on 2018-09-11 13:33_.

**Comment by lolski** [comment]
Do we still need this issue @haikalpribadi ? It's been 6 months since it is created and we should close it given that you've performed significant refactoring.

**Comment by haikalpribadi** [comment]
There's still more to do on this, @lolski. Mainly in the `@graknlabs_grakn_core//server` now.

**Comment by marco-scoppetta** [comment]
@haikalpribadi I think most of the work on this is done, Grakn 1.6.0 is going to be 130MB instead of 173MB

80% of our deps are because Analytics (Spark, Hadoop) and Cassandra
