### ISSUE TITLE
performing a query in descending order returns the results in ascending order

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#4349]
_This issue was originally posted by @lolski  on 2018-09-20 23:18_.

Query 
```
 match $c isa comment, has create-date $d; order by $d desc; get 
```
 Expected: list of dates in descending order Actual: list of dates in ascending order 
```
 {$d val 2018-08-13T17:07 isa create-date;} {$d val 2018-08-13T17:17 isa create-date;} {$d val 2018-08-13T17:54 isa create-date;} {$d val 2018-08-13T20:42 isa create-date;} {$d val 2018-08-13T21:24 isa create-date;} {$d val 2018-08-13T21:26 isa create-date;} {$d val 2018-08-13T22:57 isa create-date;} {$d val 2018-08-14T01:03 isa create-date;} 
```
 Dataset: Dropbox > Datasets > grakn-core-1.4.0-SNAPSHOT-with-github-data.zip

**Comment by haikalpribadi** [comment]
This should be fixed by PR #4910 now. @lolski can you help test it on the dataset you provided above? I've already tested it in the integration tests and it all works, so I'm closing this issue for now. (cc: @BFergerson)
