### ISSUE TITLE
BioGrakn | BLAST: define the schema in accordance with the response from BLAST

### ISSUE THREAD

**Issue by sorsaffari** [graknlabs/grakn#4363]
- [x] test the BLAST API for minimal response
- [ ] test the BLAST API for maximal response
- [ ] define the first draft of the schema
- [ ] finalise the schema

#### resources:
- https://unmc.edu/bsbc/docs/NCBI_blast.pdf

**Comment by haikalpribadi** [comment]
@sorsaffari (cc: @tomassabat @Irtazaraza) this issue should have been made in the [biograkn](https://github.com/graknlabs/biograkn). I'm closing this issue. Please move other issues like this to BioGrakn too.

**Comment by sorsaffari** [comment]
@haikalpribadi my bad. recreated this in [biograkn](https://github.com/graknlabs/biograkn)
