### ISSUE TITLE
client-python Makefile is not robust

### ISSUE THREAD

**Issue by haikalpribadi** [graknlabs/grakn#4390]
There are several issues that I encountered while trying to compile `client-python`, which makes it very difficult. It needs to be easy.

1. running `pip3 install pipenv` without `--user` causes permission issues
2. `pipenv install --dev` doesn't seem to install `grpcio` and `grpcio_tools`. I had to manually run `pip install grpcio` and `pip install grpcio_tools` to get `make protobuf` to work
3. calling `python` for the compilation is ambiguous and misleading. The system expects the `python` you run to be `python3` while users/OS expects `python` to be `python2.7`. Event after installing Python 3, we still can't call with with the `python` command. `/usr/bin/python` is of version 2.7 and it would scary to replace that with 3.7 as there is no official way to do it and may have lots of OS systems depending on it.
4. documentation on how to do the build is needed, including things like the above.

**Comment by vmax** [comment]
We don't have `Makefile` in [graknlabs/client-python](https://github.com/graknlabs/client-python) anymore, it's all in `bazel`
