### ISSUE TITLE
Client Python: file structure naming is unclear

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/grakn#4423]
To use the class `Concept` in Python it is necessary to import as follows:
```
from grakn.service.Session.Concept import Concept

is_a_concept = isInstance(my_concept, Concept.Concept)
```
From a user perspective this is confusing since there is a package called `Concept`, containing a file called `Concept`, containing a class called `Concept`.

I believe ideal best practice would be to use lower case names for packages, and that they should be named according to a summary of their content. I don't know whether this would conflict with our naming across our other drivers but something should be done to limit the confusion here if possible.

**Comment by flyingsilverfin** [comment]
needed by #4240

**Comment by flyingsilverfin** [comment]
Plan for resolution: rename Session -> session, Concept.py -> concept.py, Session.Concept -> Session.xxxx (TBD) so we don't have concept.concept.Concept, but rather from (say) API.concept import Concept

**Comment by flyingsilverfin** [comment]
Regaring rename folder structure, we have decided to postpone renaming of modules and packages to 1.6 for further discussion about making breaking changes.

**Comment by vmax** [comment]
@jmsfltchr @flyingsilverfin feel free to post this one to [`graknlabs/client-python`](https://github.com/graknlabs/client-python/) if it is still relevant
