### ISSUE TITLE
Client Python: attribute.data_type() doesn't return a string

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/grakn#4433]
The Client Python docs pledge that `my_attribute.data_type()` should return a string, but it doesn't. Presently it returns an object with an attribute `name` that holds the capitalised name of the data type.

At present I do the following to get the result I expected to see:
```
my_attribute.data_type().name.lower()
```

**Comment by flyingsilverfin** [comment]
resolution: Docs are wrong. Returns an enum that is a grakn.DataType, same as during creation.

needed by #4240
