### ISSUE TITLE
Improvement suggestion: Use actual screenshots on the academy pages

### ISSUE THREAD

**Issue by kristall** [graknlabs/grakn#4450]
The screenshots in the academy do not match my local version: In the upper left is a box that does contain "tasks" and "config" on the website screenshots but not in my local instance (li), but the li contains "commands" which is not the screenshots. 

This might be confusing to new users, so it'd be better if the screenshots reflect the actual version.

**Comment by sorsaffari** [comment]
In the new documentation, all screenshots are kept in sync with the latest changes.
