### ISSUE TITLE
Improvement suggestion: Let the red warning box in the dashboard contain an error message

### ISSUE THREAD

**Issue by kristall** [graknlabs/grakn#4451]
Title says it all I think.

**Comment by kristall** [comment]
It does not say it all: So I just saw that the red box already contains an error message.

But it does not show one for 
`match $x isa company has name "Grakn"; delete $x;` 
from https://dev.grakn.ai/academy/insert-delete-queries.html#deleting-things
which would be nice.

**Comment by kristall** [comment]
I will happily test the workbase (probably even very soon), but since I was just following the academy to start with grakn I did not check the workbase out yet since it is not mentioned on https://dev.grakn.ai/academy/setup.html

**Comment by sorsaffari** [comment]
@kristall looking forward to your feedback!

I will close this issue as I have verified that this has been resolved in the workbase. 

both the academy and documentation will go though a rewrite in the coming weeks. bug/improvement issues such as this and some other ones you've created, will help a lot in speeding up this process. thank you for your contribution 🙂
