### ISSUE TITLE
is there a type like php trait as a plus to parent/sub types?

### ISSUE THREAD

**Issue by scil** [graknlabs/grakn#4452]
[Traits are a mechanism for code reuse in single inheritance languages such as PHP. A Trait is intended to reduce some limitations of single inheritance](http://php.net/manual/pl/language.oop5.traits.php)

I wonder is there something like php traits in grankn?

**Comment by marco-scoppetta** [comment]
@scil we are not familiar with PHP, but it looks like Traits allow you to use composition together with inheritance. 
They just group a list of functionality that you can be re-used in different classes, is that right? 
We don't provide directly composition functionalities, but it looks like this might a modelling issue you're having, can you describe what are you trying to model?

**Comment by scil** [comment]
Thank you.

`sub` in grakn is like `extends` in php OOP.  I would like to know,  dispite the parent/son model, is there any model in grakn allows some attributes shared by some types?

Like trait in php,  or,  multiple inheritance in Python ?

**Comment by marco-scoppetta** [comment]
In the Grakn world there is no multiple inheritance, you can though share `attributes` and `roles` between entities.

You can have for example an entity `man` that is a `sub` of `human` and then you can have and entity `pet` which is not related to `man` or `human`.

But both `man` and `pet` can have an attribute `name` and they can both play the role `friend` in an hypothetical `friendship` relationship.

We have a (Grakn Academy)[https://dev.grakn.ai/academy/] that introduces the user to the main principles of Grakn, maybe that can give you a better understanding of what's achievable.

**Comment by scil** [comment]
Thank you.

If both `man` and `pet` have attribute `name` and `name2`. 

Can I make a `trait` containing `name` and `name2` and let `man`  and `pet` use the `trait`?

**Comment by marco-scoppetta** [comment]
So `man` and `pet` would have `name` as an attribute, you can imagine it as a field in your class. I don't see why you would need `name` and `name2`. So then you could probably have a `trait` with `getName` and `setName` and make the 2 classes use it.
I would still recommend reading the Academy first.

**Comment by marco-scoppetta** [comment]
Closing this, feel free to reopen if you need further clarification
