### ISSUE TITLE
Build a scalable behaviour-driven test framework

### ISSUE THREAD

**Issue by haikalpribadi** [graknlabs/grakn#4458]
## Goal

- Write tests once, and have it run everywhere (all repos), anywhere (all environments), and for every backend (Core and KGMS).
- Correctness: all products behave correctly in the same way, end-to-end (from core, to kgms, to clients, to consoles)
- Completeness: all products guarantee the same coverage
- Independent: the test language is independent to the code implementation, which means we can refactor code (e.g. grakn.core.api) easily by just changing the test-parser (e.g. located in grakn.core.test.behaviour), without having to change all the test code.
- Time: the effort of managing tests separately on all repos grows exponentially. The effort of doing multi-repo multi-language BDD is linear.
- Test reusability and automation: different combinations of tests can be run repeatedly in different repos. At the very least: 
    * First: in the dedicated repo that needs to be tested e.g. client-java test against grakn-core, everything client-java changes
    * Second: in the aggregated repo graknlabs/test where everything is tested again against both grakn-core and grakn-kgms for every change in any repo
- Extensibility: effort to add new scenarios and test cases should be easy, and without messing up the architecture.
- Parallelisability: test modules should depend on each other as little as possible. This will allow Bazel to execute all the tests in parallel as much as possible.

## Solution

Behaviour-driven tests with Cucumber as the framework and Gherkin as th language.

Validated requirements for the tools:
- [x] Cucumber framework for java (for grakn-core, grakn-kgms, client-java, console): cucumber-jvm
- [x] Cucumber framework for nodejs (for client-nodejs): cucumber-js
- [x] Cucumber framework for python (for client-python): behave
- [x] Cucumber framework is configurable to run feature sets against both grakn-core and grakn-kgms without repeating code
- [x] Cucumber framework provides a way to guarantee cleaning up the state of the database
- [x] Cucumber allows us to modularise feature sets into groups/packages, and we can pick and choose what to implement/run
- [x] Gherkin parser can be extended with custom parameter types
- [x] Gherkin provides data structure to contain Graql statements (for define, insert, match queries)
- [x] Gherkin provides data structure to contain Graql answers (for ConceptMap, ConceptSet, ConceptList, AnswerGroup) and can be extended with custom ones if needed

**Comment by flyingsilverfin** [comment]
Being defined in graknlabs/verification repository and implemented in grakn core using https://github.com/graknlabs/grakn/pull/5692

**Comment by flyingsilverfin** [comment]
@haikalpribadi  i think we can close this?

**Comment by flyingsilverfin** [comment]
(it's sitll on our 2.0 TODO board)

**Comment by haikalpribadi** [comment]
Yes, we can close this now. 👍

**Comment by haikalpribadi** [comment]
It was closed 20 days ago, actually. not sure if you're referring to something else

**Comment by flyingsilverfin** [comment]
i was referring to the : Projects
Grakn 2.0
" To do "

labeling that keeps it in our project TODO board even if it's closed (seems like a automation bug by github?) ill remove it
