### ISSUE TITLE
Improvement suggestion: 'return' should save a name for a query not just the button (workbase and dashboard)

### ISSUE THREAD

**Issue by kristall** [graknlabs/grakn#4462]
When you chose a "save name" for a query, then "return/enter" (on the keyboard) should save the query and not just do nothing (like in the workbase) or even execute the query (like in the dashboard) but actually save the name. Now you must hit the save button which is kinda counter intuitive.

**Comment by marco-scoppetta** [comment]
already something we are working on,  thank you!
