### ISSUE TITLE
Unclear docs about aggregation queries

### ISSUE THREAD

**Issue by kristall** [graknlabs/grakn#4464]
On https://dev.grakn.ai/academy/other-queries.html is the question
`How would you find the standard deviation of the risk values of all bonds?`
but https://dev.grakn.ai//docs/querying-data/aggregate-queries does not contain the word `deviation`.
As a non-native speaker I am not sure what a standard deviation is or how to calculate it. After asking google my guess it means the median, but if so a clarifying sentence about that would be great.

**Comment by sorsaffari** [comment]
@kristall Thank you for reporting this. It seems to be that standard deviation used to be among the aggregate functions and it's not anymore. I believe as we move towards supporting arithmetics, calculating standard variation as a part of the `match` queries will become possible again.
