### ISSUE TITLE
Incomplete and wrong sentence in the compute queries part of the academy

### ISSUE THREAD

**Issue by kristall** [graknlabs/grakn#4465]
On https://dev.grakn.ai/academy/other-queries.html#compute-queries is the sentence 
``` 
To use Analytics, you run compute queries, that have a slightly different syntax: 
a compute query has the form `compute <method> <conditions>?;` where 
`<name>`  the type of analytics functions you want to compute, `<conditions>` 
are the set of conditions you would like to provide to control the computation.
```
Wrong seems to be `<name>` since <name> was not mentioned in the form definition and I am missing an `is` after it. And the `,` after `want to compute` should imho be an `and`. So the whole would be:

``` 
To use Analytics, you run compute queries, that have a slightly different syntax: 
a compute query has the form `compute <method> <conditions>?;` where 
`<method>` is the type of analytics functions you want to compute and `<conditions>`
are the set of conditions you would like to provide to control the computation.
```

**Comment by sorsaffari** [comment]
@kristall you're right and this needs to be corrected. Thanks for reporting this.

In the meanwhile, please refer to the documentation page on [compute queries](https://dev.grakn.ai/docs/distributed-analytics/compute-queries)
