### ISSUE TITLE
Improvement suggestion: Visual feedback of running query

### ISSUE THREAD

**Issue by kristall** [graknlabs/grakn#4466]
Since for example a compute query may take some time between the start of the execution and the showing of the result (in the dashboard console) it would be very cool to have some visual feedback that the query is running and I need to be patient, before hitting Enter again, so that I don't keep restarting the query because I feel that nothing is happening ...

**Comment by marco-scoppetta** [comment]
Yeah that's going to be fixed in Workbase when we add the Console capabilities in there
