### ISSUE TITLE
Academy > Grakn Schemas > Module Review: the screenshot visualising the 'academy' knowledge graph is outdated

### ISSUE THREAD

**Issue by kristall** [graknlabs/grakn#4480]
On https://dev.grakn.ai/academy/schema-review.html is https://dev.grakn.ai/images/academy/3-schema/academy-schema.png in which it would imho be better if thing would not share the color with entity and the subentities. Make it yellow like the sun, since the sun is the root ...

**Comment by sorsaffari** [comment]
@kristall in the latest version of the dashboard, `thing`, `entity`, `attribute` and `relationship` are not displayed when visualising the schema. what you pointed out is, in fact, an outdated screenshot

**Comment by marco-scoppetta** [comment]
Closing as we don't support Academy anymore.
