### ISSUE TITLE
Query not fetching correct data and time datatype error

### ISSUE THREAD

**Issue by pvsatish** [graknlabs/grakn#4482]
Here is the movie schema:

define

play sub relationship,
	relates screendat,
	relates screens,
	has showtime,
	has rundate;

movie sub entity,
	plays screendat,
	has title,
	has genre;

theater sub entity,
	plays screens,
	has name;

  title sub attribute datatype string;
  language sub attribute datatype string;
  duration sub attribute datatype long;
  genre sub attribute datatype string;
  rundate sub attribute datatype date;
  location sub attribute datatype string;
  showtime sub attribute datatype long;
  name sub attribute datatype string;
  

insert $p isa movie has title "Peppermint" has genre "action";
insert $ab isa movie has title "AngryBirds" has genre "children-movie";
insert $am isa movie  has title "American Animals" has genre "action";
insert $ad isa movie  has title "Adrift" has genre "drama";
insert $s isa movie has title "Succession" has genre "action";

insert $pv isa theater has name "PVRCinemas" has location "koramangala";
insert $g isa theater has name "Gopalancinemas" has location "madiwala";
insert $i isa theater has name "Inoxcinemas" has location "sarjapur";

match
$p isa  movie has title "Peppermint";
$ab isa movie has title "AngryBirds";
$ad isa movie has title "Adrift";
$s isa  movie has title "Succession";
$am isa  movie has title "American Animals";
$pv isa theater has name "PVRCinemas";
$g isa theater has name "Gopalancinemas";
$i isa theater has name "Inoxcinemas";

insert $play(screendat: $p, screens: $pv) isa play; $play has rundate 2018-09-26; #has showtime "12:30pm" has showtime "01:30pm" has showtime "07:00pm"; 
insert $play(screendat: $ab, screens: $g) isa play; $play has rundate 2018-09-27; #has showtime "11:00am" has showtime "02:30pm" has showtime "08:00pm";
insert $play(screendat: $ad, screens: $pv) isa play; $play has rundate 2018-09-27; #has showtime "10:30am" has showtime "12:00pm" has showtime "10:00pm" ;
insert $play(screendat: $s, screens: $i) isa play; $play has rundate 2018-09-26; #has showtime "10:20am" has showtime "01:35pm", has showtime "07:16pm" ;
insert $play(screendat: $am, screens: $i) isa play; $play has rundate 2018-09-25; #has showtime "11:20am"  has showtime "02:30pm" has showtime "06:10pm" ;

**Error 1:**

Also, what is the datatype for showtime attribute?  I tried long, date etc. but I get the error: INVALID_ARGUMENT: GraqlQueryException-$ab doesn't have an 'isa', a 'sub' or an 'id'. Please check server logs for the stack trace.
{}

**Error2:** 

I commented Showtime and ran the below query.

**My query:**

my query:match
 $x isa movie has title $title;
 $y isa theater has name "PVRCinemas";
 (screendat: $x, screens: $y) isa play;
get $title;

**Result:**

Based on the movie data that I had inserted, the query could fetch only title (Peppermint'). But the result should be two movie titles- 'Peppermint' and 'Adrift'.  

There is some issue in the schema, which I am unable to figure out.

We should be able to get the answers for the following two questions:

1. What are the movies screened at PVRCinemas? Ans: Peppermint and Adrift.
2. What is the showtime for Peppermint in PVRCinemas? Ans: 12:30pm, 01:30pm and 07:00pm 

Please help resolving these two issues. 

Thanks
pvs

**Comment by kasper-piskorski** [comment]
Hello!

So the problems with this schema are:
- `theater` cannot have attribute `location`
- the scope of your inserts is not the one you think.

Let's have a look at the crucial match-insert part.
```
match
$p isa movie has title "Peppermint";
$ab isa movie has title "AngryBirds";
$ad isa movie has title "Adrift";
$s isa movie has title "Succession";
$am isa movie has title "American Animals";
$pv isa theater has name "PVRCinemas";
$g isa theater has name "Gopalancinemas";
$i isa theater has name "Inoxcinemas";

**insert $play(screendat: $p, screens: $pv) isa play; $play has rundate 2018-09-26; #has showtime "12:30pm" has showtime "01:30pm" has showtime "07:00pm";**
insert $play(screendat: $ab, screens: $g) isa play; $play has rundate 2018-09-27; #has showtime "11:00am" has showtime "02:30pm" has showtime "08:00pm";
insert $play(screendat: $ad, screens: $pv) isa play; $play has rundate 2018-09-27; #has showtime "10:30am" has showtime "12:00pm" has showtime "10:00pm" ;
insert $play(screendat: $s, screens: $i) isa play; $play has rundate 2018-09-26; #has showtime "10:20am" has showtime "01:35pm", has showtime "07:16pm" ;
insert $play(screendat: $am, screens: $i) isa play; $play has rundate 2018-09-25; #has showtime "11:20am" has showtime "02:30pm" has showtime "06:10pm" ;
```
Variables are scoped to the query they are defined in. As a result, the variable mappings obtained in the match part are scoped to the subsequent insert statement hence they won't be available in the remaining inserts and we get the error.

One way of correcting this is to have:
```
match
$p isa movie has title "Peppermint";
$ab isa movie has title "AngryBirds";
$ad isa movie has title "Adrift";
$s isa movie has title "Succession";
$am isa movie has title "American Animals";
$pv isa theater has name "PVRCinemas";
$g isa theater has name "Gopalancinemas";
$i isa theater has name "Inoxcinemas";

insert
(screendat: $p, screens: $pv) isa play, has rundate 2018-09-26; #has showtime "12:30pm" has showtime "01:30pm" has showtime "07:00pm";
(screendat: $ab, screens: $g) isa play, has rundate 2018-09-27; #has showtime "11:00am" has showtime "02:30pm" has showtime "08:00pm";
(screendat: $ad, screens: $pv) isa play, has rundate 2018-09-27; #has showtime "10:30am" has showtime "12:00pm" has showtime "10:00pm" ;
(screendat: $s, screens: $i) isa play, has rundate 2018-09-26; #has showtime "10:20am" has showtime "01:35pm", has showtime "07:16pm" ;
(screendat: $am, screens: $i) isa play, has rundate 2018-09-25; #has sh
```
Please also note that I omitted the `$play` variable which would lead to conflicts among relationships.

Alternatively you can omit the match part and put all yours inserts into one:

```
insert
$p isa movie has title "Peppermint" has genre "action";
$ab isa movie has title "AngryBirds" has genre "children-movie";
$am isa movie has title "American Animals" has genre "action";
$ad isa movie has title "Adrift" has genre "drama";
$s isa movie has title "Succession" has genre "action";
$pv isa theater has name "PVRCinemas" has location "koramangala";
$g isa theater has name "Gopalancinemas" has location "madiwala";
$i isa theater has name "Inoxcinemas" has location "sarjapur";

(screendat: $p, screens: $pv) isa play, has rundate 2018-09-26; 
(screendat: $ab, screens: $g) isa play, has rundate 2018-09-27; 
(screendat: $ad, screens: $pv) isa play, has rundate 2018-09-27; 
(screendat: $s, screens: $i) isa play, has rundate 2018-09-26; 
(screendat: $am, screens: $i) isa play, has rundate 2018-09-25; 
```

Hope that helps.

**Comment by pvsatish** [comment]
Hi Kasper, thanks so much.  I executed the modified code and it works perfect for my first question. Regarding my second question about showtime, I am still getting error: 

> INVALID_ARGUMENT: GraqlQueryException-cannot insert property `datatype java.lang.String` on existing concept `Base Type [ATTRIBUTE_TYPE] - Id [V172112]  - Label [showtime] - Abstract [false] `. Please check server logs for the stack trace.


Modified code:

define

play sub relationship
	relates screendat
	relates screens
	has showtime
	has rundate;


movie sub entity
	plays screendat
	has title
	has genre;


theater sub entity
	plays screens
	has name;


  title sub attribute datatype string;
  language sub attribute datatype string;
  duration sub attribute datatype long;
  genre sub attribute datatype string;
  rundate sub attribute datatype date;
  location sub attribute datatype string;
  showtime sub attribute datatype string;
  name sub attribute datatype string;

insert
$p isa movie has title "Peppermint" has genre "action";
$ab isa movie has title "AngryBirds" has genre "children-movie";
$am isa movie has title "American Animals" has genre "action";
$ad isa movie has title "Adrift" has genre "drama";
$s isa movie has title "Succession" has genre "action";
$pv isa theater has name "PVRCinemas" has location "koramangala";
$g isa theater has name "Gopalancinemas" has location "madiwala";
$i isa theater has name "Inoxcinemas" has location "sarjapur";


(screendat: $p, screens: $pv) isa play, has rundate 2018-09-26, has showtime "3:15pm", has showtime "5:15pm";
(screendat: $ab, screens: $g) isa play, has rundate 2018-09-27, has showtime "10:15am";
(screendat: $ad, screens: $pv) isa play, has rundate 2018-09-27, has showtime "12.30pm"; 
(screendat: $s, screens: $i) isa play, has rundate 2018-09-26, has showtime "3:45pm", has showtime "4:15pm", has showtime "7:30pm";
(screendat: $am, screens: $i) isa play, has rundate 2018-09-25; has showtime "3:50pm", has showtime "8:20pm", has showtime "10:30pm";

**Comment by kasper-piskorski** [comment]
You have an excess semicolon in the last line :)

Your relation part of the insert should read:
```
(screendat: $p, screens: $pv) isa play, has rundate 2018-09-26, has showtime "3:15pm", has showtime "5:15pm";
(screendat: $ab, screens: $g) isa play, has rundate 2018-09-27, has showtime "10:15am";
(screendat: $ad, screens: $pv) isa play, has rundate 2018-09-27, has showtime "12.30pm";
(screendat: $s, screens: $i) isa play, has rundate 2018-09-26, has showtime "3:45pm", has showtime "4:15pm", has showtime "7:30pm";
(screendat: $am, screens: $i) isa play, has rundate 2018-09-25, has showtime "3:50pm", has showtime "8:20pm", has showtime "10:30pm";
```

**Comment by pvsatish** [comment]
Hi Kasper, thanks for responding.

However, I am getting the same error -- INVALID_ARGUMENT: GraqlQueryException-cannot insert property `datatype java.lang.String` on existing concept `Base Type [ATTRIBUTE_TYPE] - Id [V172112]  - Label [showtime] - Abstract [false] `. Please check server logs for the stack trace.

**Comment by pvsatish** [comment]
I am getting the error when executing the .gql file in console.  Please refer the attached file.  I am using Grakn version 1.4.2.

![grakn issue](https://user-images.githubusercontent.com/20812778/47341316-54d25180-d6be-11e8-94dc-b92bfe4414fc.png)

**Comment by kasper-piskorski** [comment]
Could you paste any stack traces from `logs/grakn.log?`

**Comment by pvsatish** [comment]
> I get the bellow error when I used showtime datatype as Date

ai.grakn.exception.GraqlQueryException: cannot insert property `datatype java.time.LocalDateTime` on existing concept `Base Type [ATTRIBUTE_TYPE] - Id [V172112]  - Label [showtime] - Abstract [false] `
	at ai.grakn.exception.GraqlQueryException.create(GraqlQueryException.java:89)
	at ai.grakn.exception.GraqlQueryException.insertPropertyOnExistingConcept(GraqlQueryException.java:191)
	at ai.grakn.graql.internal.query.executor.ConceptBuilder.validateParam(ConceptBuilder.java:402)
	at ai.grakn.graql.internal.query.executor.ConceptBuilder.validate(ConceptBuilder.java:383)
	at ai.grakn.graql.internal.query.executor.ConceptBuilder.tryGetConcept(ConceptBuilder.java:209)
	at ai.grakn.graql.internal.query.executor.ConceptBuilder.build(ConceptBuilder.java:179)
	at ai.grakn.graql.internal.query.executor.QueryOperationExecutor.buildConcept(QueryOperationExecutor.java:270)
	at ai.grakn.graql.internal.query.executor.QueryOperationExecutor.get(QueryOperationExecutor.java:401)
	at ai.grakn.graql.internal.pattern.property.HasAttributeTypeProperty.lambda$define$1(HasAttributeTypeProperty.java:148)
	at ai.grakn.graql.internal.pattern.property.PropertyExecutor.execute(PropertyExecutor.java:76)
	at ai.grakn.graql.internal.query.executor.QueryOperationExecutor.insertAll(QueryOperationExecutor.java:253)
	at ai.grakn.graql.internal.query.executor.QueryOperationExecutor.defineAll(QueryOperationExecutor.java:114)
	at ai.grakn.graql.internal.query.executor.QueryExecutorImpl.run(QueryExecutorImpl.java:120)
	at ai.grakn.graql.internal.query.DefineQueryImpl.stream(DefineQueryImpl.java:51)
	at ai.grakn.engine.rpc.SessionService$TransactionListener.query(SessionService.java:237)
	at ai.grakn.engine.rpc.SessionService$TransactionListener.handleRequest(SessionService.java:142)
	at ai.grakn.engine.rpc.SessionService$TransactionListener.lambda$onNext$0(SessionService.java:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-10-23 00:09:12,691 [grpc-default-executor-3] ERROR a.g.e.r.SessionService$TransactionListener - Runtime Exception in RPC TransactionListener: 

> I get the bellow error when I used showtime datatype as String

ai.grakn.exception.GraqlQueryException: cannot insert property `datatype java.lang.String` on existing concept `Base Type [ATTRIBUTE_TYPE] - Id [V172112]  - Label [showtime] - Abstract [false] `
	at ai.grakn.exception.GraqlQueryException.create(GraqlQueryException.java:89)
	at ai.grakn.exception.GraqlQueryException.insertPropertyOnExistingConcept(GraqlQueryException.java:191)
	at ai.grakn.graql.internal.query.executor.ConceptBuilder.validateParam(ConceptBuilder.java:402)
	at ai.grakn.graql.internal.query.executor.ConceptBuilder.validate(ConceptBuilder.java:383)
	at ai.grakn.graql.internal.query.executor.ConceptBuilder.tryGetConcept(ConceptBuilder.java:209)
	at ai.grakn.graql.internal.query.executor.ConceptBuilder.build(ConceptBuilder.java:179)
	at ai.grakn.graql.internal.query.executor.QueryOperationExecutor.buildConcept(QueryOperationExecutor.java:270)
	at ai.grakn.graql.internal.query.executor.QueryOperationExecutor.get(QueryOperationExecutor.java:401)
	at ai.grakn.graql.internal.pattern.property.HasAttributeTypeProperty.lambda$define$1(HasAttributeTypeProperty.java:148)
	at ai.grakn.graql.internal.pattern.property.PropertyExecutor.execute(PropertyExecutor.java:76)
	at ai.grakn.graql.internal.query.executor.QueryOperationExecutor.insertAll(QueryOperationExecutor.java:253)
	at ai.grakn.graql.internal.query.executor.QueryOperationExecutor.defineAll(QueryOperationExecutor.java:114)
	at ai.grakn.graql.internal.query.executor.QueryExecutorImpl.run(QueryExecutorImpl.java:120)
	at ai.grakn.graql.internal.query.DefineQueryImpl.stream(DefineQueryImpl.java:51)
	at ai.grakn.engine.rpc.SessionService$TransactionListener.query(SessionService.java:237)
	at ai.grakn.engine.rpc.SessionService$TransactionListener.handleRequest(SessionService.java:142)
	at ai.grakn.engine.rpc.SessionService$TransactionListener.lambda$onNext$0(SessionService.java:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-10-23 01:44:58,450 [grpc-default-executor-4] ERROR a.g.e.r.SessionService$TransactionListener - Runtime Exception in RPC TransactionListener:

**Comment by kasper-piskorski** [comment]
Can you load the following file into a fresh keyspace:

```
define

play sub relationship
relates screendat
relates screens
has showtime
has rundate;

movie sub entity
plays screendat
has title
has genre;

theater sub entity
plays screens
has name
has location;

title sub attribute datatype string;
language sub attribute datatype string;
duration sub attribute datatype long;
genre sub attribute datatype string;
rundate sub attribute datatype date;
location sub attribute datatype string;
showtime sub attribute datatype string;
name sub attribute datatype string;

insert
$p isa movie has title "Peppermint" has genre "action";
$ab isa movie has title "AngryBirds" has genre "children-movie";
$am isa movie has title "American Animals" has genre "action";
$ad isa movie has title "Adrift" has genre "drama";
$s isa movie has title "Succession" has genre "action";
$pv isa theater has name "PVRCinemas" has location "koramangala";
$g isa theater has name "Gopalancinemas" has location "madiwala";
$i isa theater has name "Inoxcinemas" has location "sarjapur";

(screendat: $p, screens: $pv) isa play, has rundate 2018-09-26, has showtime "3:15pm", has showtime "5:15pm";
(screendat: $ab, screens: $g) isa play, has rundate 2018-09-27, has showtime "10:15am";
(screendat: $ad, screens: $pv) isa play, has rundate 2018-09-27, has showtime "12.30pm";
(screendat: $s, screens: $i) isa play, has rundate 2018-09-26, has showtime "3:45pm", has showtime "4:15pm", has showtime "7:30pm";
(screendat: $am, screens: $i) isa play, has rundate 2018-09-25, has showtime "3:50pm", has showtime "8:20pm", has showtime "10:30pm";
```
And then try to query it. Let us know how it goes.

**Comment by pvsatish** [comment]
Perfect!!

I could fetch the correct response for the query.  Thanks so much for you prompt response.  I will convey this to Tomas Sabat.

match
$x isa movie has title 'Peppermint';
$y isa theater has name 'PVRCinemas';
$play (screendat: $x, screens: $y) isa play;
$play has showtime $sht; get $sht;

response:
{$sht val "5:15pm isa showtime"}
{$sht val "3:15pm isa showtime"}

**Comment by kasper-piskorski** [comment]
Good to hear :) I'm closing this issue then.
