### ISSUE TITLE
Academy > Loading Data > Loading File: Typos

### ISSUE THREAD

**Issue by kristall** [graknlabs/grakn#4484]
'The -f option just **stands or “file”**.' => 'stands for "file".'

'The schema file **for to** be loaded can be found **in the VM** in the directory academy/short-training/schema.gql.' =?> unclear what is really meant, imho.

**Comment by vmax** [comment]
Link provided is 404 currently, therefore I conclude that it's no longer relevant (at least, in this definition). Feel free to post another one to [graknlabs/docs](https://github.com/graknlabs/docs) if I'm mistaken.
