### ISSUE TITLE
"All Types" button in the dashboard does not show the "sub" relation

### ISSUE THREAD

**Issue by kristall** [graknlabs/grakn#4485]
On https://dev.grakn.ai/academy/loading-files.html it says:

"o check if the schema load was successful, open the Graph Visualiser in the correct keyspace and click on the All Types button. It should look like the following:" then showing:

https://dev.grakn.ai/images/academy/3-schema/academy-schema.png

but I am unable to reproduce the pictured schema, since the sub relation is not shown.

(same problem on https://dev.grakn.ai/academy/schema-review.html where I am not able to reproduce the same png).

**Comment by Irtazaraza** [comment]
Dashboard is being deprecated. Workbase 1.5 will have a schema page to visualise your schema. closing this issue.
