### ISSUE TITLE
Grakn.ai navbar broken in Edge and tabs not showing well in Firefox

### ISSUE THREAD

**Issue by calebhskim** [graknlabs/grakn#4486]
Not sure if this is a known issue but when visiting https://grakn.ai/ in Edge the navbar does not render properly. In Firefox, the tab carets render at the top of the navbar. I compared against how the site renders in Chrome.

I am using the following versions of Edge and Firefox:
firefox 62.0.3 (64-bit)
edge 42.17134.1.0

Edge:
![edge](https://user-images.githubusercontent.com/8925071/47116675-316b5a80-d217-11e8-976e-aab71b380de2.PNG)
Firefox:
![firefox](https://user-images.githubusercontent.com/8925071/47116677-33cdb480-d217-11e8-9b93-d8781f6d8b13.PNG)

In Edge it seems like the issue is because `stretch` is not a supported value for `width` in Edge. Adding `width: 110vw;` to the navbar (`<div class="nav" data-reactid="2">`) seems to fix the issue.

![edge-width](https://user-images.githubusercontent.com/8925071/47117246-b440e500-d218-11e8-9784-36a63c2257cc.PNG)

In both Firefox and Edge the carets in the navbar render at the top of the navbar. Removing `vertical-align: top` from `.nav__link__dropdown .fa` seems to fix the issue. I tested it in Chrome and it does not affect the navbar.

![firefox-caret](https://user-images.githubusercontent.com/8925071/47117241-b145f480-d218-11e8-8f1d-d8ac72bf9cc0.PNG)

**Comment by marco-scoppetta** [comment]
@calebhskim thank you for reporting the issue. It is now been fixed.
