### ISSUE TITLE
Embed Janus properties in 'server/resources' into the classes that use them

### ISSUE THREAD

**Issue by lolski** [graknlabs/grakn#4509]
The following files, ie., `default-configs.properties`, `indices-composite.properties`, `indices-edges.properties`, are tightly coupled with the class which uses them.

Let's merge them with the classes that use them to make it simpler.

**Comment by vmax** [comment]
@haikalpribadi @lolski can I pick this one?

**Comment by lolski** [comment]
@vmax I think @haikalpribadi is already working on this one. Is that correct, Haikal?

**Comment by vmax** [comment]
Grakn no longer makes use of JanusGraph, so there are no properties to embed anymore.
