### ISSUE TITLE
split client-java distribution for benchmarking vs public release

### ISSUE THREAD

**Issue by flyingsilverfin** [graknlabs/grakn#4511]
* Don't want to pull in Brave and Zipkin into `client-java`'s public release distribution (want a small, light client-java distribution)
* alternative 2nd distribution that creates client-java for benchmarking
* Will need to create abstraction allowing client-java public release distirbution to compile without depending on benchmarking & Brave/Zipkin

**Comment by flyingsilverfin** [comment]
Plan: Create an extended `benchmark.Grakn` that enables instrumentation and build a separate a Bazel distribution jar/maven deploy which exclues `benchmark.*` for normal usage and includes it for the client-java-benchmark version.

**Comment by haikalpribadi** [comment]
@flyingsilverfin I just realised you don't even need to extend `GraknClient` to add tracing for benchmarking. Given that `GraknClient` has a `.overrideChannel(ManagedChannel)` method (which was previously provided as an overloaded constructor `GraknClient(ManagedChannel)`, you can just override the `ManagedChannel` from your benchmark application, with one that you constructed to have tracing with Zipkin. The code would look like something like this:

```
GraknClient client = new GraknClient(address);
        SimpleURI parsedURI = new SimpleURI(address);
        ManagedChannel channel = ManagedChannelBuilder.forAddress(parsedURI.getHost(), parsedURI.getPort())
                .intercept(new ClientTracingInstrumentationInterceptor("client-java-instrumentation"))
                .usePlaintext(true).build();
        client.overrideChannel(channel);
```

Right? I'll remove benchmarking tracing in `GraknClient` for now.

**Comment by flyingsilverfin** [comment]
The approach of overriding the client's `Channel` has been shown to work and moves the responsibility of instrumenting the client to packages outside the client
