### ISSUE TITLE
Enable importing client-java using Bazel

### ISSUE THREAD

**Issue by haikalpribadi** [graknlabs/grakn#4515]
In addition to importing `client-java` using Maven, users need to be able to import `client-java` using Bazel. This issue should only be worked on after we complete #4513.

**Comment by lolski** [comment]
We have this already, right @haikalpribadi ?

**Comment by haikalpribadi** [comment]
yeah, in a way, we do. It's not as simple as it could be, but it comes down to making the "dependencies macro" that we've already planned to do separately to this issue. @lolski

**Comment by lolski** [comment]
ok, closing this issue
