### ISSUE TITLE
Academy > Loading Data > Data migration - CSV: Typo

### ISSUE THREAD

**Issue by caufieldjh** [graknlabs/grakn#4523]
The "Migration" heading in the Academy page on Loading Data > Data migration - CSV lists the following example for loading a CSV:
`graql migration csv -k KEYSPACE -i INPUT_FILE -t TEMPLATE_FILE`
but the correct command is `migrate` so the example should presumably read
`graql migrate csv -k KEYSPACE -i INPUT_FILE -t TEMPLATE_FILE`

**Comment by sorsaffari** [comment]
@caufieldjh Thanks for reporting this :)
the `migrate` command is already deprecated and will be removed in the next release (1.5) along with its documentation.

For your future migration needs, please follow the [migration examples](http://dev.grakn.ai/docs/examples/migrating-csv-json-xml).
