### ISSUE TITLE
Graql: Variable roles not working for implicit attribute relationships

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/grakn#4548]
Variable roles do not appear to be working. The schema to reproduce is attached. Try the following queries:

Get an id for an attribute's implicit relationship:
```
match $relationship isa @has-job-title; get;
```

Results:

```
{$relationship id Eglx-j3c-fth-siw ("@has-job-title-value": id V36968, "@has-job-title-owner": id V24744) isa "@has-job-title";}
{$relationship id Eqvh-voo-fth-siw ("@has-job-title-value": id V36968, "@has-job-title-owner": id V41064) isa "@has-job-title";}
```

Use that id for the problematic query:
```
match $relationship id Eqvh-voo-fth-siw; $relationship($role: $x) isa @has-job-title; get $x, $role;
```

Receive an error:

```
INVALID_ARGUMENT: GraqlQueryException-the concept [role] could not be found in results. Please check server logs for the stack trace.
```

[schema.txt](https://codetreeusercontent.s3.amazonaws.com/uploads/14a9395b-70a6-457d-9943-c2bc167321bd/schema.txt)

*Update:*
No longer able to reproduce the `INVALID_ARGUMENT` error, however we have found consistently that querying while omitting the `isa @has-job-title` works, but leaving it in does not. To be clear, the following works:
```
match $relationship id Eqvh-voo-fth-siw; $relationship($role: $x); get $x, $role;
```

But this does not:
```
match $relationship id Eqvh-voo-fth-siw; $relationship($role: $x) isa @has-job-title; get $x, $role;
```

**Comment by alexjpwalker** [comment]
Implicit relations are gone now in 1.8.
