### ISSUE TITLE
Graql: Retrieving an implicit relationship by id along with any other concept by id returns nothing

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/grakn#4557]
Having loaded the attached Graql, make this query to get an id for an instance of an implicit relationship:
```
match $x isa @has-attribute; get;
```
Get an id for any other `thing` in the database:

```
match $x isa person; get;
```

Querying for both of those ids together returns no results:
```
match $x id Eqvh-voo-fth-siw; $y id V24664; get;
```

[schema.txt](https://codetreeusercontent.s3.amazonaws.com/uploads/32b363d6-a5ed-48db-a8fa-9f9c267f1e71/schema.txt)

**Comment by flyingsilverfin** [comment]
This has been fixed as of Grakn 1.5.6 :)
