### ISSUE TITLE
Parallelise tests for //client_python, //client-nodejs, //test-end-to-end

### ISSUE THREAD

**Issue by haikalpribadi** [graknlabs/grakn#4558]
Right now, these tests are configured to run with `--test_output=streamed` as an argument, which makes them run sequentially. We need to be able to make them run in parallel and provide `--test_output=errors` as argument (just to see the error messages).

**Comment by vmax** [comment]
@lolski @haikalpribadi First two might be covered by #4773 and #4774

**Comment by haikalpribadi** [comment]
does making them work with RBE mean that they'll also be parallelised, @vmax ?

**Comment by vmax** [comment]
@haikalpribadi actually, the other way: if they are properly parallelized, they'll be executed on RBE without errors

**Comment by vmax** [comment]
@haikalpribadi @lolski do you remember what were we blocked with?

**Comment by haikalpribadi** [comment]
I don't think anything particular was blocking us @vmax. It was just the fact that the tests depend on the `//:distribution` to be built and used. How are you thinking of resolving it?

**Comment by vmax** [comment]
@haikalpribadi I didn't know that depending on `//:distribution` was a bug -- and if it _is_, it should be a separate one. This particular issue addresses tests interfering with each other when ran in parallel.

**Comment by vmax** [comment]
Fixed by graknlabs/client-nodejs#38, graknlabs/client-python#39 — PRs that make tests for clients execute on RBE
