### ISSUE TITLE
Encapsulate Grakn's Node.js RPC library into //protocol:protocol-nodejs

### ISSUE THREAD

**Issue by haikalpribadi** [graknlabs/grakn#4566]
When we worked on PR #4564, were not able to complete the work for Node.js because `rules_nodejs` seem to have a bug where an `npm_package` could not consume `node_grpc_compile` when they sit across separate packages in bazel. We need to fix the `rules_nodejs` bug and then solve this issue.

**Comment by vmax** [comment]
@haikalpribadi Since we moved `//protocol:protocol-python` to `//client-python:rpc_raw`, should we still do this one?
