### ISSUE TITLE
Enable importing client-python using Bazel

### ISSUE THREAD

**Issue by haikalpribadi** [graknlabs/grakn#4571]

**Comment by vmax** [comment]
@haikalpribadi
do we assume here that whoever tries to use `client-python` from another `bazel` project is also using [`bazelbuild/rules_python`](https://github.com/bazelbuild/rules_python)?

if so, shall we make a `grakn-client-python-example` repo, similar to what we have [for java client](https://github.com/lolski/grakn-java-client-example)?

**Comment by haikalpribadi** [comment]
@vmax I dont know what the requirement is on the user side. It should be as minimal as possible. We don't need a full repo for examples. We have a repo for examples already at https://github.com/graknlabs/examples where you can add bazel build examples for each language too.

**Comment by vmax** [comment]
@haikalpribadi 
user (==Python developer)'s requirement here is mostly to be able to do `pip install grakn` and be good to go

**Comment by haikalpribadi** [comment]
Okay. If the user is able to instal with `pip install grakn` does that mean they can integrate it into their development environment regardless of their build system (e.g. Bazel) @vmax ?
