### ISSUE TITLE
Enable importing client-nodejs using Bazel

### ISSUE THREAD

**Issue by haikalpribadi** [graknlabs/grakn#4572]

**Comment by vmax** [comment]
@haikalpribadi
do we assume here that whoever tries to use `client-nodejs` from another `bazel` project is also using [`bazelbuild/rules_nodejs`](https://github.com/bazelbuild/rules_nodejs)?

if so, shall we make a `grakn-client-nodejs-example` repo, similar to what we have [for java client](https://github.com/lolski/grakn-java-client-example)?
