### ISSUE TITLE
Create //:deploy-brew which deploys 'grakn-core-all' to the brew package manager

### ISSUE THREAD

**Issue by lolski** [graknlabs/grakn#4573]
Build a bazel target `//:deploy-brew` which deploy to brew. It needs to call the following command:

```
brew bump-formula-pr --url=https://github.com/graknlabs/grakn/releases/download/v1.4.2/grakn-core-1.4.2.zip
```

Do a research if this command can also be ran from Linux

**Comment by vmax** [comment]
@lolski 
- does this command rely on **already-deployed** GH URL? 
- shall we read version from [`VERSION`](https://github.com/graknlabs/grakn/blob/master/VERSION)?

**Comment by haikalpribadi** [comment]
Do a check at the start of `deploy-brew` rule, (e.g. a `curl` command) to see if the URL is alive. If not, throw an exception. If alive, then proceed to deploying to brew.

**Comment by haikalpribadi** [comment]
and produce the URL form `VERSION` file.
