### ISSUE TITLE
Separate deployment package into a dedicated repository

### ISSUE THREAD

**Issue by lolski** [graknlabs/grakn#4578]
In addition to `grakn`, we need to use deployment package in `benchmark` and also potentially `grakn-kgms`. Therefore, we should split it into its own repository so it can be imported by the repository who needs to be able to deploy

**Comment by vmax** [comment]
@lolski do you mean deployment _package_ or a package with deployment **rules** here?

**Comment by lolski** [comment]
@vmax I meant the actual deployment package itself, ie., `./dependencies/deployment`

so that on other repositories it can be included as an external dependencies

**Comment by vmax** [comment]
We now have [`graknlabs/deployment`](https://github.com/graknlabs/deployment)
