### ISSUE TITLE
The deploy_maven_jar rule should know how to create a single JAR from a package along with their subpackages

### ISSUE THREAD

**Issue by lolski** [graknlabs/grakn#4579]
Often we have a Bazel package that is to big for it to exist by itself. Therefore it makes sense to split it into multiple sub-packages.

However we still want to deploy a single JAR consisting of all of them aggregated into one file, rather than having 1 JAR file for each of the sub-package.

**Comment by haikalpribadi** [comment]
Right now, `//client-java` has one `BUILD` file sitting at the root of the package. We want to split the `BUILD` files to be declared at every sub-package of `//client-java`. Thus, we will have:
- `//client-java/BUILD`
- `//client-java/concept/BUILD`
- `//client-java/exception/BUILD`
- `//client-java/executor/BUILD`
- `//client-java/rpc/BUILD`

However, there should only be one `deploy-maven-jar` target, sitting at the package root `//client-java/BUILD`. The `deploy-maven-jar` target should be able to build the dependency list `client-java/pom.xml` by _"aggregating_" dependencies from all the 5 `BUILD` files from the sub-packages defined above.

The _"aggregation function"_ should not traverse dependencies of Grakn modules (such as `//common`) in which `//client-java` depends on. Instead, `//common` should be a direct maven dependency. Likewise, the _"aggregation function"_ should not traverse the dependencies of External modules (such as Google AutoValue) in which `//client-java` depends on. Instead, they should be direct maven dependencies.
