### ISSUE TITLE
Tests on CircleCI fail because transactions clash in the same thread

### ISSUE THREAD

**Issue by haikalpribadi** [graknlabs/grakn#4582]
The issue occurs when doing:
```
bazel test //test-integration/test/graql/reasoner/... --test_output=errors
```

I've tested on my machine and everything works fine. The error only occurs in CircleCI and you can see (and rerun) the test here: https://circleci.com/gh/haikalpribadi/grakn/929

**Comment by haikalpribadi** [comment]
This is so interesting: after I reran the test, it all passes. https://circleci.com/gh/haikalpribadi/grakn/943

My other PRs are also passing. I can't seem to reproduce it anymore. See if the initial link in the description contains any useful information to debug.

**Comment by lolski** [comment]
This looks like a real flaky test, which is not build related. Do you know about this failure, @kasper-piskorski ?

**Comment by haikalpribadi** [comment]
@kasper-piskorski you should wrap transactions in an auto-closable `try{ }` block so that when the test fails, it remembers to close the transaction. This doesn't solve the root cause of this issue, but it helps to not cause other tests to fail due to transaction clashes.

I've made this change in my fork. In case this change hasn't got into master by the time you work on this, you can see (and pull it) here: https://github.com/haikalpribadi/grakn/blob/refactor/test-integration/test/graql/reasoner/atomic-query/AtomicQueryUnificationIT.java
