### ISSUE TITLE
Graql: When super type and subtype both has attribute, attribute is given twice

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/grakn#4599]
Consider this example:

```
exchange sub relationship,
        relates receiver, 
        relates provider, 
        relates object,
        has exch-date,
        has appendix; 
    export sub exchange,
        relates receiver, 
        relates provider, 
        relates object,
        plays correspondence-export,
        has exch-date,
        has appendix;
```

In workbase, the attributes for use as labels on `export` are shown in duplicate because they are also available on its supertype. We believe this is actually a Graql bug, not a workbase issue.

I don't know the actual query being executed here.

**Comment by kasper-piskorski** [comment]
Reproduced - I confirm that duplicates are returned.
