### ISSUE TITLE
Grakn should not automatically create keyspaces

### ISSUE THREAD

**Issue by marco-scoppetta** [graknlabs/grakn#4601]
As of now Grakn automatically creates a keyspace if it does not exist when opening a new session.

We want to change this behaviour so that the user needs to explicitly create a keyspace before opening a connection to it.

**Comment by marco-scoppetta** [comment]
do we still want to have this? It's been a while since the last we have discussed this.

**Comment by haikalpribadi** [comment]
yes we still want this in the future @marco-scoppetta

**Comment by vmax** [comment]
Now there's a separate API method to create the database so it's done.
