### ISSUE TITLE
Grakn script should just pass 2nd argument and onwards into console and daemon

### ISSUE THREAD

**Issue by haikalpribadi** [graknlabs/grakn#4622]
At the moment, let's saw we call the grakn script by saying: 
- `./grakn console arga argb argc`, This will result in `grakn.core.console.GraknConsole` receiving `[console, arga, argb, argc]` as the list of arguments. 
- the same case applies to `./grakn server arga argb argc`. `grakn.core.daemon.GraknDaemon` will receive `[server, arga, argb, argc]` as the list of arguments.

We should clean this up, so that only `[arga, argb, argc]` is passed as an argument, as the first one is not necssary. Console/Daemon does not need the first keyword and at the moment we clean this up by ignoring it in the main function of Console/Daemon.

> Note: in Bash this is easy, we can just pass `"${@:2}"` after the calling the java class. But in `.bat` files I have no idea, and a quick search does not show a simple way.

**Comment by marco-scoppetta** [comment]
This can be implemented after refactoring `./grakn version` to be `./grakn server version` and add `./grakn console version`, in which case we don't need to switch on the first (`server`) argument

**Comment by marco-scoppetta** [comment]
Closing as we decided to keep the omission in Java rather than having 2 different version of skipping.
