### ISSUE TITLE
Workbase causes Grakn server shutdown to stall

### ISSUE THREAD

**Issue by BFergerson** [graknlabs/grakn#4647]
It has done this several times to me now so I know they are related. Basically, if I have workbase open and I have entities and relationships pulled up, whenever I go to run:
```
./grakn server stop
```
It will hang at stopping the engine like so:
```
Stopping Engine...................................SUCCESS
```

When it finally does say `SUCCESS` it's only because I've either closed workbase or I've run reloaded (control+R) workbase.

Version: Grakn 1.4.2
OS: Ubuntu 18.04.1 LTS

**Comment by Irtazaraza** [comment]
Hi @BFergerson 
This is a known issue: #4126
