### ISSUE TITLE
Implicit relations are created inconsistently

### ISSUE THREAD

**Issue by kasper-piskorski** [graknlabs/grakn#4697]
Execution of a generic query:
```
match $x isa thing;get;
```

is affected if we query for inferrable attributes beforehand:
```
match
$x isa thing;
$x has attribute "unattached";
get;
```

Dataset: resourceAttachment.gql

Reason:

Attribute atoms in fact contain information about two other IsaAtoms:
- the attribute Isa
- the implicit relation Isa

This means that a single answer of an attribute atom corresponds to 2 answers of `Thing($x)`.

When checking for rule applicability we convert the attribute to attribute Isa to match the `Thing($x)`. When we process however the implicit relation Isa never exists and we only obtain a single answer from the attribute rule head.

**Comment by alexjpwalker** [comment]
Implicit relations are gone in 1.8.
