### ISSUE TITLE
Have certain console commands as grakn options

### ISSUE THREAD

**Issue by sorsaffari** [graknlabs/grakn#4698]
At the moment, the following requirements are implemented as part of the console:
- `>>> license`: **command** to print out the license
- `--version`: **option** to print out Grakn's version

Both of these requirements have nothing to do with the purpose of the console which is to be an interface for interacting with a keyspace.

It'd make more sense to have them as options of `grakn`:
- `./grakn --version`
- `./grakn --license`

**Comment by lolski** [comment]
based on on the discussion with @haikalpribadi  and @vmax, we decided to close the PR and revisit it later. I'm removing the label "in progress".

**Comment by vmax** [comment]
Adding `blocked` as a reminder that task does **not** contain exact definition of what needs to be done.

**Comment by flyingsilverfin** [comment]
Closed since we now print version number on grakn server start too
