### ISSUE TITLE
the type.label(value) method in Client Node.js doesn't return a Type object

### ISSUE THREAD

**Issue by sorsaffari** [graknlabs/grakn#4716]
Grakn version: 1.4.2

## Reproducing steps:
```
./graql console -k test
>>> define person sub entity;
>>> insert $x isa person;
>>> commit 
```

via client Node.js, run:
```javascript
go();
async function go() {
  const grakn = new Grakn("localhost:48555");
  const session = await grakn.session((keyspace = "test")); 
  const tx = await session.transaction(Grakn.txType.WRITE);
  const answerIterator = await tx.query("match $x isa person; limit 1; get;");

  let aConceptMapAnswer = await answerIterator.next();
  while ( aConceptMapAnswer != null) {
    const person = aConceptMapAnswer.map().get("x");
    const personType = await person.type();
    console.log(await personType.label("human"));
    aConceptMapAnswer = await answerIterator.next();
  }
  tx.close();
  session.close();
}
```

## Expected outcome:
an EntityType object

## Actual outcome
```
{ wrappers_: null,
  messageId_: undefined,
  arrayIndexOffset_: -1,
  array: [],
  pivot_: 1.7976931348623157e+308,
  convertedFloatingPointFields_: {} }
```

The equivalent of the code above, prints out for Client:
- Java: `RemoteEntityType{tx=ai.grakn.client.Grakn$Transaction@436c81a3, id=V8336}`
- Python: `<grakn.service.Session.Concept.Concept.EntityType object at 0x10720c198>`

**Comment by marco-scoppetta** [comment]
@sorsaffari I think this line is the issue:
` const session = await grakn.session((keyspace = "test")); `
I have never seen the notation `(keyspace = "test")`, try with:
` const session = await grakn.session("test"); `,

it works for me

**Comment by marco-scoppetta** [comment]
It's expected behaviour, from the documentation:

![image](https://user-images.githubusercontent.com/6430514/50015690-11f67100-ffbf-11e8-8a3c-2558a28e53d0.png)

in the nodejs client I never return the object on the setters because the JS nature does not allow the user to chain operation when `Promises` are returned
