### ISSUE TITLE
Graql: When undefining an attribute type its implicit relationship isn't undefined

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/grakn#4719]
```
define 
name sub attribute datatype string;
person sub entity, 
    has name;
```
Find the schema elements to be as expected:
```
> match $x sub thing; get;
{$x label thing;}
{$x label entity;}
{$x label attribute;}
{$x label relationship;}
{$x label person sub entity;}
{$x label name sub attribute;}
{$x label "@has-attribute" sub relationship;}
{$x label "@has-name" sub "@has-attribute";}
```
Then try indefinite `name`:
```
> undefine name sub attribute;
```

```
> match $x sub thing; get;
{$x label thing;}
{$x label entity;}
{$x label attribute;}
{$x label relationship;}
{$x label person sub entity;}
{$x label "@has-attribute" sub relationship;}
{$x label "@has-name" sub "@has-attribute";}
```
We see that `{$x label name sub attribute;}` is no longer present, but `{$x label "@has-name" sub "@has-attribute";}` is.Expected behaviour is to remove the implicit attribute type when the attribute type is removed.

**Comment by haikalpribadi** [comment]
The implicit attribute-relationship (`@has-attribute`) is actually created (and managed) by the Types that own them. In this example above, it will be managed by `person`. If you `undefine person has name` the implicit attribute-relationship should be removed (as addressed in PR #4877).

However, doing `undefine name sub attribute` should not be allowed to begin with there are entities owning that attribute. This should be caught upon `commit`. Did you try verify that `commit`ing the above code will throw you an exception? @jmsfltchr

**Comment by haikalpribadi** [comment]
If you can confirm the behaviour is as explained in the comment above, @jmsfltchr, please close this issue and label it as `invalid`.

**Comment by jmsfltchr** [comment]
Overall, the behaviour expected in order to open this issue is invalid.

However, the actual behaviour is not as [described](https://github.com/graknlabs/grakn/issues/4719#issuecomment-462076982), and so a new issue has been opened for that, #4952.
