### ISSUE TITLE
`http_archive` rule is deprecated - update.sh changes required

### ISSUE THREAD

**Issue by flyingsilverfin** [graknlabs/grakn#4736]
```
✔ 14:20: ~/Documents/grakn-dev/nd4j-dependency-failure/bazel [master|✚ 21⚑ 1]> ./dependencies/maven/update.sh 
INFO: Invocation ID: 38b03bd1-d9ae-4cf3-9a5d-4db90b64e18f
INFO: Build options have changed, discarding analysis cache.
ERROR: /Users/joshua/Documents/grakn-dev/nd4j-dependency-failure/bazel/dependencies/tools/BUILD:20:1: no such package '@bazel_deps//file': The native http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule. and referenced by '//dependencies/tools:bazel-deps-jar'
ERROR: Analysis of target '//dependencies/tools:bazel-deps' failed; build aborted: no such package '@bazel_deps//file': The native http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule.
```

Bazel version 0.20 deprecates `http_archive`. Advice offered in the error above is to use a different drop in replacement.

Will be applicable to benchmark repository & grakn, at the least.

**Comment by vmax** [comment]
@flyingsilverfin I'm afraid replacing native rules with macros loaded from library would all lead to us being unable to define macros which we import into `WORKSPACE` because of bazelbuild/bazel#1550

FYI @haikalpribadi @lolski

**Comment by haikalpribadi** [comment]
what's the right solution @vmax ?

**Comment by vmax** [comment]
@haikalpribadi I don't see any other solutions other than putting everything into `WORKSPACE` directly. They'll remove native rules completely at some point in time.

**Comment by haikalpribadi** [comment]
okay then @vmax

**Comment by vmax** [comment]
@haikalpribadi it actually works, I might have been confused by error message. Continuing to work on the issue 🙂

**Comment by haikalpribadi** [comment]
what "actually works", @vmax ?

**Comment by vmax** [comment]
@haikalpribadi Using new rules as drop-in replacements to deprecated `http_file`, `git_repository` in `.bzl` files
