### ISSUE TITLE
Allow using isan in place of isa in queries

### ISSUE THREAD

**Issue by umaxfun** [graknlabs/grakn#4770]
Is it possible to allow using `isan` instead `isa` in queries like `$p isa itsystem has name "SAP HCM";`? Looks at least weird, and half of entity names happen to start with vowel in the small IT domain :)
- itsystem
- integration
- integration_requirement
- ownership

**Comment by haikalpribadi** [comment]
Hi @umaxfun, we appreciate the idea of making Graql closer to natural language! That's the design philosophy that we have in the team as well. However, just like any other query/programming language, Graql is still a _"structured language"_. So our design will still be bounded by the fact that it is a structured language, which has to be consistent. The other principle that we abide to is simplicity. Making the alias for one of the most widely and expressively used keywords such as `isa`, e.g. `isan` which needs to consider the first letter of the subsequent word will make the language less consistent and more complex. So, unfortunately, we will have to reject this feature request. :) But please keep the ideas coming! 👍
