### ISSUE TITLE
Update //client_python:test-integration to work with RBE

### ISSUE THREAD

**Issue by lolski** [graknlabs/grakn#4774]
`//client_python:test-integration` doesn't yet work with RBE. Follow the approach done by `//test-end-to-end/client-java:client-java-e2e` in order to make it work:
- The test needs to depend on `//:distribution` so it knows to re-run the test when the distribution is changed in any way.
- Grakn needs to be started and stopped from within the test as opposed to from circleci

Once the test has been made to work with RBE, change the circleci yml such that `//client_python:test-integration` is executed using the RBE mode:
```
bazel:
  command: bazel ...
```

**Comment by vmax** [comment]
Replaced with graknlabs/client-python#2
