### ISSUE TITLE
Grakn Academy page is missing

### ISSUE THREAD

**Issue by dcalano** [graknlabs/grakn#4779]
https://dev.grakn.ai/academy

is returning "Sorry, but the page you were trying to view does not exist. Try searching for it or looking at the URL to see if it looks correct."

**Comment by sorsaffari** [comment]
@dcalano The documentation has recently been rewritten. Please have a read on the **New Grakn Documentation** section in the [1.4.3 release notes](https://discuss.grakn.ai/t/grakn-core-kgms-1-4-3-and-new-docs-are-unleashed/1070) to find out about the new docs and its structure :)
