### ISSUE TITLE
Find ways to execute rules which depend on 'pkg_rpm' on the RBE

### ISSUE THREAD

**Issue by lolski** [graknlabs/grakn#4797]
At the moment we had to force `pkg_rpm()` to be executed locally: https://github.com/graknlabs/grakn/pull/4796

Find a way to make it work in RBE

**Comment by vmax** [comment]
@lolski how can I contact RBE team to figure this out? Basically, it'd work (I think) if we manage to have a custom image which already includes `rpmbuild`

**Comment by vmax** [comment]
It *is* possible using these techniques (though not too practical):
- create a custom Docker image based on image used on RBE and deploy it to GCR (**should** be publicly-accessible GCR - not Docker Hub or other repo)
- modify `@graknlabs_build_tools//:rbe-ubuntu1604-network-standard` to include link to newly-deployed image

Relevant issue: bazelbuild/bazel-toolchains#456

**Comment by vmax** [comment]
Adding `blocked` label until it is resolved on RBE side

**Comment by vmax** [comment]
@lolski @haikalpribadi please see the RBE team member's response on the issue I linked: it's unlikely that it'll be resolved on RBE side. What shall we do?

**Comment by haikalpribadi** [comment]
Okay I've read it; that's a shame. The concern that I have is that we won't always be up to date with the latest RBE image. However, this is still tolerable, as long as we can properly schedule upgrades every month, let's say. So let's create our own image so we can speed up the CI. @vmax @lolski
