### ISSUE TITLE
Create a domain name for the Sonatype repository that's running on GCP and update deployment.properties accordingly

### ISSUE THREAD

**Issue by lolski** [graknlabs/grakn#4817]

**Comment by haikalpribadi** [comment]
This is already `in progress` or `solved` right, @vmax ?

**Comment by vmax** [comment]
This is done:
- [repo.grakn.ai](repo.grakn.ai) is pointing to Sonatype instance deployed on GCP
- [deployment.properties](https://github.com/graknlabs/build-tools/blob/master/deployment.properties) have proper values
