### ISSUE TITLE
Graql Sorting of Strings should be case insensitive

### ISSUE THREAD

**Issue by SamuelHassine** [graknlabs/grakn#4828]
Hello,

When using the Grakn feature to order results by a String property, all words with an uppercase first letter come before lowercase first letter word.

The query:

> 
> match $m isa User; $m has name $o; 
>       order by $o asc; offset 0; limit 25; 
>       get $m;
> 

returns the following results:

- Bob
- Yann
- alice
- carl

Is this behavior normal?

Best regards,
Samuel

**Comment by haikalpribadi** [comment]
Hi @SamuelHassine, sorry for the late response on this! The above behaviour is expected given the current way we implemented Sorting on Strings. However, you brought a good improvement point. I will mark this as feature (for improvement) and have it implemented in the next release. 

The resulting behaviour, using your above example, should be:
- alice
- Bob
- carl
- Yann

Thanks for pointing this out! Keep them coming :)

**Comment by haikalpribadi** [comment]
Actually, I think this is actually a bug rather than a feature improvement. I've fixed it in PR #4914 now @SamuelHassine. Thanks for pointing it out!
