### ISSUE TITLE
Graql "contains" case insensitve or allow regex 

### ISSUE THREAD

**Issue by SamuelHassine** [graknlabs/grakn#4831]
Hello,

The Grakn query using "contains" on attribute is currently case sensitive, that is not very useful in fulltext research. This query should be case insensitive. 

Using regex on attribute to search case insensitive keyword is not possible now, please refer to the forum topic: https://discuss.grakn.ai/t/case-insensitive-matching-with-contains-or-regex-or-anything/594/5.

The "/i" at the end of the regex is not accepted in the query syntax.

Best regards,
Samuel

**Comment by haikalpribadi** [comment]
Thanks for reporting this @SamuelHassine ! We've now implemented the `contains` predicate to be case-insensitive in PR #4988. 👍
