### ISSUE TITLE
Split out common parts of CircleCI config

### ISSUE THREAD

**Issue by vmax** [graknlabs/grakn#4840]
As we start splitting out repos (#4818, #4819, #4821), we'll have a lot of sections in `.circleci/config.yml` that overlap between repos. A way to reuse them needs to be found.
[Orbs](https://circleci.com/docs/2.0/creating-orbs/) feature of CircleCI might be helpful here.

**Comment by haikalpribadi** [comment]
Do you believe it's best to leave this to `v1.6` milestone, @vmax @lolski ?

**Comment by lolski** [comment]
@haikalpribadi @vmax the responsibility of storing common parts of the CircleCI config in a reusable manner is handled by `build-tools`. We decided not to use CircleCI Orbs because it would introduce another "infrastructure" in our build system. Shall we close this ticket?

**Comment by haikalpribadi** [comment]
Yes, this issue was solved by us implementing the `build-tools` repo, @lolski. I'm closing this now.
