### ISSUE TITLE
Flaky test: reusingAttributes_queryingForGenericRelation in AttributeAttachmentIT

### ISSUE THREAD

**Issue by kasper-piskorski** [graknlabs/grakn#4872]
Test: reusingAttributes_queryingForGenericRelation

```
reusingAttributes_queryingForGenericRelation(grakn.core.graql.reasoner.reasoning.AttributeAttachmentIT)
java.lang.AssertionError: expected:<3> but was:<2>
```

Seems that combination of PRs #4855 and  #4853 caused it to be flaky.

**Comment by haikalpribadi** [comment]
This is where it first occurred: https://circleci.com/gh/graknlabs/grakn/12594
And here's a second time it happened: https://circleci.com/gh/haikalpribadi/grakn/6270
