### ISSUE TITLE
Ensure correct Bazel Workspace name

### ISSUE THREAD

**Issue by lolski** [graknlabs/grakn#4882]
- Bazel Workspace Name should be `@graknlabs_grakn_core`
- Other repositories which depends on it must be updated as well:
    - client-java
    - client-python
    - client-nodejs
    - workbase
    - docs
    - examples

**Comment by vmax** [comment]
Verified:

[V] [`client-java`](https://github.com/graknlabs/client-java/blob/ee53827f3c89715a8818c79cb2542572ffddd437/WORKSPACE#L4)
[V] [`client-python`](https://github.com/graknlabs/client-python/blob/496c369847e44a58fe7cdfed6cead85031708f96/WORKSPACE#L4)
[V] [`client-nodejs`](https://github.com/graknlabs/client-nodejs/blob/c3d9179b90d8617794b60a0cfc18da10660dbaa8/WORKSPACE#L4)
[V] [`workbase`](https://github.com/graknlabs/workbase/blob/45f8f4a41de175e7988534005c4d4ff0a3ee0143/WORKSPACE#L26)
[V] [`docs`](https://github.com/graknlabs/docs/issues/49)
[V] [`examples] — not `bazel`ized yet
