### ISSUE TITLE
Develop deployment test

### ISSUE THREAD

**Issue by lolski** [graknlabs/grakn#4900]
- Does not need to run on RBE
- The test should be `ClientJavaE2E` and `DistributionE2E`
- The tests should be ran on GCP, on these platforms:
  - Ubuntu - tar.gz, deb
  - CentOS - tar.gz, rpm
  - Windows - zip
  - Mac - zip

**Comment by haikalpribadi** [comment]
Does the plan for this issue remain the same given issue #5003, @lolski ? Should `ClientJavaE2E` be cloned in `@graknlabs_grakn_core` and `@graknlabs_client_java`, or should one reuse the other?

Also, if we're not using RBE, then it definitely shouldn't be ran in PR tests. Should we restrict it to post-merge commits on `master`, as well as post-release-approval? Or just post-release-approval?

**Comment by vmax** [comment]
The plan is as follows:

- reuse existing E2E tests
- depend on *all* possible distribution variants (TarGz/Deb/RPM/ZIP)
- when running a test, detect a platform via means of Java (i.e. distinguish between RPM-based / DEB-based repos based on presence of `dpkg` in `PATH` or reading `lsb_release`)
- start Grakn appropriately for each platform (unzip the zip file / install the package)

Test _probably_ would need to be ran with `--spawn_strategy=standalone`

**Comment by vmax** [comment]
We decided to *not* do the approach outlined above and instead do setup in CircleCI's `config.yml`. Test will be already getting `grakn` available in `$PATH`
