### ISSUE TITLE
key does not enforce uniqueness

### ISSUE THREAD

**Issue by sorsaffari** [graknlabs/grakn#4928]
Grakn version: 1.5 SNAPSHOT

```
define

name sub attribute,
  datatype string;

person sub entity,
  key name;
```

`insert $x isa person, has name "a";`
`commit`
`insert $x isa person, has name "a";`
`commit`

## Expected outcome:
the second query not to be committed with a descriptive error message explaining the violation of uniqueness for  key `name` of entity `person`.

## Actual outcome
both queries are committed successfully.

**Comment by richard-julien** [comment]
How the 1.5 will handle existing database (with already the usage of **key**) with duplicate information?

**Comment by lolski** [comment]
@richard-julien an existing database will still have duplicate information, given that we check for uniqueness during data insertion.
