### ISSUE TITLE
Single locking mechanism in SessionFactory

### ISSUE THREAD

**Issue by flyingsilverfin** [graknlabs/grakn#4968]
Currently SessionFactory uses `LockManager` and does atomic operations on the internal concurrent hash map using `.map.compute()`. The latter is currently rather messy due to edge cases arising from concurrent deletions of keyspaces, but is more fine-grained than using `synchronized` everywhere. We should decide on using the LockManager, `.compute()` or just `synchronized` consistently.

**Comment by marco-scoppetta** [comment]
Done
