### ISSUE TITLE
It's necessary to be in the same directory as the grakn binary in order to load a Graql file

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/grakn#5015]
## Description

Whilst working on kglib's CI pipeline, I encountered that the following command gave a file not found error:
`grakn-core-all/grakn console -k test_schema -f kglib/kgcn/test_data/schema.gql`, even though the file was present. 
Changing the command to `cd grakn-core-all && ./grakn console -k test_schema -f ../kglib/kgcn/test_data/schema.gql` fixed the issue

## Environment

1. OS (where Grakn server runs): CircleCI machine
2. Grakn version (and platform): Grakn commit 20750ca0a46b4bc252ad81edccdfd8d8b7c46caa
3. Grakn client: trying to call console
4. Other environment details: -

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Make a `.gql` schema file one directory above (called `parent`) a grakn binary, called `schema.gql`
2. `cd parent`
3. `parent/grakn console -k test -f schema.gql'
4. Receive a file not found error

## Expected Output

Expect the schema to load, which was working in previous Grakn versions

## Actual Output

The schema .gql file wasn't correctly found

**Comment by mariusa** [comment]
Confirming. I get
```
java.nio.file.FileSystemException: ./grakn/social-network-schema.gql: Not a directory
```

As a workaround, full path works:
grakn console --keyspace social_network --file $(pwd)/grakn/social-network-schema.gql

Note, server was installed & started as root. console is run as regular user.

**Comment by marco-scoppetta** [comment]
https://github.com/graknlabs/grakn/pull/5406
