### ISSUE TITLE
Duplicate implicit relations

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/grakn#5027]
## Description

I found that it is possible to somehow insert duplicates of an implicit relation. The console output below confirms this

```
animaltrade_train> match $x id V696448; $r($x) isa @has-endangerment-level; get;
{$r id E1crua8-exds-glx-fu8 (@has-endangerment-level-owner: id V696448, @has-endangerment-level-value: id V20528) isa @has-endangerment-level; $x id V696448 isa traded-item;}
{$r id E1cruog-exds-glx-fu8 (@has-endangerment-level-owner: id V696448, @has-endangerment-level-value: id V20528) isa @has-endangerment-level; $x id V696448 isa traded-item;}
```

## Environment

1. OS (where Grakn server runs): Locally, MacOS Mojave
2. Grakn version (and platform): Commit `20750ca0a46b4bc252ad81edccdfd8d8b7c46caa`
3. Grakn client: client-python commit `5459d5d88a30631c5ebdac3a9b0d5ea6f184c8ae`
4. Other environment details: -

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Download Grakn with data from the kglib v0.1a3 release 
https://github.com/graknlabs/kglib/releases/download/v0.1a3/grakn-animaltrade.zip
2. Load the attached file into the `animaltrade_train` keyspace
3. I noticed the issue in workbase using query: `match $kgcn isa kgcn-model, has kgcn-model-version $v; $vp($kgcn, $pred) isa value-prediction; $pred($a) isa @has-endangerment-level; get; offset 0; limit 5;`
4. You can detect them better using `match $x isa traded-item; $r($x) isa @has-endangerment-level; $r2($x) isa @has-endangerment-level; $r != $r2; get; limit 5;`

## Expected Output

There should be only one `@has-endangerment-level` relation between any two things.

## Actual Output

You will see identical implicit relations:
```
animaltrade_train> match $x isa traded-item; $r($x) isa @has-endangerment-level; $r2($x) isa @has-endangerment-level; $r != $r2; get; limit 5;
{$r2 id E215r7l-dp1k-glx-fu8 (@has-endangerment-level-owner: id V638984, @has-endangerment-level-value: id V20528) isa @has-endangerment-level; $r id E215se9-dp1k-glx-fu8 (@has-endangerment-level-owner: id V638984, @has-endangerment-level-value: id V20528) isa @has-endangerment-level; $x id V638984 isa traded-item;}
{$r2 id E215r7l-dp1k-glx-fu8 (@has-endangerment-level-owner: id V638984, @has-endangerment-level-value: id V20528) isa @has-endangerment-level; $r id E215s01-dp1k-glx-fu8 (@has-endangerment-level-owner: id V638984, @has-endangerment-level-value: id V20528) isa @has-endangerment-level; $x id V638984 isa traded-item;}
{$r2 id E215r7l-dp1k-glx-fu8 (@has-endangerment-level-owner: id V638984, @has-endangerment-level-value: id V20528) isa @has-endangerment-level; $r id E215rlt-dp1k-glx-fu8 (@has-endangerment-level-owner: id V638984, @has-endangerment-level-value: id V20528) isa @has-endangerment-level; $x id V638984 isa traded-item;}
{$r2 id E215se9-dp1k-glx-fu8 (@has-endangerment-level-owner: id V638984, @has-endangerment-level-value: id V20528) isa @has-endangerment-level; $r id E215r7l-dp1k-glx-fu8 (@has-endangerment-level-owner: id V638984, @has-endangerment-level-value: id V20528) isa @has-endangerment-level; $x id V638984 isa traded-item;}
{$r2 id E215se9-dp1k-glx-fu8 (@has-endangerment-level-owner: id V638984, @has-endangerment-level-value: id V20528) isa @has-endangerment-level; $r id E215s01-dp1k-glx-fu8 (@has-endangerment-level-owner: id V638984, @has-endangerment-level-value: id V20528) isa @has-endangerment-level; $x id V638984 isa traded-item;}
```
 
## Additional information
[prediction_schema.gql.txt](https://github.com/graknlabs/grakn/files/2963063/prediction_schema.gql.txt)

-

**Comment by alexjpwalker** [comment]
Implicit relations are gone now.
