### ISSUE TITLE
Refactor tests into the right packages

### ISSUE THREAD

**Issue by lolski** [graknlabs/grakn#5043]
## Problem to Solve

Currently, there is an inconsistency where the root test structure looks like this:
```
test-end-to-end/
test-integration/
test/
  assembly/
  deployment/
  common/
```

We also have some unit tests sitting across the repositories packages and subpackages.

## Proposed Solution

There should be 4 categories of tests: unit, integration, assembly, deployment. All unit tests should sit inside the package in which the unit test is testing. The rest of the test categories should sit under `test/`:
```
test/
  integration/
  assembly/
  deployment/
```

Additionally, you may need to have `test/common` package for any shared code.

**Comment by haikalpribadi** [comment]
@kasper-piskorski given that most of the tests in Grakn Core for reasoner, can you help me on this issue and make sure we organise our tests neatly in the proposed structure above?

@flyingsilverfin for all the Graql tests, do you think we can migrate them over to the `@graknlabs_behaviour` repo? Basically, can we move the test coverage from the integration tests (where most of them sit right now) to be incorporated in the axiomatic theorem tests? cc: @jmsfltchr

**Comment by haikalpribadi** [comment]
1) Inside `//test-end-to-end` exists `ClientJavaE2E2`. This test should be moved to `@graknlabs_client_java//test` (`/assembly` or `/deployment`)
2) `Deduplicator` test should really be Integration Tests for `grakn.core.server.deduplicator`. We should not test `Deduplicator` using `GraknClient`, and use TransactionOLTP instead.
3) Distribution test should be grakn-core's "assembly tests" (`//test/assembly`)

**Comment by flyingsilverfin** [comment]
https://github.com/graknlabs/client-java/pull/96 will complete 1. in haikal's comment
