### ISSUE TITLE
Unzipping grakn dist using Mac Finder (UI) does not preserve executable persmissions

### ISSUE THREAD

**Issue by Irtazaraza** [graknlabs/grakn#5044]
## Description
Unzipping grakn dist using Mac Finder (UI) does not preserve executable persmissions

## Environment

1. OS (where Grakn server runs): Mac OS 10
2. Grakn version (and platform): Grakn 1.5

## Reproducible Steps

Steps to create the smallest reproducible scenario:
bazel build //:assemble-mac-zip
copy dist zip to a dir
double click to unzip from Finder

## Expected Output
`-rwxr-xr-x  1 user staff  3274  1 Jan  1980 grakn`

## Actual Output

`-rw-------  1 user staff  3274  1 Jan  1980 grakn`

**Comment by marco-scoppetta** [comment]
I have tried downloading the `tar.gz` (linux version), unzipped with Mac UI Finder, I did NOT have the same issue. Everything seems to be working fine. So it seems to be happening only with `.zip`

**Comment by marco-scoppetta** [comment]
This is solved with https://github.com/graknlabs/bazel-distribution/pull/109
