### ISSUE TITLE
Suspicious behavior with Inference in BioGrakn

### ISSUE THREAD

**Issue by flyingsilverfin** [graknlabs/grakn#5051]
## Description
Querying `match $x isa sequence-midline; $x "a"; get;` returns all `sequence-midline` attributes. The behavior disappears and is correct if rules are turned off. 

## Reproducible Steps

Reproducible via:
https://github.com/graknlabs/grakn/issues/4447

Note that instructions need to be updated to instead reflect using:
* branch `blast-1.5` for grakn 1.5 compatibility
* Keyspace `blast` instead of `protein`
* Example lives in `examples/blast`
* Installing python grakn client in self contained environment:
1. install pipenv
2. in the blast directory, run `pipenv shell` (=> ensure running python 3)
3. Install `biopython` and `grakn-client` (if 1.5 is not in pypi yet, you can run `pip install https://repo.grakn.ai/repository/test-pypi/packages/grakn-client/1.5.0-1ce059329ce2af7e765cbd19a45a4e41f5411f20/grakn-client-1.5.0-1ce059329ce2af7e765cbd19a45a4e41f5411f20.tar.gz1`)

## Expected Output

`match $x isa sequence-midline; $x "a"; get;` 
should return: nothing

## Actual Output

returns ALL `sequence-midline` attrs

**Comment by Irtazaraza** [comment]
This issue does not exist anymore as of Grakn version 1.5.5.
