### ISSUE TITLE
Find a way to run all of the checkstyle test using a single 'bazel test' command

### ISSUE THREAD

**Issue by lolski** [graknlabs/grakn#5052]
```
bazel test $(bazel query --noshow_progress 'kind("checkstyle_test", //...)')
```

**Comment by lolski** [comment]
This is the solution: `bazel test $(bazel query --noshow_progress 'kind("checkstyle_test", //...)')`

**Comment by lolski** [comment]
@haikalpribadi do you remember the motivation for wanting to run just the `checkstyle_test` like this in the CI?

Right now, with the exception of `test-end-to-end`, `test-assembly-*` and `test-deployment-*`, we are already running every test in every package including the `checkstyle_test`s for those packages.

**Comment by haikalpribadi** [comment]
Yes, it's exactly because of the exception you mentioned, @lolski. We have/had checkstyle tests that we weren't running that we did not know about. I think we should be able to call all `checkstyle_test` from CI's `build` step to be sure it's all called.

**Comment by lolski** [comment]
@haikalpribadi "forgetting to run checkstyle tests" is a specific case of "forgetting to run tests". therefore we should strive to solve the latter.

**Comment by vmax** [comment]
As of latest `master`, `checkstyle` tests are ran as a separate CI job, see [this snippet](https://github.com/graknlabs/grakn/blob/b806830d57e3492ad899fd1505583abf6aa61a58/.circleci/config.yml#L52-L60).
