### ISSUE TITLE
Improve the speed of the CI on master branch

### ISSUE THREAD

**Issue by lolski** [graknlabs/grakn#5079]
## Problem to Solve

The CI on `master` takes around 50 minutes to complete. For example, here's one instance: https://circleci.com/workflow-run/8330e7e5-40a0-4796-9b71-e7f2cf96dedf

It doesn't really impact us on a day-to-day basis, however it does when we're releasing.
Ideally, it should be somewhere around 10-15 minutes to maintain the smoothness of the release process.

### Caching Tests Results
@haikalpribadi has suggested caching the SHA of our distributions. This would improve the speed by never re-running test-assembly / test-deployment more than once for a given distribution.

The logic is as follows:
1. Before commencing any test-assembly / test-deployment, check if we have the test results in the cache for the given distribution.
2a. If we don't: commence the test and add the result to the cache
2b. If we do: skip the test and return the results from the cache

Needs graknlabs/grabl#20

**Comment by vmax** [comment]
@haikalpribadi is the approach outlined in issue description still relevant? if so, we should start by introducing ability to store `{distribution_hash: test_result}` mapping in [`graknlabs/grabl`](https://github.com/graknlabs/grabl)

**Comment by haikalpribadi** [comment]
Yes, this is still needed and relevant, @vmax . Create a new service endpoint on grabl.grakn.ai for this as you suggested above. We already have Mongo as a service to manage the data behding Grabl, but I'm not sure if it allows us to add another "document". @sorsaffari knows about this.

**Comment by sorsaffari** [comment]
@haikalpribadi @vmax yes, it is possible. _Mongo as a service_ on Heroku gives us one single database which can consist of many collections (the equivalent of a table in the relational model). right now the collection, Grabl writes to and reads from is `sync_deps_dicts`. We need to create another collection to store a different type of document.

**Comment by haikalpribadi** [comment]
@vmax and @lolski - given that we're taking the approach of hashing the assembled distribution and checking the hash, do we know if we are producing consistent hashes for every assembled distribution? (ps: remember the ZIP issue not producing the same hash?)

**Comment by vmax** [comment]
@haikalpribadi probably the only way to know that is empirical — let's start using the cache and see

**Comment by haikalpribadi** [comment]
> probably the only way to know that is empirical

LOL - I figured that much, @vmax :D 

> let's start using the cache and see

But okay I agree

**Comment by lolski** [comment]
@vmax @haikalpribadi let's add the deterministic ZIP and TAR functions into the `common` package and get every rules to use that.

**Comment by haikalpribadi** [comment]
I agree with @lolski, @vmax
