### ISSUE TITLE
Grakn's Docker Hub repository is missing latest tag

### ISSUE THREAD

**Issue by BFergerson** [graknlabs/grakn#5082]
Grakn is missing a `latest` tag on Docker Hub (https://hub.docker.com/r/graknlabs/grakn/tags).

Programs like Kitematic default to `latest` tag and not having one causes errors to occur.

**Comment by haikalpribadi** [comment]
Based on the discussion of the Docker `latest` tag here: https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375 they seem recommend you *not* to use it at all since it’s not automatically updated and always use explicit versions (1.5.0, 1.6.0, …, 2.0). What do you think, @BFergerson @lolski @vmax

**Comment by BFergerson** [comment]
@haikalpribadi, I don't use Kitematic much so I likely won't run into the issue again but I will just say that if it's not too much for you guys to ensure that `latest` always points to the last version you released; I think that will be most helpful to the community. I doubt Kitematic is the only application to have special logic for the `latest` tag and there are many instances of popular images using the convention:
 - https://hub.docker.com/_/postgres
 - https://hub.docker.com/_/jetty
 - https://hub.docker.com/_/docker
 - etc

**Comment by lolski** [comment]
@haikalpribadi the main point of the article is Docker doesn't automatically update the `latest` tag when we push a new image. We need to do it ourselves:

Step 1: Push `grakn-core:1.5.3` image to Dockerhub
Step 2: Update `grakn-core:latest` to point to `grakn-core:1.5.3`

In my opinion we should have the `latest` tag given that it improves user experience. It is simple to automate and won't have many edge-cases.

cc: @vmax

**Comment by haikalpribadi** [comment]
Sounds like a good solution, @lolski !
We'll implement it soon now, @BFergerson. Thanks for suggesting this!
