### ISSUE TITLE
Test different software for unzipping Grakn on Windows

### ISSUE THREAD

**Issue by marco-scoppetta** [graknlabs/grakn#5108]
## Description

Some users reported issues when unzipping Grakn1.5 on Windows using one of the following apps:
 - Zipmail
 - MK Net.Work unZIP
 - the default (Unix-like, zlib inspired, but minimalist) unzip facility built into the utils package in R
- right click on package and click Extract All

## Current workaround

 Use WinRAR

## Environment

1. OS (where Grakn server runs): Windows 10
2. Grakn version (and platform): Grakn Core 1.5

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Download Grakn
2. Unzip it using one of the above softwares

## Expected Output

Grakn folder with correct content

## Actual Output

Empty folder

**Comment by Mnuzz** [comment]
Windows 10 built-in zip extractor did not work for me (empty archive) but WinRAR was able to extract at least some or all of the files.

**Comment by dynamicdoyle** [comment]
7-Zip also worked for me.
