### ISSUE TITLE
More unique jar names

### ISSUE THREAD

**Issue by BFergerson** [graknlabs/grakn#5127]
## Description

The jar names for the Grakn modules aren't unique enough. Both `io.grakn.client:api` and `io.grakn.core:api` have a jar name of `api-1.5.0.jar`. Not only do the jar names not mention Grakn, but they also aren't unique amongst themselves.

I noticed this while building a distribution package for https://github.com/CodeBrig/GitSocratic.
![Screenshot from 2019-04-19 18-13-32](https://user-images.githubusercontent.com/3278877/56448716-f1bd2280-62ce-11e9-85cf-49eb93677c4c.png)

## Expected Output

I would expect to be able to pick a Grakn jar out of a lineup. I would also expect to pick out the different Grakn modules.

## Actual Output

The jar names all choose `api-1.5.0.jar`. This is a pretty bold jar name. I would expect this API to contain everything :P.

## More information

Grakn's new modular structure took GitSocratic's distribution size from ~200MB to ~70MB :tada:.

**Comment by haikalpribadi** [comment]
> This is a pretty bold jar name

HAHA. Bold indeed. We also noticed this problem as well, and there is an issue filed at the repository of the root cause: https://github.com/graknlabs/bazel-distribution/issues/112. We hope to resolve this soon.

> Grakn's new modular structure took GitSocratic's distribution size from ~200MB to ~70MB 🎉.

That's the goal we intended to achieve! 🎉

**Comment by haikalpribadi** [comment]
@BFergerson may I ask if the collection of JARs above are stored in one folder by yourself (custom code) or by an application that manages maven JARs? The reason why Maven JARs do not carry group-id names is that Maven organises them into folders. See this post here: https://stackoverflow.com/questions/13370666/does-a-maven-repository-have-a-standard-format/13371622#13371622

Would it be possible for you to organise your lib jars into folders too?

**Comment by BFergerson** [comment]
@haikalpribadi, it sounds like you're asking about the [Gradle Application Plugin](https://docs.gradle.org/current/userguide/application_plugin.html). Creating a folder with `lib` and putting all the libraries in it is just how the application plugin does it.

Here is a minimally reproducible example:
```sh
git clone https://github.com/BFergerson/simple-grakn-distribution
cd simple-grakn-distribution
./gradlew distZip
```

This places a .zip file at `./build/distributions/simple-grakn-distribution-1.0-SNAPSHOT.zip` which will contain the following files:
![Screenshot from 2019-06-06 06-36-58](https://user-images.githubusercontent.com/3278877/59033265-851dc900-8825-11e9-9901-295b6bc3f647.png)

Because of the naming of your libraries, this makes it impossible run after extracting it on someone's computer because only one of the .jar files will be there. It works in the IDE and everywhere else during development because of the folder trick you mention (Gradle does something similiar with its locally cached libraries).

Am I truly the only one using Grakn with Gradle?

**Comment by haikalpribadi** [comment]
Don't worry, I'm not pushing back on this, @BFergerson :) 

I also want to resolve this, and I think it's silly for Nexus Maven to set this jar naming as a convention. It may be that we just have to bow to them and change our artifact names to be less elegant.

**Comment by BFergerson** [comment]
@haikalpribadi, any chance this could make it into Grakn 1.5.7?

**Comment by haikalpribadi** [comment]
Yes, @BFergerson, it's actually on my plate. In the end, the solution is to just rename the artifact ID of our Maven packages, sadly. :(

**Comment by BFergerson** [comment]
@haikalpribadi, thanks for taking care of this. I noticed in the ticket names that it says to prefix "grakn-" and "graql-"; Does this also ensure that the `io.grakn.client:api` and `io.grakn.core:api` artifacts will have unique names? Adding "grakn-" to the both of them would result in two "grakn-api-1.5.0.jar"

**Comment by haikalpribadi** [comment]
You're welcome, @BFergerson ! Always feel free to bump things up if we any issues get forgotten, and thanks for reminding me of this one. 

> Does this also ensure that the `io.grakn.client:api` and `io.grakn.core:api artifacts` will have unique names?

Good catch! and the answer is *yes*. Because I actually renamed `io.grakn.client:api` to `io.grakn.client:grakn-client`, and renamed `io.grakn.core:api` to `io.grakn.core:grakn-api` to avoid exactly the situation situation you raised. 😉
