### ISSUE TITLE
Rule with parameter or query on a rule

### ISSUE THREAD

**Issue by andreadegiorgi91** [graknlabs/grakn#5135]
Hello.
I have a scheme with the EntityType "person" and "product" and I have a rule that determines which products each person can buy based on certain conditions. A fragment of this rule is shown below:

```
products-that-a-person-can-buy sub rule,
  when {
$ prod1 isa product;
$ p1 isa person;
...
},
then {
(potentialBuyer: $ p1, canEat: $ prod1) isa purchasable-products;
};
```

Using GRAKN.AI Workbase, the rule output is shown to me by selecting the "purchasable-products" relation.
<a href="https://imgur.com/CzIKtQw"><img src="https://i.imgur.com/CzIKtQw.png" title="source: imgur.com" /></a>
The corresponding query generated by GRAKN.AI Workbase is the following "match $ x isa purchasable-products; get; offset 0; limit 30;".
<a href="https://imgur.com/Xf3urrJ"><img src="https://i.imgur.com/Xf3urrJ.png" title="source: imgur.com" /></a>
The output of the rule corresponds to all the people and all the products that each person can buy. 
<a href="https://imgur.com/si5mTUz"><img src="https://i.imgur.com/si5mTUz.png" title="source: imgur.com" /></a>
Is there a way to write a query (or to modify the previous one) in order to show only the products that a specific person can buy using the rule?

If I modify the rule in the following way I get the products that the person can buy with the name "Andrew".

```
products-that-a-person-can-buy sub rule,
  when {
$ prod1 isa product;
$ p1 isa person;
$ p1 has name "Andrew"
...
},
then {
(potentialBuyer: $ p1, canEat: $ prod1) isa purchasable-products;
};
```
But this is limiting because I could not get the products that a person can buy with another name. Is there a solution?

**Comment by kasper-piskorski** [comment]
You do not have to modify the rule to do that. You can treat `purchasable-products` as any other relation. You can put in other patterns and what have you. So to get your result you can just query:

```
match
$p1 has name "Andrew"
(potentialBuyer: $ p1, canEat: $ prod1) isa purchasable-products;
get;
```

**Comment by andreadegiorgi91** [comment]
Thank you. All clear.
