### ISSUE TITLE
An inferred attribute still exists when rule body conditions are no longer met

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/grakn#5136]
## Description

An attribute _B_ that is inferred based on an attribute _A_ is still incorrectly inferred after attribute _A_ has been deleted.

Deleting the attribute used by the rule means that the rule should no longer be triggered.

## Environment

1. OS (where Grakn server runs): Mac OS 10
2. Grakn version (and platform): Grakn Core 1.5.1
3. Grakn client: console
4. Other environment details: -

## Reproducible Steps

Steps to create the smallest reproducible scenario:

```
define

name sub attribute,
  datatype string;

score sub attribute,
  datatype double;

person sub entity,
  has name,
  has score;

infer-attr sub rule,
when {
  $p isa person, has score $s;
  $s > 0.0;
}, then {
  $p has name "Ganesh";
};
```

```
insert $p isa person, has score 10.0;
commit
match $p isa person, has name $n; get;
# result, as expected: {$p id V20488 isa person; $n "Ganesh" isa name;}
```
deleting the attribute used by the rule means that the rule should no longer be triggered
```
match $p isa person, has score $s; delete $s;
# result: {V20552}
commit
```

## Expected Output

```
match $p isa person, has name $n; get;
```
No results expected for this query since the conditions in the rule are not met.

## Actual Output

```
match $p isa person, has name $n; get;
{$p id V20488 isa person; $n "Ganesh" isa name;}
```
1 result is actually found for this query, as if the name attribute has been persisted.

**Comment by kasper-piskorski** [comment]
Update:
Problem seems inexistent on 1.5.2. Will look into 1.5.1.
