### ISSUE TITLE
Roles should be inferred when not declared in a match query

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#5146]
_This issue was originally posted by @haikalpribadi  on 2018-03-27 14:50_.

Roles should be inferred when not declared in a match query, to improve the performance of read queries and intelligence of write syntax.

**Comment by haikalpribadi** [comment]
Would you know how to implement this, @kasper-piskorski / @flyingsilverfin ?

**Comment by kasper-piskorski** [comment]
It's already being done.
