### ISSUE TITLE
Giving attribute type new super type doesn't update implicit relation to inherit from super type

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/grakn#5148]
## Description

When declaring an existing attribute type, B,  subs another attribute type, A, then the implicit relation @has-B is not rectified to sub @has-A.

## Environment

1. OS (where Grakn server runs): Mac OS 10
2. Grakn version (and platform): Grakn Core 1.5.2
3. Grakn client: console 
4. Other environment details: -

## Reproducible Steps

Steps to create the smallest reproducible scenario:

Create an initial schema with one entity that acts as owner to an attribute:
```
define
first-name sub attribute, datatype string;
person sub entity, has first-name; 

insert $x isa person, has first-name "bill";
commit
```

modify that attribute type by making it sub a parent type:
```
define name sub attribute, datatype string;
commit
define first-name sub name;
commit
```

## Expected Output
```
> match $x isa person, has name $n; get;
```
This query should return `{$x id V16616 isa person; $n "bill" isa first-name;}`

We also expect that `match $x sub thing; get;` will show us:
```
...
{$x type @has-name sub @has-attribute;}
{$x type @has-first-name sub @has-name-attribute;}
```

## Actual Output

Instead,
```
> match $x isa person, has name $n; get;
```
returns nothing. Interrogating the schema we see that:
```
> match $x sub thing; get;
{$x type thing;}
{$x type attribute;}
{$x type relation;}
{$x type entity;}
{$x type name sub attribute;}
{$x type @has-attribute sub relation;}
{$x type person sub entity;}
{$x type first-name sub name;}
{$x type @has-first-name sub @has-attribute;}
```
 
## Additional information

Note that when we don't try to consider ownership, then everything works fine. That is:
```
> match $x isa name; get;
{$x "bill" isa first-name;}
```

Related to #4086

**Comment by alexjpwalker** [comment]
Implicit relations are gone now.
