### ISSUE TITLE
Put (add if absent) behaviour with rules with negation

### ISSUE THREAD

**Issue by kasper-piskorski** [graknlabs/grakn#5164]
## Problem to Solve

Ability to define `PUT` rules - rules that assert facts if they are not present. 

General form:
```
when{
    <some conditions>;
    not { fact;}
},
then{
    fact;
}
```

E.g.:

```
putRule sub rule,
when{
    $x isa person;
    $y isa person;
    not {($x, $y) isa someRelation;};
},
then{
    ($x, $y) isa someRelation;
};
```

Similarly for attributes (attribute defaults can be achieved this way).

## Current Workaround

Manually.

## Proposed Solution

Extending the negation semantics to cater for negation with recursion.

**Comment by flyingsilverfin** [comment]
Still relevant to the future of reasoning!

**Comment by flyingsilverfin** [comment]
We're not planning on supporting in the near future this since it requires essentially data-stratified negation, which is hard to reason about.

**Comment by krishnangovindraj** [comment]
I think the proposal may have been to allow these contradictions in a different type of rule?  i.e. `PUT` rules exist to violate (data-)stratified negation.
We'll have to think about it a bit more (e.g. see whether this causes non-deterministic results), but this might be possible.
I suggest we keep it open.
