### ISSUE TITLE
Compute query not working due to Java 32 bit memory allocation on windows

### ISSUE THREAD

**Issue by cptdagon** [graknlabs/grakn#5177]
## Description
Running any `compute` query returns `Error: UKNOWN: null.` within the grakn console.

The grakn log prints an error stating:
`ERROR org.apache.spark.SparkContext - Error initializing SparkContext.
java.lang.IllegalArgumentException: System memory 259522560 must be at least 471859200. Please increase heap size using the --driver-memory option or spark.driver.memory in Spark configuration.`

The full error log in attached below.
[Server log.txt](https://github.com/graknlabs/grakn/files/3166048/Server.log.txt)
## Environment

1. OS: Windows 10
2. Grakn version : Grakn Core 1.5.1
3. Grakn client: console
4. Java 32 bit:
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) Client VM (build 25.181-b13, mixed mode)

## Reproducible Steps

Windows machine running 32 bit java

Run `compute count;` query

## Expected Output

Returns result

## Actual Output

`Error: UNKNOWN: null. Please check server logs for the stack trace.
All uncommitted data is cleared`

**Comment by marco-scoppetta** [comment]
@cptdagon Thanks for reporting this! Unfortunately we don't support Java 32bit for the time being, please upgrade to 64bit. Let us know if we can help you in the upgrade process, thank you.
