### ISSUE TITLE
queries with "group" do not work

### ISSUE THREAD

**Issue by andreadegiorgi91** [graknlabs/grakn#5182]
Hello. At the following documentation link (https://dev.grakn.ai/docs/query/aggregate-query), in Grouping Answers there is a query that uses the "group" function. If I try to run it on Grakn.AI Workbase the following error is reported:
<a href="https://imgur.com/eXPHEcX"><img src="https://i.imgur.com/eXPHEcX.png" title="source: imgur.com" /></a>
If I try to move "group" after "offset" and "limit" I get this other error:
<a href="https://imgur.com/xT08ZPq"><img src="https://i.imgur.com/xT08ZPq.png" title="source: imgur.com" /></a>
How can I solve it?
PS. Also from the Python Client I am having difficulty with queries that use the "group" function. For example the function get ("x") gives me the following error "TypeError: get () takes 1 positional argument but 2 were given".

**Comment by Irtazaraza** [comment]
Hello,

As for the moment, Workbase only supports match get and compute path queries. 

Group queries will not run on workbase at the moment. Are you able to run them on the console?

Can you send me a bug report on how to reproduce the python client issue you are facing?

**Comment by marco-scoppetta** [comment]
@andreadegiorgi91 as @Irtazaraza said we don't support `group` queries in Workbase for the moment. Please open a dedicated issue here: https://github.com/graknlabs/client-python if you have problems with Python Client.

**Comment by andreadegiorgi91** [comment]
Thank you. As soon as possible I will try on console or in a client and I will let you know if I will encounter problems there too.

**Comment by SaqlainHussainShah** [comment]
Queries not working in grakn workbase
![workbase error](https://user-images.githubusercontent.com/13719933/134661995-fc945b98-3e84-441c-a23b-8e863b502088.png)
