### ISSUE TITLE
HTTP Error in docker container

### ISSUE THREAD

**Issue by dcalano** [graknlabs/grakn#5185]
Grakn docker container is returning http errors
https://imgur.com/a/XiZCbj8

**Comment by vmax** [comment]
@dcalano could you outline the connection method you are using and the command you're using to bootup the container? Grakn only responds to gRPC requests at port 48555 (e.g. sent via `grakn console` session or one of client drivers)

**Comment by marco-scoppetta** [comment]
AS @vmax said you should only use gRPC connections to talk to Grakn. I see that you're trying to use an HTTP1.1 request which won't work. I am going to close this issue due to lack of additional information. Re-open it if you have more info.
