### ISSUE TITLE
Defining relations on implicit attribute relations requires two Define statements

### ISSUE THREAD

**Issue by flyingsilverfin** [graknlabs/grakn#5249]
## Description
Currently (1.5.4) when we want to attach attribtues or relations to impliclt attribute relations, we cannot do so in a single define statement. This is because we lazily define the `@has-attribute` and its subtypes when attributes are defined, so by moving the schema for the implicit relations to a new define we guarantee they already exist.

## Environment
Grakn Core 1.5.4

## Reproducible Steps
Try to define this schema:
```
define
  name sub attribute, datatype long;
  number sub attribute, datatype long;
  @has-name sub @has-attribute, has number;
```

## Expected Output
No error

## Actual Output
```
INVALID_ARGUMENT: GraqlSemanticException-@has-attribute doesn't have an 'isa', a 'sub' or an 'id'. Please check server logs for the stack trace.
```
 
## Additional information
Suspect that this is caused by not having all the ordering requirements in the dependency graph formed by the define statement.

The following works:
```
define
  name sub attribute, datatype long;
  number sub attribute, datatype long;
define
  @has-name has number;
```

Related to #4086

**Comment by kasper-piskorski** [comment]
It's because implicit relation are created when you specify that a given type can have an attribute - when you use `has`.

**Comment by alexjpwalker** [comment]
No longer applicable because implicit relations have been removed in 1.8
