### ISSUE TITLE
Calling grakn server first time: 'Unrecognized VM option 'CrashOnOutOfMemoryError'

### ISSUE THREAD

**Issue by achamess** [graknlabs/grakn#5267]
## Description

Installed the latest release of Grakn. Ran `./grakn server start` and the following occurred:

```
Process exited with code '1': 'Unrecognized VM option 'CrashOnOutOfMemoryError'
Did you mean 'OnOutOfMemoryError=<value>'?
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
'
An error has occurred during boot-up. Please run 'grakn server status' or check the logs located under the 'logs' directory.
Process exited with code '1': 'Unrecognized VM option 'CrashOnOutOfMemoryError'
Did you mean 'OnOutOfMemoryError=<value>'?
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

## Environment

1. OS (where Grakn server runs): Mac OSX 10.14.5
2. Grakn version (and platform): Grakn core 1.5.5
3. Grakn client: client-java (?)

**Comment by marco-scoppetta** [comment]
@achamess that's because you probably have an older version of Java 1.8 - we'll try to remove that unrecognised option as it seems it's been added in one of the updates https://www.oracle.com/technetwork/java/javase/8u92-relnotes-2949471.html. 
In the meantime please update your JDK or JRE https://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

**Comment by achamess** [comment]
Hi. I think I have the latest of everything. I'm still getting the same problem.
![Screen Shot 2019-06-29 at 6 45 13 PM](https://user-images.githubusercontent.com/7445362/60390517-13404480-9a9e-11e9-8ab9-bf7188610a76.png)
![Screen Shot 2019-06-29 at 6 44 59 PM](https://user-images.githubusercontent.com/7445362/60390518-14717180-9a9e-11e9-94f9-eb8ef39113cd.png)

**Comment by marco-scoppetta** [comment]
can you post the output of `java -version`?

**Comment by achamess** [comment]
```
(base) Alex-Macbook-2:~ alex$ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
```

**Comment by marco-scoppetta** [comment]
You have installed `1.8.0_25`, you need at least `1.8.0_92` and the latest is `1.8.0_212`.
So you just need to uninstall current Java and reinstall a more updated version.

**Comment by achamess** [comment]
Got it. The Java environments on Mac OS are very confusing. I did update earlier, but it wasn’t calling the latest version.
This discussion helped:
https://stackoverflow.com/questions/28779190/set-mac-jdk-version-to-1-8
