### ISSUE TITLE
Split Concept package between client-java and grakn-core

### ISSUE THREAD

**Issue by haikalpribadi** [graknlabs/grakn#5288]
## Problem to Solve

At the moment, the `grakn.core.concept` package that contains interfaces of Grakn Concepts (data model) are implemented by both `@graknlabs_client_java` and `@graknlabs_grakn_core//server`. Both depend on the concept package sitting at `@graknlabs_grakn_core//concept` for concept types, instances, and answers. This creates a circular dependency between `grakn-core` and `client-java` (issue #5272). Meanwhile, `client-python` and `client-nodejs` do not depend on `grakn-core` for the `//concept` package - this architecture is correct. Like `client-python` and `client-nodejs`, `client-java` should just depend on Grakn RPC Protocol, which currently resides in the `grakn-core` repo, but will be moved to its own repository (issue #5273).

## Proposed Solution

First we need to split the implementation of Concept Answers, and implement streaming of explanations at the same time (issue #4545). Then break the synchronisation between Server Concepts and Client Concepts by deleting the Concept interfaces that they share. Significant refactoring of tests will be needed along the way.

**Comment by flyingsilverfin** [comment]
Closed with #5460, issue of streaming explanations still exists, issue #4545
