### ISSUE TITLE
Split Transaction (API) package between client-java and grakn-core

### ISSUE THREAD

**Issue by haikalpribadi** [graknlabs/grakn#5289]
## Problem to Solve

At the moment, the `grakn.core.api` package that contains interfaces of Grakn Session and Transaction, that are implemented by both `@graknlabs_client_java` and `@graknlabs_grakn_core//server`. Both depend on the API package sitting at `@graknlabs_grakn_core//api` for Session, Transaction and Keyspace. This creates a circular dependency between `grakn-core` and `client-java` (issue #5272). Meanwhile, `client-python` and `client-nodejs` do not depend on `grakn-core` for the `//concept` package - this architecture is correct. Like `client-python` and `client-nodejs`, `client-java` should just depend on Grakn RPC Protocol, which currently resides in the `grakn-core` repo, but will be moved to its own repository (issue #5273).

## Proposed Solution

Break the synchronisation between Server API and Client API by deleting the API interfaces that they share. Significant refactoring of tests will be needed along the way.

**Comment by flyingsilverfin** [comment]
Completed with #5460
