### ISSUE TITLE
the choice of Storage

### ISSUE THREAD

**Issue by Haisenbergyy** [graknlabs/grakn#5307]
I want to know if the grakn use janagraph as a storage strategy？ And is there any chance that we can switch the storage strategy?

**Comment by lolski** [comment]
Hi!

Grakn does use Janusgraph under the hood. The storage backend is actually Apache Cassandra. We have no plan on supporting multiple backends since it will mean we have to deal with various nuances which will take a lot of effort.

**Comment by pouledodue** [comment]
@Haisenbergyy what alternative storage do you need?
