### ISSUE TITLE
Atribute can't  play roles at multi places

### ISSUE THREAD

**Issue by shraddhaS28** [graknlabs/grakn#5333]
## Description
I am trying to use migration example given in the documentation, I have a example of pizza. All files I have attached in the query, it can be downloaded and it will be able to reproduce the error.

## Environment

1. OS (where Grakn server runs): Ubuntu 18.10
2. Grakn version (and platform):Grakn Core 1.5.3
3. Grakn client: client-python

## Reproducible Steps
Steps to create the smallest reproducible scenario:
[error_reproducible_files.zip](https://github.com/graknlabs/grakn/files/3395484/error_reproducible_files.zip)

migrate_schema.gql will be loaded the key-space, and after that you just have to run the migrate.py file.(set the file paths for size, pizza and special_pizza files in the code accordingly)

## Expected Output
it should produce queries as written in migrate.py file by taking variables from other files(size, pizza, special)

## Actual Output

it produced queries for size and pizza but for special pizza, it gives following error:

OUTPUT:

(produced queries:)
graql_query: insert $s isa size, has size-name "small";
graql_query: insert $s isa size, has size-name "medium";
graql_query: insert $s isa size, has size-name "large";

Inserted 3 items from [ /home/hfn/Documents/Grakn_pizza/size] into Grakn.

/home/hfn/Documents/Grakn_pizza/pizza
graql_query: match $size isa size, has size-name "small";insert (pizza-sze: $size) isa pizza;
graql_query: match $size isa size, has size-name "medium";insert (pizza-sze: $size) isa pizza;
graql_query: match $size isa size, has size-name "large";insert (pizza-sze: $size) isa pizza;

Inserted 3 items from [ /home/hfn/Documents/Grakn_pizza/pizza] into Grakn.

(error is from here)

/home/hfn/Documents/Grakn_pizza/special_pizza
graql_query: match $spcl_size isa size, has size-name "small";insert (special_pizza_size: $spcl_size) isa special_pizza;
Traceback (most recent call last):
  File "/home/hfn/.local/lib/python3.6/site-packages/grakn/service/Session/TransactionService.py", line 156, in send
    response = next(self._response_iterator)
  File "/home/hfn/.local/lib/python3.6/site-packages/grpc/_channel.py", line 364, in __next__
    return self._next()
  File "/home/hfn/.local/lib/python3.6/site-packages/grpc/_channel.py", line 358, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "InvalidKBException-A structural validation error has occurred. Please correct the [`3`] errors found. 
The type [size] of role player [V81924184] is not allowed to play Role [special_pizza_size] 
The type [size] of role player [V40964184] is not allowed to play Role [special_pizza_size] 
The type [size] of role player [V40964152] is not allowed to play Role [special_pizza_size] 
. Please check server logs for the stack trace."
        debug_error_string = "{"created":"@1563197894.817117881","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"InvalidKBException-A structural validation error has occurred. Please correct the [`3`] errors found. \nThe type [size] of role player [V81924184] is not allowed to play Role [special_pizza_size] \nThe type [size] of role player [V40964184] is not allowed to play Role [special_pizza_size] \nThe type [size] of role player [V40964152] is not allowed to play Role [special_pizza_size] \n. Please check server logs for the stack trace.","grpc_status":3}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hfn/Documents/Grakn_pizza/migrate.py", line 63, in <module>
    pizaa_client_session(inputs=inputs)
  File "/home/hfn/Documents/Grakn_pizza/migrate.py", line 30, in pizaa_client_session
    load_data_into_grakn(input, session)
  File "/home/hfn/Documents/Grakn_pizza/migrate.py", line 21, in load_data_into_grakn
    transaction.commit()
  File "/home/hfn/.local/lib/python3.6/site-packages/grakn/client.py", line 136, in commit
    self._tx_service.commit()
  File "/home/hfn/.local/lib/python3.6/site-packages/grakn/service/Session/TransactionService.py", line 56, in commit
    self._communicator.send(request)
  File "/home/hfn/.local/lib/python3.6/site-packages/grakn/service/Session/TransactionService.py", line 160, in send
    raise GraknError("Server/network error: {0}\n\n generated from request: {1}".format(e, request))
grakn.exception.GraknError.GraknError: Server/network error: <_Rendezvous of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
```
        details = "InvalidKBException-A structural validation error has occurred. Please correct the [`3`] errors found. 
The type [size] of role player [V81924184] is not allowed to play Role [special_pizza_size] 
The type [size] of role player [V40964184] is not allowed to play Role [special_pizza_size] 
The type [size] of role player [V40964152] is not allowed to play Role [special_pizza_size] 
. Please check server logs for the stack trace."
        debug_error_string = "{"created":"@1563197894.817117881","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"InvalidKBException-A structural validation error has occurred. Please correct the [`3`] errors found. \nThe type [size] of role player [V81924184] is not allowed to play Role [special_pizza_size] \nThe type [size] of role player [V40964184] is not allowed to play Role [special_pizza_size] \nThe type [size] of role player [V40964152] is not allowed to play Role [special_pizza_size] \n. Please check server logs for the stack trace.","grpc_status":3}"
```
>

 generated from request: commit_req {
}
 
## Additional information

any attribute can play multiple role but it's giving error like size can not be used with both pizza and special pizza.

EDIT:
this is the schema file

[test_schema.zip](https://github.com/graknlabs/grakn/files/3396502/test_schema.zip)

**Comment by kasper-piskorski** [comment]
Your error suggests that you didn't allow `size` to play the role `special_pizza_size`. Also, the schema in your attached file is blank so it's hard to point to specific line.

**Comment by shraddhaS28** [comment]
> Your error suggests that you didn't allow `size` to play the role `special_pizza_size`. Also, the schema in your attached file is blank so it's hard to point to specific line.

how can I allow the size?, schema I have written as per documentation and it's working fine
![Screenshot from 2019-07-16 15-20-43](https://user-images.githubusercontent.com/42804712/61285032-c5d21000-a7dd-11e9-9745-004cea8a8696.png)
(screenshot of the documentation)

I have updated the schema file in the last of the query, you can check it.

**Comment by kasper-piskorski** [comment]
Let's get over what's actually happening in the relevant part of the schema
```
size sub entity,
        has size-name,
        plays pizza-sze;

    pizza sub relation,
        relates pizza-sze;

    special_pizza sub pizza,
        relates special_pizza_size as pizza-sze;
```
We start with the `size`. From the schema we can see that it can have a `size-name` attribute and play the role of `pizza-sze`.

Now we turn our attention to the relations. We define a base `pizza` relation with a `pizza-sze` role:

```
    pizza sub relation,
        relates pizza-sze;
```

which we then specialise:

```
    special_pizza sub pizza,
        relates special_pizza_size as pizza-sze;
```
Consequently, `special_pizza` is a specialised (subclassed) `pizza` relation with a `special_pizza_size` role specialising the `pizza-sze` role. Now if we go back to our `size` entity, we can clearly see that it can only play the `pizza-sze` base role and not the specialised `special_pizza_size` role. To remedy that, we need to modify our entity definition the following way:

```
size sub entity,
        has size-name,
        plays pizza-sze,
        plays special_pizza_size;
```


Hope that clarifies things for you.

**Comment by shraddhaS28** [comment]
ya, that we can use but then what is the use of the following relation:
`special_pizza sub pizza`

we have to mention all attributes like price, name, topping in both pizza and special pizza, is there no way that we can write all these in pizza entity and all other entities using the same attributes can use **`special_pizza sub pizza`**  this relation to retrieve those attributes.

**Comment by kasper-piskorski** [comment]
There is, both `has` and `plays` properties are inherited. If you have:

```
someEntity sub entity,
    has name,
    plays someRole;
```
Then if you define `subEntity sub someEntity` it will already be able to have names attached and play `someRole`s.

**Comment by shraddhaS28** [comment]
Okay, got it!
Thank You for your help..
I'll discuss further in case of any confusion

**Comment by kasper-piskorski** [comment]
Cool! Closing then.
