### ISSUE TITLE
Loading huge dataset

### ISSUE THREAD

**Issue by shanghai-Jerry** [graknlabs/grakn#5384]
## Description

Using grakn console loads huge data, but GC overhead.

## Environment

1. OS (where Grakn server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
    Ubuntu 16.4
2. Grakn version (and platform): { e.g. Grakn Core 1.4, or Grakn KGMS 1.4.3 on Google Cloud }
    Grakn Core 1.5.7
3. Grakn client: { e.g. client-java, client-python, client-nodejs, or console }
    console
4. Other environment details:
   Nope

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1.  Run ./grakn console --keyspace company --file /data/grakn/company/company_name_insert.gql
## Expected Output
 success

## Actual Output
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at graql.lang.statement.Statement.<init>(Statement.java:74)
        ....

**Comment by shanghai-Jerry** [comment]
@Makopo  

match
  $customer isa person, has first-name $cna;
  $company isa company, has name "Telecom";
  $contract (customer: $customer, provider: $company) isa contract;
  $target isa person, has phone-number "+86 921 547 9004",  has first-name $tna;
  $call (caller: $customer, callee: $target) isa call, has started-at $started-at;
  $min-date == 2018-09-14T17:18:49; $started-at > $min-date;
get $customer, $company, $contract,$call, $target, $cna, $tna;

if $target person doesn't have first-name attribute in graph, no data return.
but there are many calls between $customer  and $target person with this match query condition above.

Wish your quick reply.

Thanks very much

**Comment by shanghai-Jerry** [comment]
After loading huge data, run with a query has error like this:

Caused by: org.janusgraph.diskstorage.TemporaryBackendException: Could not successfully complete backend operation due to repeated temporary exceptions after PT10S

**Comment by flyingsilverfin** [comment]
Hi - these all sound like interesting errors! It looks to me like these are all separate or could be considered different errors. Would you mind filing three issues for this separately:
* one for the GC error (this original post) with the full stacktrace you encountered
* one with the incomplete match query (second comment) and how you reproduce this case (is it our phone calls example or some other data set?) 
* one with more information on the data loading (how many items? is this using the node client? Is there anything happening in parallel? how many concepts are being inserted in a single insert?

It will be much easier to debug separately! Thank you!

**Comment by marco-scoppetta** [comment]
Closing this as we are going to refer to the separate issues.
