### ISSUE TITLE
Add limit to delete queries

### ISSUE THREAD

**Issue by marco-scoppetta** [graknlabs/grakn#5388]
## Problem to Solve

Delete queries cannot be limited. 
If there are too many instances to be deleted we currently get exception from Janus.

something like `match $x isa marriage; delete; limit 20;`

**Comment by lolski** [comment]
If you have 20 instances of `person` and you try to delete one of them by using `limit`: `match $p isa person; delete $p; limit 1;` it *will delete all of them*.

This looks like a high priority ticket for us.

**Comment by flyingsilverfin** [comment]
Fixed as of https://github.com/graknlabs/graql/pull/78, will be tested in a PR on Grakn next
