### ISSUE TITLE
GC overhead limit exceeded when loading a file via console

### ISSUE THREAD

**Issue by shanghai-Jerry** [graknlabs/grakn#5400]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

Using grakn console loads huge data, but GC overhead.

## Environment

1. OS (where Grakn server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
    Ubuntu 16.4
2. Grakn version (and platform): { e.g. Grakn Core 1.4, or Grakn KGMS 1.4.3 on Google Cloud }
    Grakn Core 1.5.7
3. Grakn client: { e.g. client-java, client-python, client-nodejs, or console }
    console
4. Other environment details:
   Nope

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1.  Run ./grakn console --keyspace company --file /data/grakn/company/company_name_insert.gql
## Expected Output
 success

## Actual Output
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at graql.lang.statement.Statement.<init>(Statement.java:74)
        ....

**Comment by marco-scoppetta** [comment]
@shanghai-Jerry without your file it's really hard to guess your problem, is it something you can share with us?

**Comment by marco-scoppetta** [comment]
anyway @shanghai-Jerry you cannot load big files using `console -f` as it uses only 1 big transaction.
Use one of our clients to build an importing script that splits the data in multiple transactions please.
Keeping 1 transaction open for a long time executing many insert statement should be always avoided, transactions should be short-lived and only session can be long-lived
