### ISSUE TITLE
Redefining attribute leads to multiple instances

### ISSUE THREAD

**Issue by flyingsilverfin** [graknlabs/grakn#5411]
## Description
Attributes are duplicated when re-defining attribute schema elements with the same name.

## Environment

1. OS (where Grakn server runs): Any
2. Grakn version (and platform): Core 1.5.8
3. Grakn client: Console
4. Other environment details:

## Reproducible Steps
1. Run 
```define unit sub attribute, datatype string;
define mass sub attribute, has unit, datatype double;
define modelName sub attribute, datatype string;

define product sub entity, abstract;
define cellphone sub product, has mass, has modelName;

insert
   $y 10 isa mass, has unit "kg";
   $x isa cellphone, has modelName "Cat Phone", has mass $y;
```
2. Repeat the same queries above
3. Query: `match $x isa thing; get;`

## Expected Output
Expect exactly 1 instance of the unit `kg` and the mass `10`.

## Actual Output
We end up with 1 unit `kg`, and two instances of the mass `10`.
 
## Additional information
Found via stackoverflow:
https://stackoverflow.com/questions/57857141/are-attribute-instances-in-grakn-ai-supposed-to-be-singleton

Initial suspicion is to the conversion from label to label ID we perform under the hood!

**Comment by alexjpwalker** [comment]
Fixed in https://github.com/graknlabs/grakn/pull/5801. A single instance of mass is now created.
