### ISSUE TITLE
Track keyspace statististics for meta types: entity, relation, and attribute

### ISSUE THREAD

**Issue by kasper-piskorski** [graknlabs/grakn#5421]
## Context
Currently we are storing keyspace statistics in the form of a property on type vertices. These are accessed via `KeyspaceStatistics`. We use them to optimise query planning and compute basic statistics of the graph.

## Current Workaround
Currently we count the number of instances for all non-meta types and meta `thing` type. `Thing` is the only meta type for which we store instance information. As a result computing counts in `entity`, `relation` or `attribute` require doing full computation whereas `compute count;` or `compute count in thing;` will return immediately utilising the keyspace statistics.
## Proposed Solution

Track instance counts for `entity`, `attribute` and `relation` similarly to `thing`.

**Comment by flyingsilverfin** [comment]
Solved by #5477
