### ISSUE TITLE
Grakn does not seem to run with OpenJDK on Windows

### ISSUE THREAD

**Issue by polyvertex** [graknlabs/grakn#5429]
## Description

Grakn is advertised to be [compliant with OpenJDK](https://dev.grakn.ai/docs/running-grakn/install-and-run#system-requirements) but it fails to start with the latest releases.

## Environment

* Grakn Core 1.5.8 from `grakn-core-all-windows-1.5.8.zip`, extracted as-is
* OpenJDK 12.0.2
* Windows 10

## Reproducible Steps

In a console window:

```
D:\grakn>grakn.bat server start
An error has occurred during boot-up. Please run 'grakn server status' or check the logs located under the 'logs' directory.
Unsupported Java version [12] found. Grakn needs Java 1.8 in order to run.

D:\grakn>java --version
openjdk 12.0.2 2019-07-16
OpenJDK Runtime Environment (build 12.0.2+10)
OpenJDK 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)
```

**Comment by lolski** [comment]
```
... The only requirement is Java 8 which can be downloaded from OpenJDK or Oracle Java.
```

Currently, Grakn only supports "Java 8" and you are using Java 12.

**Comment by polyvertex** [comment]
I misread this requirement as "Java 8+". Sorry for the noise then.
