### ISSUE TITLE
The following query is slow, ie., takes 15 minutes, even on a small dataset

### ISSUE THREAD

**Issue by lolski** [graknlabs/grakn#5431]
## Description

I encountered an issue where a single query may take up to 15 minutes to complete on a small dataset.

## Environment

1. OS (where Grakn server runs): Mac OS X (with 8 cores), Linux (CircleCI machine)
2. Grakn version (and platform): 1.5.9-SNAPSHOT (commit `546dd2e5028e1fcc69e35e68d18b942e142c0ab8`)
3. Grakn client: console
4. Other environment details: N/A

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Checkout the right commit: `git checkout 546dd2e5028e1fcc69e35e68d18b942e142c0ab8`
2. Build: `bazel build //:assemble-linux-targz`
3. Download [db.zip](https://github.com/graknlabs/grakn/files/3625497/db.zip)
4. Unzip the db folder and place it within `grakn-core-all-linux/server`
5. Start Grakn
6. Login to the keyspace: `grakn console -k phone_calls`
7. Run the query: 
```
match 
$suspect isa person, 
    has city "London", 
    has age > 50; 
$company isa company, 
    has name "Telecom"; 
(customer: $suspect, provider: $company) isa contract; 
$pattern-callee isa person, 
    has age < 20; 
(caller: $suspect, callee: $pattern-callee) isa call, 
    has started-at $pattern-call-date; 
$target isa person, has phone-number $phone-number, 
    has is-customer false; 
(caller: $suspect, callee: $target) isa call, 
    has started-at $target-call-date; 
$target-call-date > $pattern-call-date; 
get $phone-number;
```

## Expected Output

The query should terminate quickly

## Actual Output

The query can take up to 15 minutes in total.
 
## Additional information

FYI, the issue was first discovered when I was developing [this PR](https://github.com/graknlabs/docs/pull/212) in the following test: https://circleci.com/gh/graknlabs/docs/7260.

**Comment by sorsaffari** [comment]
@lolski @kasper-piskorski 
according to [this CI run](https://circleci.com/gh/graknlabs/docs/7293?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification), the following query (of the same dataset as mentioned in the OP) is also taking longer than 700 seconds to return:

```
 match 
  $target isa person, has phone-number "+48 894 777 5173";
  $company isa company, has name "Telecom";
  $customer-a isa person, has phone-number $phone-number-a;
  (customer: $customer-a, provider: $company) isa contract;
  (caller: $customer-a, callee: $target) isa call;
  $customer-b isa person, has phone-number $phone-number-b;
  (customer: $customer-b, provider: $company) isa contract;
  (caller: $customer-b, callee: $target) isa call;
  (caller: $customer-a, callee: $customer-b) isa call;
get $phone-number-a, $phone-number-b;
```
