### ISSUE TITLE
Concurrently inserting things with keys leads to duplicate things

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/grakn#5481]
## Description

When concurrent Grakn transactions are being used, it is possible to insert two instances with the same type and key, which should be prohibited.

## Environment

1. OS (where Grakn server runs): Mac OS 10
2. Grakn version (and platform): Grakn Core 1.5.9
3. Grakn client: client-python

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. First load this schema into a keyspace called `key_collision`:
```
define 

name sub attribute, 
    datatype string;

person sub entity, 
    key name;
```

2. Then run the attached Python script. This script starts 2 threads, both of which open a transaction, and make the query `insert $x isa person, has name "Marco";`. They each wait for the other thread to make this query, and then they both `commit`.

3. Now open Grakn console `./grakn console -k key_collision` and make the query `match $x isa person, has name "Marco"; get;` and see that more than one person has been added, despite `name` being a key.

## Expected Output

We should have received an error regarding the duplicate key for the second transaction to be committed.

## Actual Output

We receive no such error, and we see:
```
key_collision> match $x isa person, has name "Marco"; get;
{$x id V8240 isa person;}
{$x id V12336 isa person;}
```
[key_collision.py.zip](https://github.com/graknlabs/grakn/files/3784729/key_collision.py.zip)

**Comment by marco-scoppetta** [comment]
Note for future, just add this test to `AttributeUniquenessIT`:

```
   @Test
    public void concurrentInsertionOfSameKey_onlyOneIsAccepted(){
        Transaction tx = session.writeTransaction();
        tx.execute(Graql.parse("define \n" +
                "name sub attribute, \n" +
                "    datatype string;\n" +
                "person sub entity, \n" +
                "    key name;").asDefine());
        tx.commit();

        //Try to insert 2 persons with same name, this should throw exception probably
        insertConcurrently(Graql.parse("insert $x isa person, has name \"Marco\";").asInsert(), 2);


        tx = session.readTransaction();
        List<ConceptMap> execute = tx.execute(Graql.parse("match $x isa person, has name \"Marco\"; get;").asGet());
        assertEquals(1, execute.size());
    }
```

**Comment by marco-scoppetta** [comment]
NOTE: add test that tries to link same attribute key to entities in 2 concurrent transactions (as test above) but having the attribute already existing in the db (not creating a new one like in the test in comment above)
