### ISSUE TITLE
Cannot connect to Grakn when installing using apt-get

### ISSUE THREAD

**Issue by alelasantillan** [graknlabs/grakn#5482]
{
grakn server status
Storage: RUNNING
Grakn Core Server: RUNNING
root@42fa745f51a1:~# grakn console
Unable to create connection to Grakn instance at localhost:48555
Cause: io.grpc.StatusRuntimeException
UNKNOWN: Could not open global configuration. Please check server logs for the stack trace.
 }

{UBUNTU 18.04 docker }

1. OS (where Grakn server runs): {  Ubuntu 18.04 on docker }
2. Grakn version (and platform): {1.5.9 }
3. Grakn client: { grakn console }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { apt-get install grakn-core-all }
2. { grakn server start}
3. { grakn server status }
4. { grakn console }

## Expected Output

{ someting different than  Unable to create connection to Grakn instance at localhost:48555}

## Actual Output

{Unable to create connection to Grakn instance at localhost:48555
Cause: io.grpc.StatusRuntimeException
UNKNOWN: Could not open global configuration. Please check server logs for the stack trace.
 }
 
## Additional information

{ logs file
[cassandra.log](https://github.com/graknlabs/grakn/files/3784839/cassandra.log)
[grakn.log](https://github.com/graknlabs/grakn/files/3784841/grakn.log)
 }

**Comment by alelasantillan** [comment]
I've tried the same setup in another docker identical to the former one, but in another machine, without any firewall and I was not able to reproduce the error. I suspect that is a firewall related matter, but don't know how it could happen.

**Comment by marco-scoppetta** [comment]
Closing as not reproducible, re-open if it happens again

**Comment by suciokhan** [comment]
I receive the same error when I set cassandra.yaml's **listen_address** and **rpc_address** to **127.0.0.1** when trying to run Grakn 1.8.0 or 1.8.3 (download file version) on a bare-metal Ubuntu 20.04 system.
