### ISSUE TITLE
Negation Explanations incorrect

### ISSUE THREAD

**Issue by flyingsilverfin** [graknlabs/grakn#5488]
## Description
Explanations involving rules and queries with negation are not correct. We can see this when `pattern`s are missing the negation term, and are also missing variable IDs that should have been substituted in.

## Environment
Grakn Core 1.6.0

## Reproducible Steps
1. Run `NegationIT.allRecipesContainingAvailableIngredients`
2. Breakpoint after all answers have been retrieved
3. [A] Examine explanations for `recipesWithAllIngredientsAvailable` concept maps
4. [B] Examine explanations for `recipesWithUnavailableIngredients` concept maps

## Expected Output
[A] The Explanations be of type `RuleExplanation` or `JoinExplanation`, and have patterns matching the original query including the negation.

[B] The Patterns of the bottom of the nested Explanation tree contain IDs for all variables mentioned in the query pattern instead of only some of them.

## Actual Output
[A]
```
recipesWithAllIngredientsAvailable = {ArrayList@10672}  size = 3
 0 = {ConceptMap@10712} "[$r/V24816]"
  map = {Collections$UnmodifiableMap@10718}  size = 1
  explanation = {LookupExplanation@10719} 
  pattern = {Conjunction@10720} "{ { $r isa recipe; $r id V24816; }; { { $i isa available-ingredient; }; { $_ (role: $i, role: $r) isa requires; $r id V24816; }; }; };"
...
```

This indicates that explanation is a LookupExplanation (Incorrect), and that the pattern does not contain any negations, when it should given the rule definitions in `recipeTest.gql`

[B]
 ```
recipesWithUnavailableIngredients = {ArrayList@10669}  size = 2
 0 = {ConceptMap@10750} "[$r/V49272]"
  map = {Collections$UnmodifiableMap@10754}  size = 1
  explanation = {RuleExplanation@10755} 
   ruleId = {ConceptId@10762} "V61640"
   answers = {Collections$UnmodifiableRandomAccessList@10785}  size = 1
    0 = {ConceptMap@10787} "[$r/V49272]"
     map = {Collections$UnmodifiableMap@10789}  size = 1
     explanation = {LookupExplanation@10790} 
     pattern = {Conjunction@10770} "{ $r isa recipe; (requiring-recipe: $r, role: $i) isa requires; };"
```

The bottom most pattern should contain IDs for `$r` and `$i`, both are absent. This should also contain a negation pattern.

## Additional information
* Likely to be incorrect before patterns were moved from Explanations to ConceptMap #5483

**Comment by jmsfltchr** [comment]
Solved by https://github.com/graknlabs/grakn/pull/5723
