### ISSUE TITLE
Ability to store milliseconds in date-time attribute

### ISSUE THREAD

**Issue by haikalpribadi** [graknlabs/grakn#5533]
## Problem to Solve

At the moment, we are not able to store date-time value at the granularity of milliseconds. Our date-time format only allows us to save time data down to seconds: `yyyy-MM-ddTHH:mm:ss`.

## Current Workaround

One would have to store the milliseconds' data in a separate attribute of type `long`.

## Proposed Solution

Our internal representation of date-time attributes are already a `long` value of time since Epoch in milliseconds. All we need to do now is to extend Graql's date-time data type to be able to represent milliseconds. The format of we can define it to be in Graql can be the following:
```
yyyy-MM-ddTHH:mm:ss.SSS
```

## Additional Information

This feature will require Graql to have implemented the change in its grammar (issue https://github.com/graknlabs/graql/issues/93).

**Comment by flyingsilverfin** [comment]
Turns out we already have this functionality!
