### ISSUE TITLE
Deleting Attribute should delete implicit Relation and Roles

### ISSUE THREAD

**Issue by flyingsilverfin** [graknlabs/grakn#5613]
## Description
Deleting an attribute type should also remove the corresponding implicit attribute ownership. For example, deleting `name sub attribute` should also delete `@has-name` and the roles `@has-name-value` and `@has-name-owner`.

## Environment

1. OS (where Grakn server runs): Mac OS 12
2. Grakn version (and platform): Grakn Core 1.6.2
3. Grakn client: client-java
4. Other environment details:

## Reproducible Steps
In console:
1. `define person sub entity, has name; name sub attribute, datatype string;`
2. `commit`
3. `undefine name;`
4. commit
5. `match $x sub relation; get;`

## Expected Output
Just the meta relation `relation`

## Actual Output
Still includes `@has-name`
 
## Additional information
The roles `@has-name-owner` and `@has-name-value` still exist. Further, we get an answer for this query;
`match $x plays @has-name-value; get;`, which should return 0 answers.

**Comment by alexjpwalker** [comment]
Implicit relations/roles are now gone.
