### ISSUE TITLE
Warn or throw when a rule contains disconnected variables

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/grakn#5660]
## Problem to Solve

As a user, it is very easy to make a mistake when writing a rule. It's very common to have two variables that are intended to be the same, but which are not. This leads to disconnectedness of the variables in the rule body.

## Current Workaround

Be vigilant!

## Proposed Solution

Either: 
- disallow disconnected variables in a rule altogether, since actually needing this is rare
- warn the user at rule define-time that the rule contains disconnected variables

**Comment by alexjpwalker** [comment]
Raised https://github.com/graknlabs/grakn/issues/5792 which is a superset of this issue.
