### ISSUE TITLE
Migrate Graql (non-reasoner) integration tests into behaviour test

### ISSUE THREAD

**Issue by haikalpribadi** [graknlabs/grakn#5663]
## Problem to Solve

We want to move to a behaviour-driven test, and make refactoring Grakn much easier.

## Proposed Solution

Migrate all Graql (non-reasoner) integration tests as "Scenarios" in the `@graknlabs_verification//behaviour` test suite.

**Comment by flyingsilverfin** [comment]
Superceded by #5719
