### ISSUE TITLE
Transform Graql reasoner integration tests into behaviour test

### ISSUE THREAD

**Issue by haikalpribadi** [graknlabs/grakn#5664]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

We want to move to a behaviour-driven test, and make refactoring Grakn much easier.

## Proposed Solution

Transform Graql reasoner integration tests into behaviour driven test, and place them in `@graknlabs_verification//behaviour` test package.

**Comment by flyingsilverfin** [comment]
Superceded by #5721
