### ISSUE TITLE
Key uniquness non verified

### ISSUE THREAD

**Issue by EnxEng** [graknlabs/grakn#5705]
## Description

The key keyword followed by the attribute’s label does not force to assign a unique attribute to an entity.

## Environment

1. Ubuntu
2. Grakn Core 1.5.9,   Grakn Core 1.6.2, or  Grakn Core 1.7.1
3. console or client-python

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Load basic schema:
```
define

email sub attribute,
	datatype string;

person sub entity,
    key email;
```

2. Insert more than once the same entity
```
insert $x isa person, has email "mail";
```
3. See the duplicate email with another id inserted, e.g. $x/V1234
and count two "mail" node

## Expected Output
'key' should not permit the second insertion.

## Actual Output

You can save multiple entities, with the same 'key' value
End every time you insert the console respond as
{$x id V123456789 isa person;}
every time changing the V123456789 numbers

## Additional information

It is the same error as reported in:
[discuss.grakn](https://discuss.grakn.ai/t/what-does-key-actually-do/786)
 And differs from the 
[grakn guide](https://dev.grakn.ai/docs/schema/concepts#assign-an-attribute-to-an-entity-as-a-unique-identifier)

**Comment by flyingsilverfin** [comment]
Hi - key uniqueness is enforced at `commit` time... what happens when you follow the insert statements with a commit?

**Comment by EnxEng** [comment]
Ok, thank you very much.
It works at commit time!
