### ISSUE TITLE
Migrate Graql Native Integration Tests to BDD

### ISSUE THREAD

**Issue by flyingsilverfin** [graknlabs/grakn#5719]
## Problem to Solve
Currently, there are quite a few tests in Grakn Core that are "Graql", ie language tests - these should be moved to BDD and integrated into the `Axiomatic` tests - basic language behaviour tests found at https://github.com/graknlabs/verification/tree/master/behaviour/graql/language.

## Proposed Solution
Tests to migrate from Grakn Core to BDD and implemented:

* `graql/executor`
  * `DirectIsaIT.whenInsertIsaExplicit_InsertsADirectInstanceOfAType`
  * `DirectSubIT.directSubReturnsOnlyItselfAndDirectChildTypesWithoutReasoning`
  * `DirectSubIT.directSubReturnsOnlyItselfAndDirectChildTypesWithReasoning`
==> can be merged into Match BDD

* `graql/query/pattern`
  * `PatternIT.whenValueComparisonIsUnbound_weThrow`
  * `PatternIT.whenStatementDoesntHaveProperties_weThrow`
  * `PatternIT.whenMatchingWithValueInequality_resultsAreFilteredCorrectly`
==> can be merged into Match BDD

* `graql/query/GraqlDefineIT`
  * ALL tests migratable to Define BDD

* `graql/query/GraqlDeleteIT`
  * `afterDeletingAllInstances_TheTypeCanBeUndefined` -> Undefine BDD
  * ALL others can be moved to Delete BDD

* `graql/query/GraqlGetIT`
  * ALL to Get BDD

* `graql/query/GraqlInsertIT`
  * ALL to Insert BDD

* `graql/query/GraqlUndefineIT``
  * ALL to Undefine BDD

* `graql/query/NumberCastingIT`
  * ALL to Attribute Query BDD (might find better name that doesn't clash with Concept API)

* `graql/query/QueryErrorIT`
  * ALL to Error BDD

* `graql/query/QueryValidityIT`
  * Tests that are not designed to throw, merge into Match BDD
  * Tests that are designed to throw, merge into QueryError BDD

Across all of these, it will be interesting to see how to run the Write queries, then commit, and then roll back the state.
May be unucessary in BDD, as we should load a new keyspace or 
Also, many depend on MovieGraph, which may need to be shortened/adapted for BDD!

**Comment by flyingsilverfin** [comment]
Also to migrate are probably the majority of `test/integration/concept`

**Comment by alexjpwalker** [comment]
The migration is complete
