### ISSUE TITLE
Behaviour of Explanations and QueryPattern incl for Disjunctions and Negations

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/grakn#5724]
## Problem to Solve

Currently explanations and patterns show some inconsistencies that we would like to correct.

Besides anything that is clearly a bug.

We have considered what the remit of explanations should be. There are two obvious options:
1. A storyline which looks as the user would expect that shows how their query was dissected and which rules were applied to find their answer
2. An actual representation of how reasoner resolves their query

We sided with option 1 initially. In this case it seems ideal to use user-given variables throughout wherever possible, not to use concept ids in the returned patterns (since the user has them anyway in the associated `ConceptMap`), and to show the user negations and disjunctions (incl. all clauses) in the patterns provided.

However, this is showing them something that doesn't exist. The reasoner normalises the user's query into `negation disjunctive normal form` in order to process it, and so the user's query takes a different form from the get-go.

When the reasoner tries to fulfil a subgoal, it does so by making an id substitution into the given query, and executing this new pattern. Therefore removing ids from patterns would be additional work done, and seems illogical, inconsistent and therefore inelegant.

Another consequence that arises from this is that ids are substituted into queries for concepts that are inside disjunctive clauses. 

Example:
```
match $com isa company;
{$com has name $n1; $n1 "the-company";}
or {$com has name $n2; $n2 "another-company";}; get;
```

In this case during normalisation the reasoner will normalise this query into two:
```
match $com isa company; $com has name $n1; $n1 "the-company"; get;
```
```
match $com isa company; $com has name $n2; $n2 "another-company"; get;
```
Finding the results of these queries leads to answers that include the `name` variables, `$n1` and `$n2`, both in the answer ConceptMap and in the pattern. These variables are then filtered out of the ConceptMaps for the user's query, since `$n1` and `$n2` are variables each scoped to a disjunction's clause. They are **not** filtered out of the patterns though, which is inconsistent.

Overall we arrive at the conclusion that behaviour option 1 is not viable, which leaves us with option 2.

## Current Workaround

We can work around this by accepting that there is an inconsistency in how disjunctions (and negations but it's not so bad) are returned in patterns vs ConceptMaps.

## Proposed Solution

There are two viable solutions we can see:

1. Return all variables in a ConceptMap, including those inside the disjunction clauses. This has a serious flaw - if there is more than one disjunctive statement then the inner variables can clash. This also has wide ramifications as it means a significant change in the answers returned from Grakn.
2. Introduce additional explanation type(s), ones to explain disjunctions and negations. These can have ConceptMaps that are isolated from other disjunction/negation blocks, so we can return the scoped variables freely, and they can correspond in full with the patterns given alongside.

Solution 2 seems the clearly more favourable.

**Comment by flyingsilverfin** [comment]
@jmsfltchr  this has been worked on and is mostly solved now?

**Comment by jmsfltchr** [comment]
Yes that's right, option 2 has been implemented in https://github.com/graknlabs/grakn/pull/5723, so this is solved
