### ISSUE TITLE
Inconsistent shared attribute display - need help identifying unique attributes

### ISSUE THREAD

**Issue by Qbbz** [graknlabs/grakn#5759]
EDIT: In a post below I've presented shorter and more focused version of the problem description, after trying to troubleshoot the issue myself. It could be more helpful than this runaway description ;) 

## Description

In my schema I am making use of shared attribute 'depth' that is being used between different entities. On top of that, there's an entity 'SSP-vec' that has an attribute 'ssp-value'. Each 'ssp-value' is being assigned a depth. In my query I want to retrieve SSP_values only at meaningful depths, namely the depths appearing as attributes for other entities, instead of the whole range off 'ssp-value' - 'depth' pairs (35 pairs or so).

```
SSP-vec sub entity,
		has season,
		has location,
		has SSP_value,
		has depth,
		plays define_SSP,
		plays find_channel;

SSP_value sub attribute, 
		datatype double,
		has depth;
```

Previously, I've been working with a slightly outdated Grakn Core 1.5.9 and corresponding Python client. This setup was giving me exactly the output that I wanted (at least I thought so looking at the Workbase) - the depth attributes were shared between SSP-vec and other entities, like so:
![query_grakn159](https://user-images.githubusercontent.com/25904278/84421113-5cd85f80-ac1b-11ea-84af-bdba916b2eb9.JPG)

However, after moving to Grakn Core 1.6.2 (also checked 1.7.1 with the same result), the shared depth property is being lost, for some, but not all (!) results, while querying in Workbase.
![query_grakn162](https://user-images.githubusercontent.com/25904278/84421289-a0cb6480-ac1b-11ea-86bc-ee8d9a6fdd10.JPG)

As requested I have tested the query in console. There are 126 matches in each file. They differ by combination of variables $x, $y and attributes $a, $b. It seems that all three core versions produce the same output, only IDs for entity vary:
[grakn15-output.txt](https://github.com/graknlabs/grakn/files/4766370/grakn15-output.txt)
[grakn16-output.txt](https://github.com/graknlabs/grakn/files/4766371/grakn16-output.txt)
[grakn17-output.txt](https://github.com/graknlabs/grakn/files/4766373/grakn17-output.txt)

**I need help identifying if these disconnected depth attributes are actually unique, because the console output doesn't seem to assign any ID to a depth attribute, other than value.** To make it easier to read, I've run these outputs through np.unique(), which gives a summary of unique variables, the same for all 3 output files (beside the entities ID). The results:
[grakn-unique-output.txt](https://github.com/graknlabs/grakn/files/4766401/grakn-unique-output.txt)

On a final note, I would like to ask you if that's a usual and expected behaviour that the query results in 126 separate results, because of these combinations of $x, $y and attributes $a, $b. I would like to use this schema with KGCN. Do you think that my query\schema should be re-formulated to avoid producing multiple versions of the same graph? Is this a problem for KGCN or can the results be consolidated into a single output? 

**Explanation of the variables:**
$x can take 3 different entity values with corresponding attributes $a, where $a is always 2 attributes length & depth or length & slope: 
```
bottom-segment-1 sub entity,
		has length,
		has depth,
		plays define_bathy,
		plays bathy_src_position;

	bottom-segment-2 sub entity,
		has length,
		has depth,
		plays define_bathy;

	wedge-segment sub entity,
		has length,
		has slope,
		plays define_bathy;

```
$y can take 3 different entity values with corresponding attributes $b, where $b can be  a set of 1, 2 or 5 attributes: 
```
	sonic-layer sub entity,
		has SLD_avgrad,
		has depth,
		plays channel_exists;

	deep-channel sub entity,
		has depth, #3 depths: DC_ax, DC_top, DC_bot
		has DC_avgrad_top,
		has DC_avgrad_bot,
		plays channel_exists;
		
	duct-exists sub entity,
		has number_of_ducts, 
		plays channel_count;

```
**Corresponding relations:**
```
	bathymetry sub relation,
		relates defined_by_bathy,
		relates define_bathy,
		has bottom_type;

	SSP-channel sub relation,
		relates find_channel,
		relates channel_exists,
		relates channel_count;	
```
For each scenario there's at least one bathymetry relation with a bottom-segment-1, or 3 bathymetry relations with bottom-segment-1, bottom-segment-2 and wedge-segment.

For each scenario there's always a duct-exists entity and thus at least 1 SSP-channel relation. It works as a dummy count, to make the query consistent between 'types' of scenarios. In addition to that there is possibly a sonic-layer and\or deep channel (so 0, 1 or 2 additional SSP-channel relations). Also notice the different role for $y plays channel_exists\plays channel_count. 

## Environment

1. OS (where Grakn server runs): Windows 10
2. Grakn version (and platform): Grakn Core 1.5.9/1.6.2/1.7.1
3. Grakn client: client-python
4. Other environment details:

## Reproducible Steps

The query:
```
match
$scn isa sound-propagation-scenario, has scenario_id $sid;
$ray isa ray-input, has num_rays $nray; 
$src isa source, has depth $ds; 
$bs1 isa bottom-segment-1, has depth $dstart, has length $l;
$ssp isa SSP-vec, has location $loc, has season $ses, has SSP_value $sspval, has depth $dsspmax;

$conv($scn, $ray) isa convergence;
$srcp($scn, $src, $bs1) isa src-position;
$bathy($scn, $x) isa bathymetry, has bottom_type $bt;
$x has attribute $a;
$speed($scn, $ssp) isa sound-speed;
$duct($ssp, $y) isa SSP-channel;
$y has attribute $b;

$sspval has depth $dssp;
{$dssp == $ds;} or {$dssp == $dstart;} or {$dssp == $a;} or {$dssp == $b;} or {$dssp == $dsspmax;};

$sid == 440;

get 
$scn, $sid, $ray, $nray, $conv,
$src, $ds, $srcp, $bs1, $dstart, $l,
$bathy, $x, $bt, $a,
$ssp, $speed, $loc, $ses, $sspval, $dsspmax, $dssp,
$duct, $y, $b;
```

Schema file (saved as txt): 
[ssp_schema_unordered.txt](https://github.com/graknlabs/grakn/files/4766433/ssp_schema_unordered.txt)

**Comment by VladGan** [comment]
@flyingsilverfin comment in discord 
https://discordapp.com/channels/665254494820368395/672562706284412935/720369935942942830

**Comment by Qbbz** [comment]
If you'd like to reproduce this behaviour completely, please see my SSP git repository (https://github.com/Qbbz/SSP) that contains the data and the data migration script. It uses only a fraction of a complete database and shouldn't take more than a few minutes to obtain the same result.

**Comment by Qbbz** [comment]
UPDATE: I've been trying to approach the problem more systematically and at this point I doubt it's a core issue, rather some inconsistency in workbase-core interaction display. **There's no difference in console output between core versions, but the workbase display changes.** Everything's connected for core 1.5.9 and workbase 1.27 but not for 1.6.2 and the same workbase.

I've found out by isolating parts of the schema that these disjunctive patterns of type:
{$a = ...;} or {$a = ...;};
produce a number of outputs, which is a combination of all possible true values for the 'undefined' (under-constrained?) attributes, so in example a query:
```
match $scn has scenario_id 440;
$ssp isa SSP-vec, has location $loc, has season $ses, has SSP_value $sspval, has depth $dsspmax;
$duct($ssp, $y) isa SSP-channel;
$dex isa duct-exists, has number_of_ducts $nod; $y != $dex;
$y has depth $dy;
$speed($scn, $ssp) isa sound-speed;
$sspval has depth $dssp;
{$dssp == $dy;} or {$dssp == $dsspmax;};
get $speed, $ssp, $y, $sspval, $dy,$dsspmax, $dssp, $duct; offset 0; limit 30;
```
where $dssp is the shared attribute of interes, to be equal to $dy or $dsspmax. Here $dy can take 3 distinct values of depth and $dsspmax only one, produces following result:
```
{$ssp id V41087104 isa SSP-vec; $dssp 0 isa depth; $dy 0 isa depth; $sspval 1522.055742 isa SSP_value; $y id V250088 isa deep-channel; $duct id V286816 (find_channel: id V41087104, channel_exists: id V250088) isa SSP-channel; $dsspmax 1500 isa depth; $speed id V311512 (define_SSP: id V41087104, defined_by_SSP: id V8296) isa sound-speed;}
{$ssp id V41087104 isa SSP-vec; $dssp 950 isa depth; $dy 950 isa depth; $sspval 1522.785176 isa SSP_value; $y id V250088 isa deep-channel; $duct id V286816 (find_channel: id V41087104, channel_exists: id V250088) isa SSP-channel; $dsspmax 1500 isa depth; $speed id V311512 (define_SSP: id V41087104, defined_by_SSP: id V8296) isa sound-speed;}
{$ssp id V41087104 isa SSP-vec; $dssp 100 isa depth; $dy 100 isa depth; $sspval 1512.183359 isa SSP_value; $y id V250088 isa deep-channel; $duct id V286816 (find_channel: id V41087104, channel_exists: id V250088) isa SSP-channel; $dsspmax 1500 isa depth; $speed id V311512 (define_SSP: id V41087104, defined_by_SSP: id V8296) isa sound-speed;}
{$ssp id V41087104 isa SSP-vec; $dssp 1500 isa depth; $dy 100 isa depth; $sspval 1531.777734 isa SSP_value; $y id V250088 isa deep-channel; $duct id V286816 (find_channel: id V41087104, channel_exists: id V250088) isa SSP-channel; $dsspmax 1500 isa depth; $speed id V311512 (define_SSP: id V41087104, defined_by_SSP: id V8296) isa sound-speed;}
{$ssp id V41087104 isa SSP-vec; $dssp 1500 isa depth; $dy 950 isa depth; $sspval 1531.777734 isa SSP_value; $y id V250088 isa deep-channel; $duct id V286816 (find_channel: id V41087104, channel_exists: id V250088) isa SSP-channel; $dsspmax 1500 isa depth; $speed id V311512 (define_SSP: id V41087104, defined_by_SSP: id V8296) isa sound-speed;}
{$ssp id V41087104 isa SSP-vec; $dssp 1500 isa depth; $dy 0 isa depth; $sspval 1531.777734 isa SSP_value; $y id V250088 isa deep-channel; $duct id V286816 (find_channel: id V41087104, channel_exists: id V250088) isa SSP-channel; $dsspmax 1500 isa depth; $speed id V311512 (define_SSP: id V41087104, defined_by_SSP: id V8296) isa sound-speed;}
```
If I'm interpreting this correctly, it seems that the attribute is shared in 3\6 cases with $dy and in the other 3\6 cases with $dsspmax, however all of them are ultimately linked to the same SSP-vec id V41087104. My guess would be that depth: 0, 100, 950, 1500 are unique for this vector? 

@flyingsilverfin @VladGan would you please review my troubleshooting process? 

Similar output in another example:
```
match 
$bathy($scn, $x) isa bathymetry, has bottom_type $bt;$scn has scenario_id 440;
$x has length $l, has attribute $a;
$s isa slope; $d isa depth;
{$a == $s;} or {$a == $d;};
$ssp isa SSP-vec, has location $loc, has season $ses, has SSP_value $sspval, has depth $dsspmax;
$speed($scn, $ssp) isa sound-speed;
$sspval has depth $dssp;
{$dssp == $a;} or {$dssp == $dsspmax;};
get $bathy, $x, $l, $a, $ssp, $sspval, $dssp, $dsspmax; offset 0; limit 30;

{$ssp id V135352 isa SSP-vec; $a -2 isa slope; $dssp 1500 isa depth; $bathy id V41443352 (define_bathy: id V98528, defined_by_bathy: id V12392) isa bathymetry;  $dsspmax 1500 isa depth; $sspval 1531.777734 isa SSP_value; $x id V98528 isa wedge-segment; $l 41523.0 isa length;}
{$ssp id V135352 isa SSP-vec; $a 1500 isa depth; $dssp 1500 isa depth; $bathy id V213176 (define_bathy: id V90336, defined_by_bathy: id V12392) isa bathymetry; $dsspmax 1500 isa depth;  $sspval 1531.777734 isa SSP_value; $x id V90336 isa bottom-segment-2; $l 1238.5 isa length;}
{$ssp id V135352 isa SSP-vec; $a 50 isa depth; $dssp 1500 isa depth; $bathy id V41218224 (define_bathy: id V37088, defined_by_bathy: id V12392) isa bathymetry;  $dsspmax 1500 isa depth;  $sspval 1531.777734 isa SSP_value; $x id V37088 isa bottom-segment-1; $l 1238.5 isa length;}
{$ssp id V135352 isa SSP-vec; $a 50 isa depth; $dssp 50 isa depth; $bathy id V41218224 (define_bathy: id V37088, defined_by_bathy: id V12392) isa bathymetry;  $dsspmax 1500 isa depth; $sspval 1513.369141 isa SSP_value; $x id V37088 isa bottom-segment-1; $l 1238.5 isa length;}
```

If you agree, I think my problem is more of how to deal with multiple attributes of the same type assigned to a single entity. I think for my application I should get rid of multiple outputs containing only a single variable of interest, or merge them somehow. I will move with this problem to a more suitable section in the forum.

**Comment by VladGan** [comment]
@Qbbz thanks for your update, we will look into it and will get back to you. It is most likely in fact workbase issue

**Comment by Qbbz** [comment]
> @Qbbz thanks for your update, we will look into it and will get back to you. It is most likely in fact workbase issue

@VladGan i've found a bug in my code. The problem was the data format. Values for some of these 'depth' attributes were float() while for the other they were int(). I'm a bit surprised that I didn't get an error while inserting the data.

**Comment by flyingsilverfin** [comment]
@Qbbz can you file an issue for this please? This would probably save other people a headache!

**Comment by VladGan** [comment]
@Qbbz Good job!
