### ISSUE TITLE
[1], [0.0] and ["true"] are all accepted as `boolean` values

### ISSUE THREAD

**Issue by alexjpwalker** [graknlabs/grakn#5803]
## Description

[1], [0.0] and ["true"] are all accepted as `boolean` values.

## Environment

1. OS (where Grakn server runs): Mac OS 10
2. Grakn version (and platform): Grakn Core 1.8
3. Grakn client: client-java

## Reproducible Steps

```
define is-alive sub attribute, value boolean;
insert $x 1 isa is-alive;
```

## Expected Output

An error should be thrown because 1 is not a valid `boolean`, only `true` and `false` are.

## Actual Output

It gets stored as a boolean.

**Comment by flyingsilverfin** [comment]
Sloved With #5859
