### ISSUE TITLE
Grakn Match-Insert reads its own writes

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/grakn#5841]
## Description

This issue has come about from seeing an inconsistency in what is matched in a `match` query vs what is returned in a `match insert` query. It has been found that the same (or very similar) issue exists with rules.

## Environment

1. OS (where Grakn server runs): Mac OS 10
2. Grakn version (and platform): Grakn Core 1.8
3. Grakn client: console

## Reproducible Steps

Steps to create the smallest reproducible scenario:
```
define

closed_space sub entity,
    plays from_space,
    plays to_space;

kitchen sub closed_space;
living sub closed_space;
hall sub closed_space;

door sub entity,
    plays connection;
living_door sub door;
kitchen_door sub door;

closed_space_connecting sub relation,
    relates connection,
    relates from_space,
    relates to_space;

insert
$l isa living;
$k isa kitchen;
$h isa hall;
$ld isa living_door;
$kd isa kitchen_door;
(from_space: $l, to_space: $h, connection: $ld) isa closed_space_connecting;
(from_space: $h, to_space: $l, connection: $ld) isa closed_space_connecting;

(from_space: $k, to_space: $h, connection: $kd) isa closed_space_connecting;
(from_space: $h, to_space: $k, connection: $kd) isa closed_space_connecting;
```

This match gives results as expected:

```
match
$x isa closed_space;
$y isa closed_space;
$z isa closed_space;
$d1 isa door;
$d2 isa door;
(from_space: $x, to_space: $y, connection: $d1) isa closed_space_connecting;
(from_space: $y, to_space: $z, connection: $d2) isa closed_space_connecting;
$x != $z;
#$d1 != $d2; # optional
get $x, $z;
```
Results, note that the hall is never `$x` or `$y`. I have checked that without `get` filters this is still the correct set of x and z.
```
{$x id V16408 isa living; $z id V20504 isa kitchen;}
{$x id V20504 isa kitchen; $z id V16408 isa living;}
```

This `match insert` gives incorrect results:
```
match
$x isa closed_space;
$y isa closed_space;
$z isa closed_space;
$d1 isa door;
$d2 isa door;
(from_space: $x, to_space: $y, connection: $d1) isa closed_space_connecting;
(from_space: $y, to_space: $z, connection: $d2) isa closed_space_connecting;
$x != $z;
#$d1 != $d2;
insert (from_space: $x, to_space: $z, connection: $d1, connection: $d2) isa closed_space_connecting;
```

In the answer we see that the hall non-deterministically can be $x and/or $z, which based on the match it shouldn't be.
Therefore we are forced to believe that the `insert` part changes the answer of the match:
```
{$x id V24680 isa kitchen; $z id V36944 isa living; $d1 id V28776 isa kitchen_door; $d2 id V36968 isa living_door;}
{$x id V24680 isa kitchen; $z id V32848 isa hall; $d1 id V36968 isa living_door; $d2 id V36968 isa living_door;}
{$x id V36944 isa living; $z id V24680 isa kitchen; $d1 id V36968 isa living_door; $d2 id V28776 isa kitchen_door;}
```

Trying a rule fares no better:
```
define
connect-rooms sub rule,
when {
    $x isa closed_space;
    $y isa closed_space;
    $z isa closed_space;
    $d1 isa door;
    $d2 isa door;
    $c1(from_space: $x, to_space: $y, connection: $d1) isa closed_space_connecting;
    $c2(from_space: $y, to_space: $z, connection: $d2) isa closed_space_connecting;
    $x != $z;
    $d1 != $d2;
    $c1 != $c2;
}, then {
    (from_space: $x, to_space: $z, connection: $d1, connection: $d2) isa closed_space_connecting;
};
```

Query for
```
match (from_space: $x, to_space: $z, connection: $d1, connection: $d2) isa closed_space_connecting; get;
```
and see that the hall non-deterministically comes back as $x and/or $z, which it should never be.

**Comment by kasper-piskorski** [comment]
Please note that your rule is recursive, hence when using a rule the situation is different: your inferences can be applied back to your original data deriving new inferences.

Notation: 
```
(xPos -> (yPos) -> zPos) ^ doors
L - living
H - hall
K - kitchen
```
Originally you have:
```
(L -> H)^ d1
(H -> L)^ d1
(K -> H)^ d2
(H -> K)^ d2
```

From which you can infer using the rule that:
```
(L -> (H) -> K) ^ d1, d2
(K -> (H) -> L) ^ d1, d2
```

Which combined with the initial data will give you:
```
(L -> (K) -> H) ^ d1, d2
(K -> (L) -> H) ^ d1, d2
(H -> (L) -> K) ^ d1, d2
(H -> (K) -> L) ^ d1, d2
```
I. e. the halls are expected in both `$x` and `$y` position if you use a rule.

**Comment by flyingsilverfin** [comment]
The issue has been investigated:
1. The current implementation of `match-insert` reads its own writes
2. This means that we create a new relation between `$x` and `$z`, which allows the `match` to be satisfied in unexpected ways
3. This is a nondeterministic failure due to the query planner being nondeterministic - depending on how the vertices/edges are scanned 
4. Solving this in 2.0 would involve a sort of snapshotting mechanism within a transaction, along with probably only permitting a single writer/separate write buffers that live per-query, or similar.

**Comment by flyingsilverfin** [comment]
In 2.0, we collect all `match` answers before performing inserts between them, solving this issue (same logic applies for match-delete)
