### ISSUE TITLE
Symmetric Relation in Reasoning behaves differently to Graql

### ISSUE THREAD

**Issue by hkuich** [graknlabs/grakn#5872]
## Description

Given a symmetric relation as part of a rule, the rule engine returns more answers than the when clause executed using graql in the console as a match query. 

## Environment

1. OS (where Grakn server runs): Mac OSX 10.15.5
2. Grakn version (and platform): Grakn Core 1.8
3. Grakn client: Console

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Load Schema (attached)
2. Load sample Data (attached)

3. Run Rule query: - get 4 results (2 are erroneous)
```
match 
$t isa gene, has gene-id "gene1";
$d isa disease, has disease-id "disease1";
$rel (hypothesized-target: $t, disease-of-interest: $d, indirectly-supporting-evidence: $e) isa hypothesis; get;  offset 0; limit 5;
```
4. Run When clause as Match with gene and disease IDs - get 2 results (expected result)
```
match
    $g1 isa gene, has gene-id "gene1";
    $d isa disease, has disease-id "disease1";
    $h (hypothesized-target: $g1, disease-of-interest: $d) isa hypothesis;
    $g2 isa gene; 
    $holo (homologue: $g1, homologue: $g2) isa homology;
    $a (assay-target: $g2, modeled-disease: $d) isa assay;
get $a;
```
[data.gql.txt](https://github.com/graknlabs/grakn/files/5051510/data.gql.txt)
[schema.gql.txt](https://github.com/graknlabs/grakn/files/5063086/schema.gql.txt)

**Comment by jmsfltchr** [comment]
Corrected to remove `$g1 = $g2` from step 4 and from the rule, which was there erroneously.
Adding `$g1 != $g2` to the rule body makes the rule consistent with the match query, and hence is the point of contention of this whole issue.
