### ISSUE TITLE
Wrong number of explanations when analysing an inferred relation

### ISSUE THREAD

**Issue by richard-julien** [graknlabs/grakn#5877]
## Description

After migrating from 1.7 to 1.8.1 we have an integration test failing. The integration test try to explain a inferred relationship and we see a wrong number of explanations in the result.

## Environment

1. OS: Windows 10
2. Grakn Core 1.8.1
3. Grakn client: client-python 1.8.0

## Reproducible Steps

[gql_files.zip](https://github.com/graknlabs/grakn/files/5132609/gql_files.zip)
Steps to create the smallest reproducible scenario:
1. Load the schema "opencti.gql"
That will create the opencti schema + one inference rule
2. Insert the data "data.gql"
That will create 3 entities and 2 relations
Intrusion-Set -> Target -> Organization -> part of -> Sector
3. Check that inference is correct
Only 1 target relation is really created between Intrusion-Set -> Target -> Organization
The rule will infer a target relation between Intrusion-Set -> Target -> Sector
```
match $x isa targets; get;
{$x id V536672 (targets_from: id V1032208, targets_to: id V589952) isa targets;}
{$x id V540864 (targets_from: id V1032208, targets_to: id V1036304) isa targets;}
```
4. Use grakn client to list the relations and ask for inference and explanation

![image](https://user-images.githubusercontent.com/285555/91351902-52c10880-e7e9-11ea-9f9f-dd9735414f4b.png)

`{"level":"info","message":"Find inferred relation with 1 explanations","timestamp":"2020-08-26T20:06:58.969Z"}`

## Expected Output

We expect 2 explanations in the result.

## Actual Output

Only 1 explanation

**Comment by richard-julien** [comment]
Any news on this? Looks like a regression. Do you plan to fix it?

**Comment by kasper-piskorski** [comment]
Hey, so there were some updates in the behaviour of explanations:

https://github.com/graknlabs/grakn/pull/5709

Specifically an extra layer of indirection was introduced. The explanations of rules now only contain a single answer answering the `when` part of a given rule. The specific component explanations of the `when` conjunction can be obtained by accessing the explanation of that answer.

So in your example the first `getAnswers()` call expectedly produces a single answer. This explanation of that answer however will contain the 2 further answers you are looking for.
So for your rule
```
  PartOfTargetsRule sub rule,
    when {
      $rel1_part-of_from_part-of_to(part-of_from: $subEntity, part-of_to: $entity) isa part-of;
      $rel2_source_target(targets_from: $threat, targets_to: $subEntity) isa targets;
    }, then {
      (targets_from: $threat, targets_to: $entity) isa targets;
    };
```
The explanation structure looks like this:

Answer: 
`[$x id V536672]`
|
|   `explanation()`
|
RuleExplanation
|
|    `getAnswers()`
|
Answer: 
`[$rel1_part-of_from_part-of_to id ..., $rel2_source_target id ..., $subEntity id ..., $entity id ...., $threat id ...]` 
|
|  'explanation()'
|
JoinExplanation
|
|  `getAnswers()`
|
Answers{ 
`[$rel1_part-of_from_part-of_to,$subEntity, $entity)]`, 
`[$rel2_source_target, $threat, $subEntity]`
}

**Comment by richard-julien** [comment]
Ok thanks! I will try that and back to you if everything work

**Comment by richard-julien** [comment]
Hi @kasper-piskorski. This is now perfectly functional. Don't hesitate to add this to your documentation :) Thanks!
