### ISSUE TITLE
NullPointerException when trying to unset has edge that doesn't exist

### ISSUE THREAD

**Issue by lriuui0x0** [graknlabs/grakn#5904]
## Description

See https://github.com/graknlabs/grakn/blob/5690405fdba48f9b94347856908d9850f0da176c/concept/thing/impl/ThingImpl.java#L117-L119

We didn't check if the edge exists before trying to delete it, which will cause NPE.

**Comment by lolski** [comment]
[Triaged] @haikalpribadi I've moved this to medium since there's a for the user. they simply should not call "concept.unset(attribute)" if said concept does not actually have that particular attribute.

**Comment by haikalpribadi** [comment]
This is solved by https://github.com/graknlabs/grakn/commit/1a64381f10bb889379edbf86a57219d783c375b0
