### ISSUE TITLE
Define the behaviour of Alpha Equivalance between ValueConstraints of long and double

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/grakn#5908]
## Problem to Solve

Consider whether two concludables which are alpha equivalent up to a ValueConstraint, where one is a long and the other a double. Should these be considered equal? Implement accordingly.

**Comment by flyingsilverfin** [comment]
Only in Feb 9 did we formally reach a conclusion, which is rather obvious:
Attibutes of non-equal value type are not alpha-equivalent.
If they were, writing a concludable `$x has age 2.0`, would be resolved by either a concludable resolver for `$x has age 2.0` OR `$x has age 2`. However, the latter is incorrect as it has different unification behaviours with rules, than the former.

As such, we must treat different values as separate by data type, which is the current implementation
