### ISSUE TITLE
Reasoner 2.0: Rules should infer attribute ownership, but not attribute existence

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/grakn#5909]
## Problem to Solve

In Grakn <1.8.x it has been possible to write several kinds of attribute inference that infer more than one atomic fact.

```
infer-attribute sub rule,
when {
  $x isa person;
}, then {
  $x has name "Alice";
};
```

The rule head can be rewritten as:
- `$x has name $n; $n "Alice" isa name` or
- `$x has name $n; $n "Alice"`

This rule head will create the `name` "Alice" if it doesn't exist, *AND* will create a `has` edge from `$x` to that attribute. This means it infers two facts.

## Proposed Solution

We assert that the only sensible syntax that should be allowed for inferring `has` edges is:
```
...
then {
  $x has $a;
};
```

In this case, there are 3 options to achieve the functionality above:
1. The user pre-inserts the attribute, and rewrites the rule as below. This is a functional workaround until option 2 is implemented.
```
infer-attribute sub rule,
when {
  $x isa person;
  $a "Alice" isa name;
}, then {
  $x has $a;
};
``` 
2. Rule syntax permits computation/assignment of new attributes in a separate clause. This clause would give the `then` access to the newly generated facts. This approach is the cleanest, and is cohesive with how we imagine inferred arithmetic will work.
3. Pre-inserting attributes automatically. We see this as a poor workaround which we should avoid.
We still allow `then { $x has name "Alice"; };` but Grakn inserts the attribute ahead of time, to ensure that it always exists. Then only the `has` is being inferred by the rule head. This smells since the user is still writing two facts in the rule head, but it doesn't look like it because they're using a syntactic sugar (which looks like one fact) to do so.

**Comment by flyingsilverfin** [comment]
Following the conclusion outlined in https://github.com/graknlabs/grakn/issues/5911, this issue has been resolved.
