### ISSUE TITLE
Reasoner 2.0: A rule can only infer one atomic fact

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/grakn#5911]
## Problem to Solve

In Grakn <1.8.x:
- roleplayers could be inferred into existing relations, which clearly conflicts with the idea that relations are atomic, since in this way they can be broken down into components
- attribute existence and ownership could be inferred at once

## Proposed Solution

The head of a rule should only infer one atomic fact. 

Atomic facts in Grakn should be clearly defined as:
1. Entity existence
2. Attribute existence, with value
3. Relation existence, including all role:roleplayer pairs
4. Attribute ownership

As an outcome of this, we can see that only 3 and 4 should be inferable by rules.

**Comment by flyingsilverfin** [comment]
Closing as we went ahead and made the changes we required:
reasoning can only infer:
1. `(friend: $x) isa friendship` --  a new, complete relation instance
2. `$x has $a` -- re-attaching an existing matched attribtue to a new instances
3. `$x has name "Zoe"` -- attaching a potentially brand new attribute to a variable

Everything else is no longer allowed :)
