### ISSUE TITLE
Bazel build should use Java 11 by default

### ISSUE THREAD

**Issue by alexjpwalker** [graknlabs/grakn#5913]
## Problem to Solve

Java 11 has slightly different requirements to Java 8. A build on Java 8 is not guaranteed to work on Java 11. But we want to support Java 11.

## Proposed Solution

Ideally we would get Bazel to build Grakn (and Client Java) on both Java 8 and 11.

**Comment by haikalpribadi** [comment]
Are you aware of this, @vmax ?

**Comment by vmax** [comment]
@haikalpribadi @alexjpwalker as of now, default Java version on Grabl images is Java 11 (we also instruct it to build bytecode compatible with Java 8)
