### ISSUE TITLE
Reasoner 2.0: How to apply unifiers from concludables which have repeated variables

### ISSUE THREAD

**Issue by maxbaxt** [graknlabs/grakn#5914]
## Problem to Solve

Suppose we have a Conjunction Concludable:
```
(employee: $x, employee: $x) isa employee;
```
And want it unified with:
```
(employee: $a, employee: $b) isa employee;
```
Then the unifier will be something like `{a->x, b->z}`. This will mean that the solutions found to the rule head will have many invalid answers where `a=\=b`.

## Proposed Solution

A quick (in terms of implementation) solution will be to reject the answers that don't conform to the equality of some variables. It is currently unclear when and where in the codebase this rejection should be placed.
This solution is quite inefficient, so a better solution will be to have the Head Concludables "carry" the information from the Conjunction Concludables that triggered them. But currently we can't do that without remaking the conjunction in the Rule Body.

**Comment by flyingsilverfin** [comment]
Has been solved with `Unifier Requirements`, utilising a post-filter approach, which as noted, is less efficient. We will look toward making this more efficient with query rewriting.
