### ISSUE TITLE
Pattern shape guarantees can be encoded as classes

### ISSUE THREAD

**Issue by flyingsilverfin** [graknlabs/grakn#5919]
## Problem to Solve
At several points of defining grakn data structures, we make assumptions (sometimes validated via assertions, or exceptions) about the shape of constraints or variables. For instance, the `then` of a rule must have one of three exact forms. We can make this more type safe and strict, and easier to understand by having specific data structures for these forms.

As another example, in many cases it would be convenint to be able to assume that an `isa` constraint exists, but we almost never have this guarateed (except possibly by type inference, which we don't rely on having run). One idea is enforce certain shape characteristics during graql query normalisation, or Graql -> Grakn pattern translation. 

## Proposed Solution
* Implement more specialised data structures that reflect constrained shapes that a set of variables/constraints is allowed to have in a specific context (may be somewhat similar to `Concludable` that we enforce at a high level -- we can be less error prone by enforcing at the pattern level or lower)
* Implement padding or add assumed structure that has proven to be useful at query normalisation

**Comment by flyingsilverfin** [comment]
superceded by https://github.com/graknlabs/grakn/issues/6115

**Comment by haikalpribadi** [comment]
Make sure it has the right label when closing, @flyingsilverfin
