### ISSUE TITLE
StopIteration Exception when iterating over a concept map 

### ISSUE THREAD

**Issue by tomassabat** [graknlabs/grakn#6008]
## Description

I am printing all the instances of a type in Python. After a while Grakn hangs and it throws up an `StopIteration` Exception.

## Environment

1. OS: Mac OS 10.14
2. Grakn version: Grakn Core 2.0.0-alpha
3. Grakn client-python version: client-python 2.0.0-alpha-4
4. Python version: 3.9

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run this grakn distribution: https://www.dropbox.com/s/qtoy4igwsw5of3p/grakn-2.0-alpha-tomas-20210110.zip?dl=0
2. In a terminal run python, and run: 
```
from grakn.client import GraknClient, SessionType, TransactionType
client = GraknClient("localhost:1729")
session = client.session("biograkn_covid_19", SessionType.DATA)
tx = session.transaction(TransactionType.READ)
answer_iterator = tx.query().match("match $x isa gene, has entrez-id $gs; get $gs;")
n = 0
for answer in answer_iterator:
	print(answer.get("gs"))
	n = n + 1
```
4. After a while Grakn while will throw this error: 
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grakn/rpc/transaction.py", line 136, in _fetch
    response = next(self._response_iterator)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_channel.py", line 416, in __next__
    return self._next()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_channel.py", line 801, in _next
    raise StopIteration()
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grakn/rpc/stream.py", line 57, in __next__
    return next(self)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grakn/rpc/stream.py", line 50, in __next__
    res = self._transaction._fetch(self._request_id)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grakn/rpc/transaction.py", line 145, in _fetch
    raise GraknClientException("The transaction has been closed and no further operation is allowed.")
grakn.common.exception.GraknClientException: The transaction has been closed and no further operation is allowed.
```
5. The CPU keeps spinning on 100%
6. I am unable to stop Grakn using control + c and Java throws an `OutOfMemoryError` (see screenshot below)
7. I end up killing Grakn with `kill -9`

## Expected Output

I expect to have as an output all the instances of this given type printed in the console. 

## Actual Output

A StopIteration and a Java OutOfMemory Exception. 
 
## Additional information

![image](https://user-images.githubusercontent.com/20223184/104120553-a44cd880-532f-11eb-830b-2c6a018fc9fb.png)

![image](https://user-images.githubusercontent.com/20223184/104120545-9b5c0700-532f-11eb-9dba-5839e2a8bfd4.png)

**Comment by lolski** [comment]
I've confirmed that this is a bug with the graph producer: the query will work when you turn off parallelism in `QueryManager`.

The bug has been verified to exist in this version of Grakn: https://github.com/graknlabs/grakn/commit/c20ef0589c62abfa53e2a0c41079e1b89c44d00b

**Comment by lriuui0x0** [comment]
https://discord.com/channels/665254494820368395/672580553677078548/798309789556801587
