### ISSUE TITLE
Opening data session with schema session open hangs client

### ISSUE THREAD

**Issue by BFergerson** [graknlabs/grakn#6031]
## Description

If you have a schema session open then trying to open a data session will hang the Grakn client.
Reproduced with with JDK 8/11.

## Environment

1. OS (where Grakn server runs): Ubuntu 20
2. Grakn version (and platform): Grakn Core 2.0.0-alpha
3. Grakn client: java-client 2.0.0-alpha-4

## Reproducible Steps

```groovy
def graknHost = "localhost"
def graknPort = 1729
def graknKeyspace = "grakn"
def graknClient = new GraknClient(graknHost + ":" + graknPort)
if (graknClient.databases().contains(graknKeyspace)) graknClient.databases().delete(graknKeyspace)
graknClient.databases().create(graknKeyspace)
def schemaSession = graknClient.session(graknKeyspace, Grakn.Session.Type.SCHEMA) //<-- Change to DATA to fix issue

def dataSession1 = graknClient.session(graknKeyspace, Grakn.Session.Type.DATA)
def ds1Tx = dataSession1.transaction(Grakn.Transaction.Type.WRITE)
ds1Tx.close() //<-- Never gets here if schemaSession is opened with SCHEMA
dataSession1.close()

schemaSession.close()
graknClient.close()
```

**Comment by BFergerson** [comment]
FYI, probably belongs in the grakn-client repo. Didn't think about it till now.

**Comment by alexjpwalker** [comment]
There is a proposed fix to this issue, which is: https://github.com/graknlabs/client-java/issues/194

**Comment by haikalpribadi** [comment]
Should we throw an exception from the server instead, @alexjpwalker ? That would be safer for all clients to behave the same right? 

Can you ensure that you're closing the schema session before opening data transaction, @BFergerson ? A fix for this will only come in the form of timing out on opening the data transaction if schema session is still open.

**Comment by BFergerson** [comment]
I can do that. I opened this ticket because it was unexpected behavior and I couldn't find anything which documented it. It makes sense in retrospect but it took a minute to find because I was unaware that schema sessions are meant to be as short-lived as possible. There should be some documentation and/or error instead of just hanging, IMO.

**Comment by haikalpribadi** [comment]
You're right. An error on the locking data transaction upon timeout is the best way to go. That's what we'll do, I think. @alexjpwalker let's discuss tomorrow.

**Comment by alexjpwalker** [comment]
> Should we throw an exception from the server instead, @alexjpwalker ? That would be safer for all clients to behave the same right?

@haikalpribadi : With the proposed solution, the exception will indeed be thrown from the server, and all clients will behave the same.

We can split up the proposed solution into two parts:

1. Throw an exception if an attempt to open a transaction spends 10 seconds waiting for a lock
2. Make this 10 second timeout a configurable setting in all clients

**Comment by haikalpribadi** [comment]
> We can split up the proposed solution into two parts, where (1) is higher priority than (2):
> 
> 1. Throw an exception if an attempt to open a transaction spends 10 seconds waiting for a lock
> 2. Make this 10 second timeout a configurable Option in all clients

That's perfect, @alexjpwalker. Can you create 2 separate issues for that? Link them here, and make sure we triage them accordingly.

**Comment by alexjpwalker** [comment]
> That's perfect, @alexjpwalker. Can you create 2 separate issues for that? Link them here, and make sure we triage them accordingly.

High priority bug: https://github.com/graknlabs/grakn/issues/6065
Low priority feature: https://github.com/graknlabs/client-java/issues/242

**Comment by haikalpribadi** [comment]
Closing this issue as it has been resolved by:
- https://github.com/graknlabs/grakn/pull/6095
- https://github.com/graknlabs/grakn/pull/6111
