### ISSUE TITLE
Error attempting to define 'plays' with override in a Graql query

### ISSUE THREAD

**Issue by alexjpwalker** [graknlabs/grakn#6032]
## Description

An error occurs attempting to define 'plays' with override in a Graql query

## Environment

1. OS (where Grakn server runs): Mac OS 11
2. Grakn version (and platform): Grakn Core 2.0
3. Grakn client: console

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. Create database, session and schema write tx
2. Run query:
```graql
define
locates relates located;
contractor-locates sub locates, relates contractor-located as located;

employment sub relation, relates employee, plays locates:located;
contractor-employment sub employment, plays contractor-locates:contractor-located as located;
```

## Expected Output

Query should be accepted by the server

## Actual Output

A NullPointerException is thrown in `Definer.setPlays`
 
## Additional information

I also tried qualifying the overridden role: `plays contractor-locates:contractor-located as locates:located` but this fails to parse in Graql. I assume this is by design, and the real error is the NPE when trying to override with the unscoped role, which is thrown in `Definer.setPlays`.

**Comment by haikalpribadi** [comment]
Fixed by: https://github.com/graknlabs/grakn/pull/6050
