### ISSUE TITLE
Inter-transaction caching?

### ISSUE THREAD

**Issue by BFergerson** [graknlabs/grakn#6041]
## Problem to Solve

I have a query that takes 30s-1m to run the first time and takes 30ms after that if using the same transaction. Using another transaction makes the query go back to 30s-1m. I've tracked down the query speed to being caused by `traversalEng.iterator(conjunction.traversal())` in `TypeResolver.retrieveResolveTypes` iterating on 182k results. The 182k results is concerning given that the database the query is being run on doesn't have data and only has a schema. Once it does get passed that I can use the transaction to query much more efficiently.

Are there plans for inter-transactional caching and is there anything I can do to reduce the number of results that need to be iterated via `TypeResolver.retrieveResolveTypes`.

I'm using Grakn 2.0.0-alpha.

---

### Schema
https://gist.github.com/BFergerson/54f7a6f3b0701ec408341973b76c3d8f

### Query
```
match (is_parent: \$function, is_child: \$functionName); \$functionName has name contains "main";
```

**Comment by haikalpribadi** [comment]
There's a lot that has changed with type resolver at this point. 

@maxbaxt can you first confirm that the bug actually exist in 2.0.0-alpha, and then verify it again in with latest master. Report both results by commenting on this issue. This may have been solved in latest master. But if not, please help debug it.

**Comment by BFergerson** [comment]
I've confirmed the results with 2.0.0-alpha-2 to be sub-second. The first time the query was run was ~700ms and each time after that was < 15ms. This speed is also present in new transactions. It would be interesting to know which commit solved this issue but that's for me to look into. Thanks.
