### ISSUE TITLE
Cancelling a query in the console causes server to hang

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/grakn#6043]
## Description

Trying to cancel a query before it had completed left the console in an unusable state, presumably while it was waiting for the server to finish the query. In fact, I tried to cancel the query before _any_ results were streamed back. If it were left to run this query should return many results.

## Environment

1. OS (where Grakn server runs): AWS
2. Grakn version (and platform): Grakn 2.0 Alpha
3. Grakn client: console
4. Other environment details: Private client data

## Reproducible Steps

Steps to create the smallest reproducible scenario:
Run this query in the console:

```
<db>::data::read> match
> $dis isa disease, has disease-id "C0020517";
> $dda(therapeutic: $drug, $dis) isa drug-disease-association;
> $drug(drug-substance: $c) isa is-a-drug; $c isa compound;
> $cta($c, $pro) isa drug-protein-interaction;
```

Try to cancel the query with ctrl+c

## Expected Output

Query should stop running and console should return.

## Actual Output

Console didn't return, which put it in an unresponsive state. Killed the server with `kill -9 <pid>` (`kill wasn't sufficient, indicating that the server could have been hanging). Having killed the server the console returned.
 
## Additional Information
Similar to https://github.com/graknlabs/console/issues/93

**Comment by haikalpribadi** [comment]
Do we have the schema and data to reproduce this bug, @jmsfltchr ? The query above won't be sufficient to reproduce the issue without them.

**Comment by jmsfltchr** [comment]
Yes we have access to the Grakn instance, however that information is private and so can't be shared here.

**Comment by VladGan** [comment]
fixed in https://github.com/graknlabs/console/pull/117
