### ISSUE TITLE
Set constructor cannot infer common parent class

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/grakn#6045]
## Problem to Solve

Grakn common's `public static <T> Set<T> set(Collection<T> collection, T item, T... items)` constructor (and similar others) falls down when the exact type of the provided collection isn't given. This happens quite frequently, for example:

```
private final RelationConstraint relation;
private final IsaConstraint isa;
private final Set<LabelConstraint> labels;

@Override
public Set<Constraint> concludableConstraints() {
    return isa == null ? set(labels, relation) : set(labels, relation, isa);
}
```
The above won't work, so we are forced to work around with this:
```
@Override
public Set<Constraint> concludableConstraints() {
    return isa == null ? set(new HashSet<>(labels), relation) : set(new HashSet<>(labels), relation, isa);
}
```

**Comment by haikalpribadi** [comment]
This is a correct java behaviour. I've explained to @jmsfltchr in person so I'm closing this.
