### ISSUE TITLE
Illegal internal state thrown from match aggregate query using 'sum'

### ISSUE THREAD

**Issue by alexjpwalker** [graknlabs/grakn#6090]
## Description

When executing a match aggregate query using 'sum', an illegal internal state error is thrown.

## Environment

1. OS (where Grakn server runs): Ubuntu 16.4
2. Grakn version (and platform): Grakn Core 2.0
3. Grakn client: client-python

## Reproducible Steps

The `get.feature` test intermittently fails. One of the violating scenarios is: `the sum of an answer set of 'long' values can be retrieved`:
```
Given graql insert                                                                   # external/graknlabs_behaviour/graql/language/steps/graql_steps.py:69
      """
      insert
      $p1 isa person, has age 6, has ref 0;
      $p2 isa person, has age 30, has ref 1;
      $p3 isa person, has age 14, has ref 2;
      """
    Given transaction commits                                                            # external/graknlabs_behaviour/graql/language/steps/transaction_steps.py:110
    Given the integrity is validated                                                     # external/graknlabs_behaviour/graql/language/steps/graql_steps.py:33
    Given session opens transaction of type: read                                        # external/graknlabs_behaviour/graql/language/steps/transaction_steps.py:43
    When get answer of graql match aggregate                                             # external/graknlabs_behaviour/graql/language/steps/graql_steps.py:116
      """
      match $x isa person, has age $y;
      sum $y;
      """
2021-01-26 14:32:01,124 [ForkJoinPool-1-worker-5] [ERROR] grakn.core.rocks.RocksStorage - grakn.core.common.exception.GraknException: [INT01] Invalid Internal State: Illegal internal state!
grakn.core.common.exception.GraknException: grakn.core.common.exception.GraknException: [INT01] Invalid Internal State: Illegal internal state!
	at grakn.core.common.exception.GraknException.of(GraknException.java:51)
	at grakn.core.common.producer.ProducerIterator.hasNext(ProducerIterator.java:93)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at grakn.core.query.Matcher$Aggregator.aggregate(Matcher.java:167)
	at grakn.core.query.Matcher$Aggregator.execute(Matcher.java:162)
	at grakn.core.query.QueryManager.match(QueryManager.java:103)
```

## Expected Output

The sum should be 50.

## Actual Output

An illegal internal state error is thrown.
 
## Additional information

All of the `sum` operations have a chance to throw this error. I'm not sure if it's reproducible in Core.

**Comment by lriuui0x0** [comment]
@alexjpwalker  I have ran the test 30 times locally and didn't reproduce this. The test also seems quite stable on CI. I can see that you're using a version of core that's a week ago, can you update the core to latest version? Maybe that will fix the problem.

**Comment by alexjpwalker** [comment]
Using Grakn version `c2efc0a71a215b59650a3ea0e8b6f4c2c83737e3` (created 2 days ago) in client-java:
```
1) the min of an answer set of 'long' values can be retrieved(Graql Get Clause)

grakn.client.common.exception.GraknClientException: grakn.core.common.exception.GraknException: [INT01] Invalid Internal State: Illegal internal state! Please check server logs for the stack trace.
```
See https://grabl.io/alexjpwalker/client-java/92b6d0cd5aa6e43eb297fb813d91c800894e5e14/build/1/correctness/1/test-behaviour/1 for the full test log

**Comment by haikalpribadi** [comment]
This test doesn't fail on graknlabs/grakn BDD tests. Is anyone working on this right now @alexjpwalker ?

**Comment by haikalpribadi** [comment]
So the bug was found in client-python, @alexjpwalker reproduced it in client-java above, so make sure to NOT just test it on graknlabs/grakn, @lriuui0x0 . Make sure to test it though a client.

**Comment by VladGan** [comment]
closed since I'm not able to reproduce it (@alexjpwalker comment about seeing this issue in the new grakn was a mistake, he used old grakn)
