### ISSUE TITLE
Queries stall under Java 11 but not under Java 8

### ISSUE THREAD

**Issue by vmax** [graknlabs/grakn#6096]
## Description

Some queries stall when ran under Java 11

## Environment

1. OS (where Grakn server runs): Ubuntu 20.10
2. Grakn version (and platform): 2.0.0-alpha
3. Grakn client: test from within Core codebase
4. Other environment details: -

## Reproducible Steps

Test added in #6059

Steps to create the smallest reproducible scenario:

`bazel test //test/integration/docs:test-1 --test_output=streamed --runs_per_test=10`

## Expected Output

every test finishing in time

## Actual Output

Some of the tests stall

## Additional information

Might be connected with query planner not choosing an optimal plan?

**Comment by haikalpribadi** [comment]
Solved with `2.0.0-alpha-4`
