### ISSUE TITLE
ThreadLocal used in ManagedBlockingQueue causing memory leak

### ISSUE THREAD

**Issue by lriuui0x0** [graknlabs/grakn#6108]
When `ThreadLocal` is used as instance field, we need to call `remove()` method explicitly, otherwise memory will not be released until the thread finishes.

See https://www.baeldung.com/java-memory-leaks#7-using-threadlocals

**Comment by haikalpribadi** [comment]
Please don't forget to assign labels and project to new issues, @lriuui0x0

**Comment by haikalpribadi** [comment]
Usages of `ThreadLocal` have now been removed by the following commits:
- https://github.com/graknlabs/grakn/commit/5d614198e453dffff1573e3cf94c1dcca0c76bc8 
- https://github.com/graknlabs/grakn/commit/9f4146a67c51a45e6c9b2ce272f2ff4ee1a7385a
- https://github.com/graknlabs/grakn/commit/130141ef0b48fd09efa41f0a6f3d974725f7daaf
- https://github.com/graknlabs/grakn/commit/4fa8b46af06c390de980e86e1d0324c6110c1b22
