### ISSUE TITLE
Traversal engine throws an error when the optimiser is continued on from another cache

### ISSUE THREAD

**Issue by maxbaxt** [graknlabs/grakn#6109]
## Description

Running the `TraversalEgine.iterator()`  on a query already search for can lead the planning algorithm to reach an illegal state.

## Environment

Grakn Core

## Reproducible Steps

1. Open the branch: [ https://github.com/maxbaxt/grakn/tree/optimisation-cache-fail]( https://github.com/maxbaxt/grakn/tree/optimisation-cache-fail)
2. Run the test `hit_planning_cache_twice()` in `TypeResolverTest`.

## Expected Output

It should run the `TyepResolver` twice

## Actual Output

Runs it the first time, but the second time it reaches an illegal state whilst running the optimiser.
 
## Additional information

I have disabled the `TypeResolver` cache in order to trigger the planning cache.

**Comment by haikalpribadi** [comment]
This issue is fixed by https://github.com/graknlabs/grakn/commit/3b212bc0370d5ffa7c77a715a0a0d2eb1fc77777
