### ISSUE TITLE
Grakn would crash when attempting to delete a database

### ISSUE THREAD

**Issue by lolski** [graknlabs/grakn#6112]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

[This commit](https://github.com/graknlabs/grakn/commit/bff5ee18549773d653c9141e496eecebc2602b72) has introduced a bug where Grakn may crash when attempting to delete a database.

## Environment

1. OS (where Grakn server runs): Linux, Mac (and perhaps Windows too)
2. Grakn version (and platform): bff5ee18549773d653c9141e496eecebc2602b72
3. Grakn client: client-java

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. Go to `client-java`
2. Update `@graknlabs_grakn_core_artifact` to `bff5ee18549773d653c9141e496eecebc2602b72`
3. `bazel test //test/behaviour/graql/language/define:test-core --cache_test_results=no`

## Expected Output

The tests passed

## Actual Output

The tests failed because Grakn crashed when BDD's `ConnectionSteps` tries to delete the test database

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000001122105c1, pid=90981, tid=28931
#
# JRE version: Java(TM) SE Runtime Environment 18.9 (11.0.9+7) (build 11.0.9+7-LTS)
# Java VM: Java HotSpot(TM) 64-Bit Server VM 18.9 (11.0.9+7-LTS, mixed mode, tiered, compressed oops, g1 gc, bsd-amd64)
# Problematic frame:
# C  [librocksdbjni8592788797031841212.jnilib+0x2e5c1]  Java_org_rocksdb_Transaction_disposeInternal+0x2a1
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
--- i: grakn
# An error report file with more information is saved as:
# /private/var/tmp/_bazel_lolski/461c6321c5cf0efb4a452e28f6d21c8d/sandbox/darwin-sandbox/1405/execroot/graknlabs_client_java/bazel-out/darwin-fastbuild/bin/test/behaviour/graql/language/define/test-core.runfiles/graknlabs_client_java/test/grakn-core-server-native/grakn-core-server-mac-bff5ee18549773d653c9141e496eecebc2602b72/hs_err_pid90981.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

```
 
## Additional information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by haikalpribadi** [comment]
Don't forget to re-enable this test in client-java once you fix this issue, @lriuui0x0 : https://github.com/graknlabs/client-java/blob/0a971ec467d3736d38908ac29aa57ec2316f16c0/.grabl/automation.yml#L79-L80

**Comment by haikalpribadi** [comment]
This issue is solved by https://github.com/graknlabs/grakn/commit/bbcf14300c1118c20bc6dc54ef20fd49431a0e7a
