### ISSUE TITLE
Deleted vertices can have new edges added to them

### ISSUE THREAD

**Issue by Phillammon** [graknlabs/grakn#6117]
Once a vertex has been deleted, it should not be possible to give it new edges- either by giving it a new attribute ownership, by assigning it to be owned by another thing, or by being assigned another roleplayer (if the vertex is a relation). Presently, this is allowed blindly, and should instead throw an exception of some kind.

Related to https://github.com/graknlabs/behaviour/pull/160
Related to https://github.com/graknlabs/behaviour/pull/161 (ignored scenario only)

**Comment by haikalpribadi** [comment]
Can you make sure to add BDD scenarios for this (and `@ignore` it), open a PR for it and link them here?

**Comment by haikalpribadi** [comment]
This issue is fixed by https://github.com/graknlabs/grakn/commit/1016555c4e9bf1958fbd1913be6a0f0aa3a4ad82
