### ISSUE TITLE
Inserting a relation where a relation already exists extends the relation

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/grakn#6148]
## Description

Under certain circumstances adding a relation between two players, who are already related by the same relation type, instead creates two relations with four role-players.

## Environment

1. OS (where Grakn server runs): AWS
2. Grakn version (and platform): 2.0 alpha 5
3. Grakn client: client-python
4. Other environment details: I have full steps for reproducing this on a client's private server. I will share this privately.

**Comment by haikalpribadi** [comment]
Fixed by @lriuui0x0 through https://github.com/graknlabs/grakn/commit/0ec3c1186da1ffc43eefeb39ca3804a90a8174ad
