### ISSUE TITLE
Grakn Server Documentation referencing non-existing `status` command

### ISSUE THREAD

**Issue by chris-aeviator** [graknlabs/grakn#6166]
Running grakn:latest via docker (V. 2.0.0-alpha6) as suggested in the documentation will not give access to the `grakn server status` command.

Running `./grakn server status` will yield in a 

```
root@6934d65565d4:/opt/grakn-core-all-linux# ./grakn server status

====================================================================================================
      ________  _____     _______  __    ___ __    __      _______  _______  _____     _______
     |   __   ||   _  \  |   _   ||  |  /  /|  \  |  |    |   _   ||   _   ||   _  \  |   ____|
     |  |  |__||  | |  | |  | |  ||  | /  / |   \ |  |    |  | |__||  | |  ||  | |  | |  |
     |  | ____ |  |_/ /  |  |_|  ||  |/  /  |    \|  |    |  |     |  | |  ||  |_/ /  |  |____
     |  ||_   ||   _  \  |   _   ||   _  \  |   _    |    |  |  __ |  | |  ||   _  \  |   ____|
     |  |__|  ||  | \  \ |  | |  ||  | \  \ |  | \   |    |  |_|  ||  |_|  ||  | \  \ |  |____
     |________||__|  \__\|__| |__||__|  \__\|__|  \__|    |_______||_______||__|  \__\|_______|

                                         THE KNOWLEDGE GRAPH
====================================================================================================
Usage: grakn server [-hV] [--debug] [--[no-]grabl-trace] [--data=<data>]
                    [--grabl-token=<grablToken>] [--grabl-uri=<grablURI>]
                    [--grabl-username=<grablUsername>] [--port=<port>] [COMMAND]
      --data=<data>        Directory in which database server data will be
                             stored
      --debug              Debug mode
      --grabl-token=<grablToken>
                           Grabl account access token
      --[no-]grabl-trace   Enable Grabl performance tracing
      --grabl-uri=<grablURI>
                           Grabl tracing server URI
      --grabl-username=<grablUsername>
                           Grabl username
  -h, --help               Show this help message and exit.
      --port=<port>        Port number of database server in which GRPC clients
                             will connect to
  -V, --version            Print version information and exit.
Commands:
  import
  export
  schema
```

message where as it should display the server status.

Running the commands in the documentation should always yield in correct behaviour, even when transitioning to a new version (as indicated by the version tag 2.0.0-alpha-6)

**Comment by haikalpribadi** [comment]
Hi @chris-aeviator, the new Grakn 2.0.0, no longer takes the argument `status`. As you can see the output of the CLI helper, only `--data`, `--debug`, `--grabl-*`, `--help`, `--port` and `--version` are the flags now accepted in 2.0.0.

The reason `status` is no longer needed in Grakn 2.0, is because the server application runs in the "foreground" now, as opposed to Grakn 1.8, which would run as a process in the "background". And because it's in the foreground now, you don't need to check the status. You can either see it running in the foreground, blocking your console, or not. The way to run it in the background as a process now is only by using `systemd`, and `systemctl`, after wrapping Grakn as a "service". We will automate and document this in the future. But for now, running Grakn in the foreground should be sufficient to get started.

**Comment by chris-aeviator** [comment]
@haikalpribadi thanks for your explanation. The reason for this issue was also to highlight the need to adjust the documentation, since as a user I expect the documentation to point to the correct commands at all times, which is not the case anymore since the graknlabs/grakn:latest does not point to the container anymore that's meant to be in the documentation. Therefore I suggest to change the documentation to either strip out the `grakn server status` command or explicitly mention to run `graknlabs/grakn:1.8.4` in the docker section

**Comment by haikalpribadi** [comment]
And just to make sure you're on the right documentation...

Grakn 2.0.0 is currently documented on https://dev.docs.grakn.ai

The main https://docs.grakn.ai is still hosting Grakn 1.8. That is because Grakn 2.0 is still in "alpha" stage (only for a very short while now)

**Comment by haikalpribadi** [comment]
I see you're point, @chris-aeviator - you're right! I think the docker documentation is out of sync with the new Grakn 2.0.0 now. 

@lolski @vmax can you help update docker documentation to be in sync with 2.0?

I shall close this issue now, Chris! Thank you for raising it to our attention!

**Comment by haikalpribadi** [comment]
Follow up on this issue is filed here: https://github.com/graknlabs/grakn/issues/6167

**Comment by chris-aeviator** [comment]
this is not solved btw - v.2.0. still raises an error

```
:/opt/typedb-all-linux# ./typedb server status

================================================================
     ________ __      __ _____    _______  _____    _____
    |__    __|\  \  /  /|   _  \ |   _   ||   _  \ |   _  \
       |  |    \  \/  / |  | |  ||  | |__||  | |  ||  | |  |
       |  |     \    /  |  |/  / |  |___  |  | |  ||  |/  /
       |  |      |  |   |   __/  |   ___| |  | |  ||   _  \
       |  |      |  |   |  |     |  |  __ |  | |  ||  | |  |
       |  |      |  |   |  |     |  |_|  ||  |/  / |  |/  /
       |__|      |__|   |__|     |_______||_____/  |_____/

                    A STRONGLY-TYPED DATABASE
================================================================

Unmatched argument at index 0: 'status'
Usage: typedb server [-hV] [--debug] [--[no-]vaticle-factory-trace]
                     [--data=<data>] [--logs=<logs>] [--port=<port>]
                     [--vaticle-factory-token=<factoryToken>]
                     [--vaticle-factory-uri=<factoryURI>]
                     [--vaticle-factory-username=<factoryUsername>] [COMMAND]
      --data=<data>   Directory in which database server data will be stored
      --debug         Debug mode
  -h, --help          Show this help message and exit.
      --logs=<logs>   Directory in which database server logs will be stored
      --port=<port>   Port number of database server in which GRPC clients will
                        connect to
  -V, --version       Print version information and exit.
      --vaticle-factory-token=<factoryToken>
                      Vaticle Factory account access token
      --[no-]vaticle-factory-trace
                      Enable Vaticle Factory performance tracing
      --vaticle-factory-uri=<factoryURI>
                      Vaticle Factory tracing server URI
      --vaticle-factory-username=<factoryUsername>
                      Vaticle Factory username
Commands:
  import
  export
```

**Comment by haikalpribadi** [comment]
It's not meant to be solved, @chris-aeviator. The `status` command has been dropped since 2.0. See my reply above: https://github.com/vaticle/typedb/issues/6166#issuecomment-778634637
