### ISSUE TITLE
Grakn does not read the data in full and goes into itself 

### ISSUE THREAD

**Issue by hermanvolobuev** [graknlabs/grakn#6187]
## Description

Attempts to do the following result in either a crash or the "goes into itself" of the Grakn server : 
1) simple sequential reading of data without any filtering and/or sorting;
2) reading single records and creating on their basis a relationship and writing a relationship to the Grakn, 
3) reading single records with selection.
This report contains materials according to claim 1, namely the code, which was used to generate the grack scheme and 5,027,200 concepts containing randomly generated attributes. Then there was an attempt to read the generated concepts. The reading limit was set at 6,000,000 results. Without specifying the limit, Grakn goes into itself - this is a separate error, and does not return any result. 4,345,000 concepts were read, which is slightly less than necessary. As a result, the server went into itself and the program did not end. 

## Environment

1. OS (where Grakn server runs): Ubuntu 20.04.2 LTS
2. Grakn version (and platform): 2.0.0-alpha-7
3. Grakn client: client-java.         
4. Other environment details:
      <dependency>
            <groupId>io.graql</groupId>
            <artifactId>graql-lang</artifactId>
            <version>2.0.0-alpha-7</version>
        </dependency>
        <dependency>
            <groupId>io.grakn.client</groupId>
            <artifactId>grakn-client</artifactId>
            <version>2.0.0-alpha-8</version>
        </dependency>

IntelliJ Idea project:
[grakn_test.zip](https://github.com/graknlabs/grakn/files/6009301/grakn_test.zip)

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. run GraknTest.main

## Expected Output

normal program termination, the log should indicate that the number of concepts written to the base is equal to the number of read concepts. 

## Actual Output

the server "goes into itself".
 
## Additional information

Intellij Idea and server console views:
<img width="1839" alt="Screenshot 2021-02-19 114927" src="https://user-images.githubusercontent.com/52756583/108493641-9b004580-72b7-11eb-9274-00a525aa622c.png">

concept insertion and schema creation log:
<img width="975" alt="Screenshot 2021-02-19 115422" src="https://user-images.githubusercontent.com/52756583/108493658-a0f62680-72b7-11eb-9ed3-d9ca8245e75e.png">

htop view:
<img width="1843" alt="Screenshot 2021-02-19 120041" src="https://user-images.githubusercontent.com/52756583/108493677-a5224400-72b7-11eb-9e60-00a943f8c3fd.png">

Grakn server log:
[LOG.zip](https://github.com/graknlabs/grakn/files/6009339/LOG.zip)

**Comment by hermanvolobuev** [comment]
In the process of dealing with the problem described here, I tried to re-create the Grack.client. The result was an exception when getting a new client. in the process of dealing with the problem described here, I tried to re-create the Grack.client. The result was an exception when getting a new client. Traces of this in the comment: 
![изображение](https://user-images.githubusercontent.com/52756583/108635050-ff74fd80-748d-11eb-8dcc-83fdfb583ac2.png)

**Comment by haikalpribadi** [comment]
I don't understand the issue you're trying to describe here, @hermanvolobuev. The screenshots don't make sense either. Are you on our Discord chat server? Perhaps you can explain it better via chat? The screenshots of your IDE as they are above are not very helpful to tell what's going on wrong. And what does "Grakn goes into itself" even mean????? 🤯

**Comment by haikalpribadi** [comment]
I don't understand that problem you're trying to describe at all, @hermanvolobuev. You should not just dump an entire folder of your IDE to reproduce your problem. That's not what "reproducible steps" mean. Don't use screenshots to describe your problem in lieu of appropriate descriptions. Please open another issue with a proper explanations of your problem, and a sequence of steps to reproduce your problem.

Make sure you write your schema that was used when the bug occurred, provide the scripts to load the data, and provide the query that caused the bug. The above post you've created does not help us in reproducing the bug at all.
