### ISSUE TITLE
data reading does not work 

### ISSUE THREAD

**Issue by hermanvolobuev** [graknlabs/grakn#6201]
This bug report is linked to bug report # 6187 "Grakn does not read the data in full and goes into itself". The statements shown in the figure do not work - the server "goes into itself". The reason is the number of attributes that need to be retrieved from the database in one request. If this number is radically reduced to two or three, then this query works - see # 6187. 

![изображение](https://user-images.githubusercontent.com/52756583/108634536-03ebe700-748b-11eb-874a-a3828dc107f3.png)

## Environment

OS (where Grakn server runs): Ubuntu 20.04.2 LTS
Grakn version (and platform): 2.0.0-alpha-7
Grakn client: client-java.
Other environment details:

io.graql
graql-lang
2.0.0-alpha-7

io.grakn.client
grakn-client
2.0.0-alpha-8

IntelliJ Idea project:
[grakn_test.zip](https://github.com/graknlabs/grakn/files/6018269/grakn_test.zip)

## Reproducible Steps

run GraknTest.main 

## Expected Output

normal program termination

## Actual Output

the server "goes into itself"
 
## Additional information

nothing

**Comment by haikalpribadi** [comment]
This task is also confusing, like the other 2. I don't understand that problem you're trying to describe at all, @hermanvolobuev. You should not just dump an entire folder of your IDE to reproduce your problem. That's not what "reproducible steps" mean. Don't use screenshots to describe your problem in lieu of appropriate descriptions. Please open another issue with a proper explanations of your problem, and a sequence of steps to reproduce your problem.
