### ISSUE TITLE
Correct using classes designed to get a client, session and transaction raises the [CLI1] Illegal Client State exception. 

### ISSUE THREAD

**Issue by hermanvolobuev** [graknlabs/grakn#6207]
This task is a supplement to the task "Grakn does not read the data in full and goes into itself #6187". The program attached illustrates the following: 
- generating the schema and the test database (if necessary, see task #6187), 
- reading generated entities from the test database (taking into account the features described in task #6201), 
- creating relationships based on the read entities. 

## Environment

    OS (where Grakn server runs): Ubuntu 20.04.2 LTS
    Grakn version (and platform): 2.0.0-alpha-7
    Grakn client: client-java.
    Other environment details:

    io.graql
    graql-lang
    2.0.0-alpha-7
    io.grakn.client
    grakn-client
    2.0.0-alpha-8

## Reproducible Steps

prepare and execute the IntelliJ Idea project: 
[grakn_test.zip](https://github.com/graknlabs/grakn/files/6028736/grakn_test.zip)

## Expected Output

 In a normal situation, the program should have created many relationships.

## Actual Output

The program ends with an exception "[CLI 1] Illegal Client State". As can be seen from the program log, only one correct relationship is created (see Figure 1), which is confirmed by executing the corresponding request in the console (see Figure 2). 
 
## Additional information

Fig.1 - program ends with an exception "[CLI 1] Illegal Client State" and only one correct link is created
![изображение](https://user-images.githubusercontent.com/52756583/108839820-98b72780-75e6-11eb-9235-4cd1acd86cda.png)

Fig.2 -  executing the corresponding request in the console
![изображение](https://user-images.githubusercontent.com/52756583/108840141-f8adce00-75e6-11eb-94f4-89278e61707e.png)

**Comment by haikalpribadi** [comment]
This task is also confusing, like the other 2. I don't understand that problem you're trying to describe at all, @hermanvolobuev. You should not just dump an entire folder of your IDE to reproduce your problem. That's not what "reproducible steps" mean. Don't use screenshots to describe your problem in lieu of appropriate descriptions. Please open another issue with a proper explanations of your problem, and a sequence of steps to reproduce your problem.
