### ISSUE TITLE
Stalling when doing multiple Match queries and closing the sessions while they are running

### ISSUE THREAD

**Issue by alexjpwalker** [graknlabs/grakn#6212]
## Description

When repeatedly running Match queries and quickly closing the sessions, after a short while, the system simply hangs and stops responding to RPC calls.

## Environment

1. OS (where Grakn server runs): Mac OS 11
2. Grakn version (and platform): Grakn Core 2.0
3. Grakn client: client-java

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. With an empty Grakn database running in the background, run client-java
2. Repeat 50 times:
  2.1. Open a data session and read transaction
  2.2. Run `match $x isa thing;` without awaiting the response
  2.3. Immediately close the session

## Expected Output

All of the match queries should fail due to interruption and the test should run to completion.

## Actual Output

After the 18th session is closed, no more sessions can be opened - the system stalls.
 
## Additional information

Debugging the various server threads, it appears to have got stuck on `procedureLatch.await` in `GraphPlanner.procedure`. And if we change that line to add a timeout, like `procedureLatch.await(1, TimeUnit.SECONDS)` then the result changes: it hangs for 1 second, then the 19th session opens, then it hangs for 1 second, then the 20th session opens... and so on, until all the sessions have opened and the test runs to completion, albeit very slowly.

Clearly, adding a timeout to this latch is not the right solution. Perhaps we should have the traversal engine keep track of all active traversals and terminate them when the underlying resources are closed?

**Comment by alexjpwalker** [comment]
This error can be reproduced in Grakn Core using a similar procedure: see https://github.com/alexjpwalker/grakn/tree/graph-producer-await-stall .

The reproducible scenario is `graphProducerAwaitTest` in `test/integration/QueryTest.java`.

**Comment by haikalpribadi** [comment]
This issue is fixed by https://github.com/graknlabs/grakn/commit/2f3797bb5ec198aa28064ce1644b29d7b72e3ee9
