### ISSUE TITLE
Data deletion error and crash

### ISSUE THREAD

**Issue by fatter-pale** [graknlabs/grakn#6217]
## Description

I try to delete all data from a database in a single query (data as instances of thing), but get an error. This can lead to a server crash after several repetitions.

## Environment

1. Docker
2. Grakn Core: GraknServer --version: 2.0.0-alpha-7
3. Grakn client: Console --version: 2.0.0-alpha-6

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. ./grakn console
2. database create testdb
3. transaction testdb **schema** write
4. source ...
```
define

### ATTRIBUTES

an-id sub attribute,
    value string;

operational-status sub attribute,
    value boolean;

an-amount sub attribute, abstract,
    value long;

    volume-ml sub an-amount;

    a-percentage sub an-amount, abstract;

        alcohol-percentage sub a-percentage;

beverage-type sub attribute,
    value string,
    owns an-id @key,
    owns alcohol-percentage,
    plays containing:contained;

### ENTITIES

Equipment sub entity,
    owns an-id @key;

    Robot sub Equipment,
        owns operational-status,
        plays attaching:attacher;

    Gripper sub Equipment,
        plays attaching:attached;

    Glass sub Equipment,
        plays containing:container;

### RELATIONS

containing sub relation,
    owns volume-ml,
    relates contained,
    relates container;

mounting sub relation,
    relates mounted,
    relates mount;

    attaching sub mounting,
        relates attached as mounted,
        relates attacher as mount;
```
4. commit
5. transaction testdb **data** write
6. source ...
```
insert

$r1 isa Robot,
    has an-id "Robot1";

$r2 isa Robot,
    has an-id "Robot2";

$gr1 isa Gripper,
    has an-id "Gripper1";

$gr2 isa Gripper,
    has an-id "Gripper2";

(attached: $gr1, attacher: $r1) isa attaching;

(attached: $gr2, attacher: $r2) isa attaching;

$gin "gin" isa beverage-type,
    has an-id "bt-gin",
    has alcohol-percentage 40;

$tonic "tonic" isa beverage-type,
    has an-id "bt-tonic",
    has alcohol-percentage 0;

$glass isa Glass,
    has an-id "GnT-glass";

(contained: $gin, container: $glass) isa containing,
    has volume-ml 40;
```
7. commit
8. transaction testdb data write
9. `match $x isa thing; delete $x isa thing;`

## Expected Output

`Concepts have been deleted`

## Actual Output

`java.lang.NullPointerException Please check server logs for the stack trace.`
or
`java.util.NoSuchElementException Please check server logs for the stack trace.`
or
crash

## Additional information
The output exceptions seem to alternate randomly before the crash.

![Screenshot (209)](https://user-images.githubusercontent.com/56684558/109174816-7d365300-7785-11eb-9461-2d60b08471f3.png)

I tried a more trivial example schema and data but the bug reproducibility was way lower. It still happened, but not as reliably.

**Comment by haikalpribadi** [comment]
Thanks for the clear steps to reproduce the bug, @fatter-pale ! Will get on this soon.

**Comment by haikalpribadi** [comment]
FYI, if you need an alternative way to delete everything in a database, you can also just delete the database itself, by calling:
```
database delete testdb
```

**Comment by fatter-pale** [comment]
My pleasure, @haikalpribadi !
That is what I resorted to in the end, it's just that it felt more convenient to keep the schema intact and when trying different sets of data on it.

**Comment by haikalpribadi** [comment]
I agree. The query to delete all things like what you did is definitely more convenient and we'll make sure it should work!

**Comment by haikalpribadi** [comment]
This issue has been fixed by commit https://github.com/graknlabs/grakn/commit/86bb66493e5b55d1a09e92aec8786c3a30ff6cfb and will come out in the next release, @fatter-pale - thanks for raising an issue for the bug!
