### ISSUE TITLE
Triggering an undefined rule throws NullPointerException

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/grakn#6228]
## Description

Having Undefined any rule, making a query that would trigger the rule then throws a NullPointerException.

## Environment

1. OS (where Grakn server runs): Mac OS 10
2. Grakn version (and platform): Grakn Core 2.0 alpha 8
3. Grakn client: console

## Reproducible steps

1. Load the [docs schema](https://github.com/graknlabs/docs/blob/development/files/social-network/schema.gql)
2. We'll target this rule (any rule will do):
```
rule events-overlap:
		when {
			$e1 isa periodic-event;
			$e1 has start-date $sd1, has end-date $ed1;
			$e2 isa periodic-event;
			$e2 has start-date $sd2, has end-date $ed2;
			$sd2 > $sd1;
			$sd2 < $ed1;
			$e1 != $e2;
		} then {
			(overlapping: $e1, overlapping: $e2) isa event-overlap;
		};
```
3. Undefine the rule, commit, and try to trigger the rule
```
> transaction social_network schema write
social_network::schema::write> undefine rule events-overlap;

Concepts have been undefined
social_network::schema::write> commit
Transaction changes committed
> transaction social_network data read
social_network::data::read> match (overlapping: $e1, overlapping: $e2) isa event-overlap;

java.lang.NullPointerException Please check server logs for the stack trace.
>
```

**Comment by flyingsilverfin** [comment]
Closed with #6230
