### ISSUE TITLE
Type label validation

### ISSUE THREAD

**Issue by alexjpwalker** [graknlabs/grakn#6253]
## Problem to Solve

Currently our Type Labels are validated only at the Graql parser level, and not at the Concept level, meaning it is possible to define Types with invalid labels (null, empty string, labels starting with a number...)

These are particularly problematic because
- They can't be queried via Graql
- They throw errors on the client if a query happens to find them, eg `match $x sub thing`

## Current Workaround

Try very hard to not break the database.

## Proposed Solution

We should create a method in `graql` named `Graql.parseLabel` and use that to validate the label.

## Additional Information

A simple regex check will not do - Graql's label validation is too complex.

**Comment by flyingsilverfin** [comment]
@alexjpwalker is this done?

**Comment by haikalpribadi** [comment]
Yes, @flyingsilverfin, this issue has been implemented in this merged PR: https://github.com/graknlabs/grakn/pull/6254
