### ISSUE TITLE
Unable to install grakn-core-all

### ISSUE THREAD

**Issue by nicolamassarenti** [graknlabs/grakn#6292]
Hi,

I'm using Ubuntu 20.04. I previously installed grakn 2.0.0-alpha9 (it was running correctly), then I had to uninstalled it and now I am trying to install it again. 

Now I am facing a problem: it seems I'm no longer able to install it. I have this error:
![image](https://user-images.githubusercontent.com/38035878/114311323-95bcbb80-9aee-11eb-98dd-a02dd23dec29.png)

Do you know how I could solve this problem and install the software?

Thank you in advance.
Nicola

**Comment by lolski** [comment]
Hi @nicolamassarenti !

Can you check if you still have `grakn-core-server`, `grakn-core-console`, and `grakn-bin` installed? It is possible that some of them still are and If so, can you try to uninstall all of them?

Once done, you will be on a clean state. Then, try to install `grakn-core-all` again and let us know if the problem persists.

**Comment by nicolamassarenti** [comment]
Hi @lolski, 

I've checked and none of them is installed. 

![image](https://user-images.githubusercontent.com/38035878/114354269-44eca780-9b6e-11eb-8aa2-1adde36b5f30.png)

What else could I do to solve this issue? I am interested in installing Grakn Core 1.8.4 and Grakn Workbase 1.3.6.

**Comment by lolski** [comment]
@nicolamassarenti Right. Do you not want to install the latest Grakn Core which is 2.0.1? It works with Workbase 2.0.1. We have a strong recommendation for users to always stick with the newest version.

**Comment by nicolamassarenti** [comment]
We were interested in installing the latest Grakn Core (and we did it), but we noticed that in Workbase 2.0.1 the feature "Schema Designer" is missing and no estimated timeline is provided ([#388](https://github.com/graknlabs/workbase/issues/388)).

This feature is important to us because we are designing a new graph and it's easier to design it with a graphical tool.

Do you have any suggestion to solve the issue above?

**Comment by lolski** [comment]
@nicolamassarenti right okay. It is correct that we don't yet have a timeline for it.

However, do you only need it to view the schema? If that's enough for your use-case then you can do so in the current Workbase: https://github.com/graknlabs/workbase/issues/388#issuecomment-814722943

Let me know.

**Comment by nicolamassarenti** [comment]
@lolski unfortunately we need to view and simultaneously to "create" the schema, so I'd say that it's not sufficient to run the command `match $x sub thing;` for only viewing the schema. 

Having said so, to me the only possible alternative seems to come back to the previous version, namely _Grakn Core 1.8.4_ and _Grakn Workbase 1.3.6_. Is it possible to install these versions via APT? If yes, do you have any suggestions for solving the problem shown previously?

Thank you for the support!

**Comment by lolski** [comment]
@nicolamassarenti I see. Most users have had success with creating the schema by writing Graql directly in Grakn Console. While not ideal, we would recommend you to do the same, and I think it's not that bad.

If you insist on using Grakn 1.8.4, you can install it by forcing APT to install the version number of the package: https://askubuntu.com/a/428778. You will need to set the version of `grakn-core-all`, `grakn-core-server`, `grakn-console`, and `grakn-bin` accordingly.

However, bear in mind that we are not providing support / bugfixes since we want to concentrate our effort on 2.0.

**Comment by nicolamassarenti** [comment]
@lolski thanks for the information. Actually the support it's important to us, therefore we have decided to follow your suggestion and to proceed with the use of Grakn Core 2.0.1. 

At this point, since a colleague of mine has already worked several days to create the new schema and to populate the DB (by means of the feature _Schema Designer_ of Grakn Workbase version 1.3.6), we would like to avoid wasting the work. 
From your [doc](https://docs.grakn.ai/docs/management/migration-and-backup) it seems that it is possible to export the graph from the version 1.8.4 (command `grakn server export [database] [filename].grakn`) and to import it into the new version 2.0.1 (command `grakn server import [database] [filename].grakn`). Is it correct? Are required any other procedures?

In addition, since I am also going to re-install `grakn-core-all`, I still have to fix the problem mentioned at the beginning of this issue. I post below the screenshot where I try to install `grakn-core-all` and where I check if any of `grakn-core-all`, `grakn-core-server`, `grakn-console`, `grakn-bin` is installed: none of them is installed.

![image](https://user-images.githubusercontent.com/38035878/114399122-df65de80-9ba0-11eb-84cc-6e595fe82baa.png)

I really don't know why and how to solve the dependency problem. Do you have any suggestion about how to solve this issue?

Thanks

**Comment by lolski** [comment]
> From your doc it seems that it is possible to export the graph from the version 1.8.4 (command grakn server export [database] [filename].grakn) and to import it into the new version 2.0.1 (command grakn server import [database] [filename].grakn). Is it correct? Are required any other procedures?

@flyingsilverfin would it be something that's possible?

> In addition, since I am also going to re-install grakn-core-all, I still have to fix the problem mentioned at the beginning of this issue. I post below the screenshot where I try to install grakn-core-all and where I check if any of grakn-core-all, grakn-core-server, grakn-console, grakn-bin is installed: none of them is installed.

I am not yet sure what the problem is with this.

Can you try cleaning the distribution completely:

```
apt remove grakn-core-all grakn-core-server grakn-console grakn-bin
```

Followed by installing them, making sure to specify the exact versions:

```
apt install grakn-core-all=2.0.1 grakn-core-server=2.0.1 grakn-console=2.0.0 grakn-bin=2.0.0
```

**Comment by flyingsilverfin** [comment]
It depends on the schema - if your schema is compatible (eg. you transition it to Grakn 2.0 syntax and requirements and you don't have to make any further modifications except syntax) then you should be able to use the export feature

**Comment by flyingsilverfin** [comment]
It's also good practice to set up a data loading pipeline that you can re-run if you wish to re-install Grakn for instance, or if we release a version that has a breaking change and requires a re-import. I believe from 2.0 onwards expect users to be able to use the `export/import` functionality, but it hasn't been heavily used and tested much to this date - most users have their own import pipeline.

**Comment by nicolamassarenti** [comment]
> ...
> > In addition, since I am also going to re-install grakn-core-all, I still have to fix the problem mentioned at the beginning of this issue. I post below the screenshot where I try to install grakn-core-all and where I check if any of grakn-core-all, grakn-core-server, grakn-console, grakn-bin is installed: none of them is installed.
> 
> I am not yet sure what the problem is with this.
> 
> Can you try cleaning the distribution completely:
> 
> ```
> apt remove grakn-core-all grakn-core-server grakn-console grakn-bin
> ```
> 
> Followed by installing them, making sure to specify the exact versions:
> 
> ```
> apt install grakn-core-all=2.0.1 grakn-core-server=2.0.1 grakn-console=2.0.0 grakn-bin=2.0.0
> ```

Great, thanks @lolski! By explicitating the version I was able to install all the packages! 


> It depends on the schema - if your schema is compatible (eg. you transition it to Grakn 2.0 syntax and requirements and you don't have to make any further modifications except syntax) then you should be able to use the export feature

@flyingsilverfin I'm not sure I've understood. I am in the process of changing version, the graph we designed using version (1.8.4) is incomplete, therefore we want to "move" it to version _2.0.1_ to continue the design and to populate the graph. Is this possible?

For what concerns the import pipeline: yes, we will create them, but unfortunately at the moment we don't have any pipelines ready because we expected to be able to import/export the graph. Do you have some templates or material that could be useful in developing the pipelines?

Thanks!

**Comment by flyingsilverfin** [comment]
On the note of import/export - this feature really only works for _data_ . 
You first have to dump the schema (in 1.8.4 you need to use `./grakn server schema <database name>`), then make the required syntax changes for 2.0, load the schema into a Grakn 2.0 instance.

If your changes are strictly syntax changes (eg. you don't change your model with new types, change the attribute ownerships or role `plays`/`relates` etc) then you should be able to proceed to do a data dump in 1.8.4 using `./grakn server export <database name>`, and then load the file into Grakn 2.0

Does that make sense?

Our example on migrating phone-calls from csv is a good example - we have the guides in Java, Python and NodeJS.

Note that if you're loading from CSV, we highly recommend using Bayer's GraMI -- check out Henning's older blog post at https://towardsdatascience.com/introducing-grami-a-data-migration-tool-for-grakn-d4051582f867 and up-to-date github repo https://github.com/bayer-science-for-a-better-life/grami

You can build GraMI into a loading pipeline as well!

**Comment by nicolamassarenti** [comment]
Hi @flyingsilverfin , 

Thank you for answering to our doubts. We have indeed followed your instructions, we have exported the schema from version `1.8.4` with command `./grakn server schema <databse_name>`. 

We noticed that the syntax changes of our schema with respect to version `2.0.1` involved only the substitution of the keyword `has` with `owns`. 

We now have the current error:
![image](https://user-images.githubusercontent.com/38035878/114838857-6ac7b580-9dd5-11eb-880f-fde467113b70.png)

But I really don't understand what the problem is. As an example, I share here some samples of the schema, hopefully this can help you in better understanding the issue.

```
define


 sottotensione sub attribute,
    value string;

 timeout_sequenza_syncro sub attribute,
    value string;

analisi_rischi sub attribute,
    value string;

asse_D_bloccato sub attribute,
    value string;

asse_z_bloccato sub attribute,
    value string;

assistenza_e_garanzia sub attribute,
    value string;
...
```
and...
```
...
    uso sub ISTRUZIONI_PER_USO_E_MANUTENZIONE;

        silo_2 sub uso;

            configurazioni_stoccaggio sub silo_2;

            baia sub silo_2;

            console_comando sub silo_2;

            magazzino_verticale_multi-colonna_versatile sub silo_2;

            pulsantiera_mobile sub silo_2;

            vassoio sub silo_2;

        software_gestione sub uso;

            convenzioni_adottate sub il software_gestione;

            servizio_movimentazione-ICON_zeroTM sub software_gestione;

        modalita_uso sub uso;

            accensione_e_spegnimento_macchina sub modalita_uso;

            comando_macchina_manuale sub modalita_uso;

            corretto_carico_vassoi sub modalita_uso;

            prelevare_carico sub modalita_uso;

            ripristino_errori sub modalita_uso;

            ripristino_macchina_blackout sub modalita_uso,
                owns blackout_durante_movimentazione_elevatore,
                owns blackout_durante_movimentazione_catene_dispositivo_prelievo;
```

Can you give us any help? To me it seems that `define` is correct. Importing this would help us in saving the effort and work invested in designing the schema in version `1.8.4`.

Thank you in advance.
Nicola

**Comment by flyingsilverfin** [comment]
It would be most useful if we could have the entire schema to see where the syntax errors are... for one, we don't allow spaces in your types... did you manage to insert spaces in 1.8.4 in your types? if so you might have to re-name it in 1.8.4 and then try the export again.

I say this because I see an error in the following lines:
```
software_gestione sub uso;

            convenzioni_adottate sub il software_gestione;  # <---- can't have space between `il` and `software_gestione`

            servizio_movimentazione-ICON_zeroTM sub software_gestione;
            ```

**Comment by flyingsilverfin** [comment]
By the way, here's the summary of the changes in the Graql syntax in 2.0:
https://github.com/graknlabs/graql/releases/tag/2.0.0-alpha

**Comment by nicolamassarenti** [comment]
@flyingsilverfin thank you very much for the support!

Best,
Nicola
