### ISSUE TITLE
Port omitted test suites from Grakn Core 1.8

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/grakn#6580]
## Description
Port RuleScaling, and BenchmarkBig, BenchmarkSmall from Core 1.8. Requires fast TypeInference implementation.

**Comment by flyingsilverfin** [comment]
@krishnangovindraj i have removed this from the `Planning` milestone but we should still implement!

**Comment by flyingsilverfin** [comment]
Implemented in #6737
