### ISSUE TITLE
Grakn is missing from apt-get

### ISSUE THREAD

**Issue by gabefair** [graknlabs/grakn#882]
Creating a Personal Package Archive (PPA) for Grakn will allow users to install Grakn using a command like `apt-get install Grakn`
This is important b/c you don't want someone else taking that name from you.

**Comment by burukuru** [comment]
Thanks for flagging this up @gabefair. We'll need to have a chat internally about how to package Grakn for Linux distributions. I will post an update when that happens.

In the meantime I've registered us here: https://launchpad.net/~graknlabs
As far as I can tell, there is no way to reserve a package name.

**Comment by vmax** [comment]
Building/deploying DEBs is on our schedule currently.
